### ISSUE TITLE
[Forms] [Beta.28] NullReferenceException when clicking on attribution with link

### ISSUE THREAD

**Issue by Christoph-Majcen** [Mapsui/Mapsui#731] opened 2019-11-22 12:57 UTC
Nuget: Mapsui.Forms
Affected Versions: beta.28  

Description: When trying to click on the attribution link, the App crashes with an NullReferenceException

Repro Project: https://github.com/Christoph-Majcen/MapsuiAttributionRepro

StackTrace:
at Mapsui.UI.Forms.MapView.HandlerInfo (System.Object sender, Mapsui.UI.MapInfoEventArgs e) [0x000ec] in <bf398775e1254a9bbb006c8294c0bb73>:0 
  at Mapsui.UI.Forms.MapControl.OnInfo (Mapsui.UI.MapInfoEventArgs mapInfoEventArgs) [0x0000e] in <bf398775e1254a9bbb006c8294c0bb73>:0 
  at Mapsui.UI.Forms.MapControl.OnSingleTapped (Mapsui.Geometries.Point screenPosition) [0x0002f] in <bf398775e1254a9bbb006c8294c0bb73>:0 
  at Mapsui.UI.Forms.MapControl+<>c__DisplayClass37_0.<OnTouch>b__5 (System.Object l) [0x00051] in <bf398775e1254a9bbb006c8294c0bb73>:0 
  at System.Threading.Timer+Scheduler.TimerCB (System.Object o) [0x00007] in <19853c43ab794d18ab1a33ecb65b3c4d>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <19853c43ab794d18ab1a33ecb65b3c4d>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <19853c43ab794d18ab1a33ecb65b3c4d>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <19853c43ab794d18ab1a33ecb65b3c4d>:0

**Comment by pauldendulk** [comment] 2019-11-26 20:55
Thanks a lot for the sample that made it easy to reproduce it. I tried the same in the Mapsui samples but could not reproduce it there. I upgraded your sample to the beta 30 but it still got the NullReferenceException. I need to investigate this further.

**Comment by charlenni** [comment] 2019-12-16 18:52
See PR #745.

Thank you for reporting bug with repo.

**Comment by pauldendulk** [comment] 2020-02-01 19:36
should be fixed in 2.0.0-beta.33

**Closed by pauldendulk** 2020-02-01 19:36 UTC
Labels: bug 🐛
