### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. on Android/Xamarin Forms

### ISSUE THREAD

**Issue by josesimas** [Mapsui/Mapsui#433] opened 2018-06-04 11:31 UTC
Hello,

I upgraded recently to 1.4.2 (using Mapsui.Forms 0.2.1) and every now and then I get the error below. It is random but maybe it happens more when the map is off screen (on a tab that is not selected, for example). I am sorry I cannot provide a better bug report but may the stack trace will help. For the moment wrapping every call to Mapsui.Forms.MapView.RefreshGraphics() in a try/catch block solves the issue.

	Xamarin caused by: android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.
	Object name: 'SkiaSharp.Views.Android.SKCanvasView'.
	Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)<db1250be0eb4441f99401ee7818a9e4a>:0
	Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<db1250be0eb4441f99401ee7818a9e4a>:0
	Android.Views.View.PostInvalidate()<706ba34c11404af5a70a40b3615ae291>:0
	Mapsui.UI.Android.MapControl.RefreshGraphics()<c13b5b47cf5c441089ad69c9299ca90f>:0
	Mapsui.Forms.Android.MapViewRenderer.<OnElementChanged>b__4_0(MapView sender)<ad757c9e187340519b5278d48c3fd589>:0
	at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
	System.Reflection.MonoMethod.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)<438260da45914f6d95850cbf8108928b>:0
	--- End of inner exception stack trace ---
	System.Reflection.MonoMethod.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)<438260da45914f6d95850cbf8108928b>:0
	System.Reflection.MethodBase.Invoke(object obj, object[] parameters)<438260da45914f6d95850cbf8108928b>:0
	Xamarin.Forms.MessagingCenter.Subscription.InvokeCallback(object sender, object args)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.InnerSend(string message, Type senderType, Type argType, object sender, object args)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send<TSender>(TSender sender, string message)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.Send<TSender>(TSender sender, string message)<3754ae802c714b298131b9c985b370ad>:0
	Mapsui.Forms.MapView.RefreshGraphics()<e0b84dac711f49209ca4f84db73e0c3b>:0

Thanks,
Jose

**Comment by pauldendulk** [comment] 2018-06-04 21:33
I guess Xamarin.Forms explicitly calls dispose on its children when a tab is disposed. If there is still some pointer to the layers a change notification will try to access the disposed object. 

What I don't understand it why the skia canvas is disposed but but not the MapControl. This could be because of timing but it is not that likely. 

Calling an explicit unsubscribe in Dispose should fix this. This code was in Mapsui but got lost after some refactoring. I added it back.

**Comment by pauldendulk** [comment] 2018-06-04 21:37
I release 1.4.3-beta.2 with this fix.

**Comment by josesimas** [comment] 2018-06-04 21:39
Fantastics, that is great, thanks!

**Comment by pauldendulk** [comment] 2018-06-04 21:43
Don t cheer to early. I don t fully understand the problem. Please test.

**Comment by josesimas** [comment] 2018-06-05 08:54
Hi Paul,

No problem. I installed the beta and removed the workaround. So far so good
but this was a random occurrence. I will leave it like that for a while to
see if the exception appears again.

Thanks,
Jose

**Comment by josesimas** [comment] 2018-06-06 08:00
Hi Paul,

Unfortunately the bug still happens. I opened a record in my app, went to the map's tab and tapped the map, then selected a different tab and got the same exception. 

	Xamarin caused by: android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.
	Object name: 'SkiaSharp.Views.Android.SKCanvasView'.
	Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)<db1250be0eb4441f99401ee7818a9e4a>:0
	Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<db1250be0eb4441f99401ee7818a9e4a>:0
	Android.Views.View.PostInvalidate()<706ba34c11404af5a70a40b3615ae291>:0
	Mapsui.UI.Android.MapControl.RefreshGraphics()<c13b5b47cf5c441089ad69c9299ca90f>:0
	Mapsui.Forms.Android.MapViewRenderer.<OnElementChanged>b__4_0(MapView sender)<ad757c9e187340519b5278d48c3fd589>:0
	at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
	System.Reflection.MonoMethod.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)<438260da45914f6d95850cbf8108928b>:0
	--- End of inner exception stack trace ---
	System.Reflection.MonoMethod.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)<438260da45914f6d95850cbf8108928b>:0
	System.Reflection.MethodBase.Invoke(object obj, object[] parameters)<438260da45914f6d95850cbf8108928b>:0
	Xamarin.Forms.MessagingCenter.Subscription.InvokeCallback(object sender, object args)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.InnerSend(string message, Type senderType, Type argType, object sender, object args)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send<TSender>(TSender sender, string message)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.Send<TSender>(TSender sender, string message)<3754ae802c714b298131b9c985b370ad>:0
	Mapsui.Forms.MapView.RefreshGraphics()<e0b84dac711f49209ca4f84db73e0c3b>:0
	MyCode.ViewModels.MyPagePageViewModel.<RefreshMap>b__68_21()<83a68197a14d4a9ba6eed042f7956800>:0
	Java.Lang.Thread.RunnableImplementor.Run()<706ba34c11404af5a70a40b3615ae291>:0
	Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<706ba34c11404af5a70a40b3615ae291>:0
	at (wrapper dynamic-method) System.Object.d69e55f4-e049-41ca-89bb-101d7db413b9(intptr,intptr)
	mono.java.lang.RunnableImplementor.n_run(Native Method)
	mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
	android.os.Handler.handleCallback()Handler.java:751
	android.os.Handler.dispatchMessage()Handler.java:95
	android.os.Looper.loop()Looper.java:154
	android.app.ActivityThread.main()ActivityThread.java:6836
	java.lang.reflect.Method.invoke(Native Method)
	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1520
	com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1410

I repeated the exact same steps and nothing happened, really annoying.

In another instance, while debugging, I stopped at a breakpoint just before calling the mapping Navigate and the same happened. I suppose this is due to some timing issue. 

Thanks,
Jose

**Comment by pauldendulk** [comment] 2018-06-06 08:02
Thanks for testing. I will look into it.

**Comment by josesimas** [comment] 2018-06-06 08:02
No problem. Let me know if you want me to do more testing.

**Comment by charlenni** [comment] 2018-06-06 08:47
Could be related to [this](https://forums.xamarin.com/discussion/66566/cannot-access-a-disposed-object-appcompat-navigationpagerenderer). If I unterstand it correct, Xamarin disposes the native views while forms think, there are still there.

If I look to the code, it could be, that RefreshGraphics isn't called in the main thread. Perhaps this is the problem. MapRefreshGraphics does this.

**Comment by josesimas** [comment] 2018-06-06 08:52
That was my first thought, sometimes some view models' methods get called
from a different thread. I make sure that all the map interactions are on
the UI thread by wrapping them in _deviceService.BeginInvokeOnMainThread(()
=> blocks.

**Comment by charlenni** [comment] 2018-06-07 05:56
The problem could be the check, if the SKCanvasView is disposed or not. If I understand the process correct, than Xamarin.Forms dispose the page from the hidden tab and creates it later new, if the page is shown again.

Perhaps we could add a check, if the View is visible or not like
````
            if (_canvas.Visibility == ViewStates.Visible)
            {
                _canvas.PostInvalidate();
            }
````

**Comment by pauldendulk** [comment] 2018-06-07 17:57
@josesimas If you run RefreshGraphics on the main thread this would only prevent the problem if Dispose is called from the main thread. Do you know if this is the case? Is this how Xamarin works?

I just committed another attempt to fix this. I call PostInvalidate of the MapControl itself. Invalidate will also invalidate the children (at least thats how it worked on the platforms I used). This small change has two advantages. 

1. I do not access the _canvas handler for this. I guess somewhere inside Xamarin it is called but I assume they check dispose there. 
1. It is actually posted on the ui thread as @josesimas suggested. This is what PostInvalidate does extra over Invalidate.

Let's see. Hopefully you can test this again.

**Comment by josesimas** [comment] 2018-06-08 07:51
Hi Paul, did you release the changes to 1.4.3-beta.2 as well?

**Comment by josesimas** [comment] 2018-06-08 07:52
BTW, I am sorry, I don't know if Xamarin calls Dispose on the UI Thread. I
will investigate.

**Comment by pauldendulk** [comment] 2018-06-08 07:55
Ah no. Sorry. Forgot this was a v1.4 issue. Will do that soon

**Comment by pauldendulk** [comment] 2018-06-08 11:14
I pushed  1.4.3-beta.3 where PostInvalidate is used instead of _canvas.Invalidate(). On iOS similar with SetNeedsDisplay.

**Comment by josesimas** [comment] 2018-06-08 11:16
Great thanks, I will get it now and test.

**Comment by josesimas** [comment] 2018-06-08 14:36
Hi Paul,

I am afraid it is still there. I tried creating a simpler project and so far it did not crash. but the main app crashed very soon. Here is the stacktrace.

	Xamarin caused by: android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.
	Object name: 'SkiaSharp.Views.Android.SKCanvasView'.
	Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)<db1250be0eb4441f99401ee7818a9e4a>:0
	Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<db1250be0eb4441f99401ee7818a9e4a>:0
	Android.Views.View.PostInvalidate()<706ba34c11404af5a70a40b3615ae291>:0
	Mapsui.UI.Android.MapControl.RefreshGraphics()<c13b5b47cf5c441089ad69c9299ca90f>:0
	Mapsui.Forms.Android.MapViewRenderer.<OnElementChanged>b__4_0(MapView sender)<ad757c9e187340519b5278d48c3fd589>:0
	at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
	System.Reflection.MonoMethod.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)<438260da45914f6d95850cbf8108928b>:0
	--- End of inner exception stack trace ---
	System.Reflection.MonoMethod.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)<438260da45914f6d95850cbf8108928b>:0
	System.Reflection.MethodBase.Invoke(object obj, object[] parameters)<438260da45914f6d95850cbf8108928b>:0
	Xamarin.Forms.MessagingCenter.Subscription.InvokeCallback(object sender, object args)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.InnerSend(string message, Type senderType, Type argType, object sender, object args)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send<TSender>(TSender sender, string message)<3754ae802c714b298131b9c985b370ad>:0
	Xamarin.Forms.MessagingCenter.Send<TSender>(TSender sender, string message)<3754ae802c714b298131b9c985b370ad>:0
	Mapsui.Forms.MapView.RefreshGraphics()<e0b84dac711f49209ca4f84db73e0c3b>:0
	MyApp.ViewModels.SearchResultsPageViewModel.<RefreshMap>b__68_21()<83a68197a14d4a9ba6eed042f7956800>:0
	Java.Lang.Thread.RunnableImplementor.Run()<706ba34c11404af5a70a40b3615ae291>:0
	Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<706ba34c11404af5a70a40b3615ae291>:0
	at (wrapper dynamic-method) System.Object.d69e55f4-e049-41ca-89bb-101d7db413b9(intptr,intptr)
	mono.java.lang.RunnableImplementor.n_run(Native Method)
	mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
	android.os.Handler.handleCallback()Handler.java:751
	android.os.Handler.dispatchMessage()Handler.java:95
	android.os.Looper.loop()Looper.java:154
	android.app.ActivityThread.main()ActivityThread.java:6836
	java.lang.reflect.Method.invoke(Native Method)
	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1520
	com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1410

Jose

**Comment by pauldendulk** [comment] 2018-06-08 15:53
Thanks for the solid testing. I need to do some thinking. 

What could happen that RefreshGraphics is called right before Dispose is called from another thread. Dispose completes but the calls within RefreshGraphics continue. 

If this could be the problem then this should be a problem in many scenarios. Whenever an object is called from several threads this could happen. Should this be solved by checking on Disposed in every call, on every line? Even if you check the dispose could happen between the check and the call.

**Comment by pauldendulk** [comment] 2018-06-08 16:10
You say:

> It is random but maybe it happens more when the map is off screen (on a tab that is not selected, for example).

So, it also happens when the Map is on screen? Is it the same bug?

**Comment by pauldendulk** [comment] 2018-06-08 16:38
Object are collected when they are not connected anymore. If the Forms MapViewRenderer still is, and it points to the MapControl then they both can not be collected. If they are both detached they could be collected. Even if they are attached to each other. Perhaps this is happening.

**Comment by pauldendulk** [comment] 2018-06-08 16:38
@josesimas Is there any explicit Dispose call in your code?

There is none in the forms code.

**Comment by josesimas** [comment] 2018-06-08 20:02
Hi Paul,

Answering your questions:

1. I have never seen it crash while the map is on screen. The app just
crashes while I am somewhere else. I get the stack trace from Hockey App
(my app sends these crashes to this web service).

2. I don't call dispose on anything that is not mine and I don't call
dispose on any UI control. Bear in mind though that the app is rather
complex for a phone app and uses several third party controls, including
proprietary ones. Still, I have 2 maps in the app. One seats on a Tabbed
Page which is a Xamarin standard page and one seats on a third party tab
view. I get the same exceptions in both.

The app is already in the app store but in beta. I can send you the link
privately if you like.

Thanks,
Jose

**Comment by pauldendulk** [comment] 2018-06-08 21:30
I created a little console application to see how garbage collection works. There is a parent and child. If I set the parent to null and call GC.Collect it is immediately collected (the obvious situation). If the parent calls long running method (accessing the child) it does not get garbage collected. The method just keeps running. This last case is what is in the zip. 

[ResearchDisposeError.zip](https://github.com/Mapsui/Mapsui/files/2086143/ResearchDisposeError.zip)

So, the situation we have here is not just a regular situation.

**Comment by pauldendulk** [comment] 2018-06-09 06:37
The conclusion from my sample is that this is not how things work:

> What could happen that RefreshGraphics is called right before Dispose is called from another thread. Dispose completes but the calls within RefreshGraphics continue.

**Comment by josesimas** [comment] 2018-06-09 06:38
Yes they are both Mapsui maps.

**Comment by pauldendulk** [comment] 2018-06-09 06:42
When you catch the exception the functions properly?

**Comment by pauldendulk** [comment] 2018-06-09 06:47
You created a sample app which could not reproduce the problem. Perhaps you could call GC.Collect right after the call to RefreshGraphics to induce it.

**Comment by charlenni** [comment] 2018-06-09 07:00
I read the first message again and thought about, what could be happen. @josesimas says, that the problem occurs, if he change to another tab of his tab control. Perhaps the Xamarin.Forms wrapper calls a RefreshGraphics, because it gets invisible but is garbage collected already.

For me, it seems related to [this](https://forums.xamarin.com/discussion/66566/cannot-access-a-disposed-object-appcompat-navigationpagerenderer) problem (more at the end of the thread).

**Comment by pauldendulk** [comment] 2018-06-09 07:13
> Perhaps the Xamarin.Forms wrapper calls a RefreshGraphics, because it gets invisible but is garbage collected already.

If the wrappper calls RefreshGraphics there is a pointer from the wrapper to the MapControl and GC should never happen. The only scenario that I though could happen is that RefreshGraphics is called right before GC and te exception occurs because the object is collected while RefreshGraphics is still running. The sample app show that this is not how things work either. (btw, we could test the sample app with mono to see if it works the same there). It is getting more likely that there is a bug in something else.

I am going to study the thread.

**Comment by pauldendulk** [comment] 2018-06-09 07:13
@josesimas What version of Xamarin.Forms you use?

**Comment by pauldendulk** [comment] 2018-06-09 07:18
@josesimas Do you use AppCompat?

**Comment by pauldendulk** [comment] 2018-06-09 07:45
Read the thread. I was especially inspired by 'I give up' :). The original issue was resolved, but I assume that midix ran into another such issue. btw, code where there is a check on _dispose and then do something with that object can always fail in a multi-thread situation when there is no lock. So, I am not surprised there is an issue.

I am going to add a try-catch on RefreshGraphics and log if caught. In theory this could happen to other methods as well but I don't want to make the code too complicated. 

If we want to proceed we should focus on a reproducible sample. Perhaps first with Mapsui. If that succeed try to reproduce it without.

**Comment by pauldendulk** [comment] 2018-06-09 07:50
One more idea. Maybe I should create the SKCanvasView with the application context.

**Comment by pauldendulk** [comment] 2018-06-09 08:28
I am not going the use the application context. The context used right now is the context passed to MapControl. It should be under the control of the user of Mapsui. They can choose to use Application context of local activity context (Perhaps you could try that Jose). Although the application context could fix this exception this might introduce a memory leak. 

I see in Mapsui.Forms that the MapViewRenderer also initializes the MapControl with the Context passed to itself. That seems correct.

**Comment by pauldendulk** [comment] 2018-06-09 08:43
I am really trying to stop thinking about this and just add the try-catch, but...  Since, MapViewRenderer, MapControl and SKCanvasView are all children of the same activity there should be no problem. They will all get cleaned up at the same time. So why is there still access to members of the activity being disposed? My guess is this is because of the MessagingCenter which is global scope. Perhaps there should be an unsubscribe to those messages that the MapViewRenderer is listening to. This is the last thing about this :)

**Comment by pauldendulk** [comment] 2018-06-09 09:47
I pushed 1.4.3-beta.4. 

One thing I am still worried about. If PostInvalidate posts to the UI thread and the call is not will the exception be returned to the calling thread?

**Comment by pauldendulk** [comment] 2018-06-09 09:54
Summary. I assume there is an explicit Dispose somewhere in Xamarin. This could be the Activity wrapper. I can't see how such an exception could occur if there is no explicit Dispose. While Dispose is going on the MessageCenter, which is static and never disposed sends another RefreshGraphics. A proper solution would be to somehow unsubscribe to those message before the dispose. This is not something we can fix in Mapsui.

**Comment by charlenni** [comment] 2018-06-09 11:59
That could be the solution. The MessagingCenter is still active and calls the refresh. But I'm sorry, I couldn't help. Still I could not run Xamarin.Forms projects :(

**Comment by josesimas** [comment] 2018-06-09 17:47
Yes, when I catch the exception everything keeps working including the map
when I open it.

**Comment by josesimas** [comment] 2018-06-09 17:47
Version 2.5

**Comment by josesimas** [comment] 2018-06-11 09:10
Hello both,

I am sorry but I was away from the computer most of the weekend. I answered the email thread so my posts above are out of context.

I tried your suggestions about calling GC.Collect() just before RefreshGraphics but nothing happened. I also installed the latest beta (1.4.3-beta.4) and the maps stopped working altogether (grey background and panning and zooming don't work - I can see that because the scale widget does not change). I double checked if anything else had changed but it appears that this latest beta does not work at all regardless of the provider.

Cheers,
Jose

**Comment by pauldendulk** [comment] 2018-06-11 10:45
The GC.Collect was to be called after RefreshGraphics to trigger a collect while RefreshGraphics was still running. Perhaps it should be called from another thread so that both get called at the same time. It is just meant as a way to try to reproduce the problem. It is not that important anymore since I think I understand the problem.

Here are the commits for 1.4. 
https://github.com/Mapsui/Mapsui/commits/1.4
As you can see this is the only commit that affects the code. I can't see how adding a try catch could cause this problem.
https://github.com/Mapsui/Mapsui/commit/6fa634c6c25182aad8462e17924d4765a68051d6
But perhaps the best thing to do for now is to work with the previous version and use your try-catch workaround.

Wrapping this up. My conclusion is that the Activity actively calls Dispose on its children while the MessageCenter calls RefreshGraphics. This is not a bug in Mapsui. 

In Mapsui 2.0 a pure Xamarin.Forms implementation will be added. I would expect such a solution to be less problematic than with the render wrappers. Perhaps better to put my effort in this future solution :)

**Closed by pauldendulk** 2018-06-11 10:45 UTC
Labels: question

**Comment by josesimas** [comment] 2018-06-13 07:38
Indeed, I am looking forward to 2.0 :). Thanks Paul.

**Comment by pauldendulk** [comment] 2018-06-23 05:58
There is a new release with a fix for the map refresh.
