### ISSUE TITLE
Website/documentation high CPU usage

### ISSUE THREAD

**Issue by basvd** [Mapsui/Mapsui#2580] opened 2024-04-03 15:58 UTC
Forgive me for not using the bug report template, but this issue concerns the website and not MapsUI itself.

The website (any part of it) uses a full core of CPU for each tab that is open. This happens in multiple browsers, including Firefox, Chromium, and Edge. I think the issue is related to the search functionality of the DocFX generated site.

It would be really helpful if this can be solved, because right now I can't browse the documentation/API reference without my computer taking off.

**Comment by pauldendulk** [comment] 2024-04-12 10:28
Thanks for the report! Not sure what was the cause but I updated to the latest version of docfx (which needed some additional changes in our configuration) and things look better. The search is now fixed too.

https://github.com/Mapsui/Mapsui/pull/2587

**Closed** 2024-04-12 18:36 UTC
