### ISSUE TITLE
Map going blank

### ISSUE THREAD

**Issue by woemike** [Mapsui/Mapsui#746] opened 2019-12-16 22:04 UTC
Hello,

I am using Mapsui in a xamarin.forms app. I noticed that on Android 5, if I am pausing the app (pressing the home button or switching between apps), when I resume my activity the map is blank. Are you aware of this issue?

Kind regards,
Alexandru Mihai Ion

**Comment by charlenni** [comment] 2019-12-17 06:17
Can reproduce this on Android 5.0 with emulator, but not with Android 9.0.

**Comment by woemike** [comment] 2019-12-17 13:45
Thank you for your fast response. I can reproduce with: Samsung T285 (ANdroid 5.1.1) and Samsung S5 (Android 6.0.1), 100 %reproducibility. Any fixes? :(

**Comment by Catelinecz** [comment] 2020-01-10 08:27
I have the same problem with 2x Huawei ALE-L21 (Android 6.0 and Android 5.0.1). It happens every time when I leave the app. Using Mapsui 2.0.0-beta.30. Don't think it's problem connected with Android version, but maybe that customized ROMs that Huaweis and some Samsungs have. MapView.Refresh() doesn't work, couldn't find any fix :(.

**Comment by pauldendulk** [comment] 2020-01-12 08:40
It might be related to performance characteristics of the specific device. Although I would not expect a difference in the emulator in that case.

**Comment by charlenni** [comment] 2020-01-12 13:53
@pauldendulk The problem is, that RefreshGraphics() only invalidates the surface when GrContext is different from null. But if you come back, GrContext is null. If you remove the check and press the zoom in button, than the map is drawn again.

**Comment by charlenni** [comment] 2020-01-12 13:57
If I remember it correct, than the if clause was inserted to check, if SkiaSharp is initialized and don’t drawn anything before.

**Comment by charlenni** [comment] 2020-01-12 13:58
And even when removing this, we don’t get called, if the view appears on the screen again.

**Comment by charlenni** [comment] 2020-01-28 15:00
This problem should be solved with part 2 of #790. 

If your page is appearing again, you should call MapView.Refresh() to redraw the map. Otherwise it is redrawn after any move of the map.

**Comment by pauldendulk** [comment] 2020-01-29 17:54
Should be fixed in 2.0.0-beta.33. I will keep this open because I would like this to be tested.

**Closed** 2020-05-05 08:23 UTC
Labels: bug 🐛, mapview, needs-testing 🧪
