### ISSUE TITLE
UWP - Map disappears when PopAsync() from Navigation in Forms

### ISSUE THREAD

**Issue by spaddlewit** [Mapsui/Mapsui#838] opened 2020-02-24 18:40 UTC
UWP, Mapsui 2.0 - beta 35, SkiaSharp

Map blanks out when returning to it from a spawned child page.
This was tested in Mapsui.Forms, but it may exist in other implementation styles.

I created a small sample app to reproduce the issue:

[MapsuiBug.UWP.zip](https://github.com/Mapsui/Mapsui/files/4246186/MapsuiBug.UWP.zip)

**Comment by pauldendulk** [comment] 2020-02-24 19:07
Thanks a lot. Did this work properly for you in earlier versions? Which version did you first see this?

**Comment by spaddlewit** [comment] 2020-02-24 19:15
My mistake on the report -- I made the sample app using beta35.
Yes, it worked properly in previous versions. It broke somewhere between beta28 and beta32. I'd narrow it down further, but VS isn't letting me pick NuGets inbetween those versions for some reason.

**Comment by spaddlewit** [comment] 2020-02-24 19:22
I was able to narrow down a little futher. Looks like it happened somewhere between beta28 and beta30.

**Comment by pauldendulk** [comment] 2020-02-24 19:30
Thanks, that helps a lot.

**Comment by pauldendulk** [comment] 2020-02-24 19:47
The sample makes it very easy to test.

beta.28 works properly
beta.29 crashes immediately because skiasharp was updated but the nuspec wasn't
beta.30 shows the problem.

So it is caused by the skiasharp upgrade to 1.68.1, which is unfortunate because it is not under our control.

**Comment by spaddlewit** [comment] 2020-02-24 19:49
What if you try it with the 1.68.2 previews?

**Comment by pauldendulk** [comment] 2020-02-24 19:55
Good idea.

There were also some other changes, so it could be something else. Here some commits in between the beta.29 and beta.28 tag:
https://github.com/Mapsui/Mapsui/commits/master?after=6f9c95579e6f223553f66d4a5310a504520ded03+209

Here the release notes of beta.29
https://github.com/Mapsui/Mapsui/releases/tag/2.0.0-beta.29

Xamarin.Forms upgrade is also a suspect.

**Comment by pauldendulk** [comment] 2020-02-24 20:13
skiasharp 1.68.2 previews does not fix it.
Latest stable Xamarin.Forms 4.4.0.99etc does not fix it.

**Comment by pauldendulk** [comment] 2020-02-25 08:28
I created a minimal reproduction for skiasharp based on you sample, but with Mapsui removed. I hope you don't mind.

https://github.com/pauldendulk/skiasharp-uwp-blank-screen

**Comment by pauldendulk** [comment] 2020-02-25 08:31
I submitted a skiasharp issue:
https://github.com/mono/SkiaSharp/issues/1155

**Comment by charlenni** [comment] 2020-02-25 09:48
I assume, that this is the same problem as #677 and some others. It seems, that SkiaSharp miss to call OnPaintSurface when it is again visible on the screen. Don't no, if Skia is mentioned about this event, but than don't understand, why this should only be the case in Mapsui.

**Comment by pauldendulk** [comment] 2020-02-25 10:33
Well I can reproduce it without Mapsui. Let's hear what they say.

The paint event is called. I can see that in the debugger. Just nothing shows. Might be related to threading.

**Comment by charlenni** [comment] 2020-02-25 10:42
In such cases I saw, that the GrContext is null. Perhaps this is the reason, why it is only seen on SKGLView?

**Comment by pauldendulk** [comment] 2020-02-25 14:09
ah, I should check if CrContext is null.

**Comment by spaddlewit** [comment] 2020-02-25 14:11
I don't mind at all. Priority #1 is solving problems. :) Hopefully Skia has some insight.

**Comment by pauldendulk** [comment] 2020-02-26 06:27
GrContext is not null.

**Comment by pauldendulk** [comment] 2020-04-04 10:53
@spaddlewit Could you explain a bit more here about your use case: https://github.com/mono/SkiaSharp/issues/1155

**Comment by mattleibow** [comment] 2020-04-06 19:22
Hey folks, just a quick update. I think I fixed the issue, see https://github.com/mono/SkiaSharp/issues/1155#issuecomment-609988075

**Comment by pauldendulk** [comment] 2020-04-26 08:39
@spaddlewit This issue should be fixed with rc.3.

**Comment by spaddlewit** [comment] 2020-05-11 21:22
Appears to be fixed. Thank you so much!

**Comment by charlenni** [comment] 2020-05-12 03:40
Could you then please close the issue?

**Comment by radderz** [comment] 2020-05-12 04:28
Closing..

**Closed by radderz** 2020-05-12 04:28 UTC
Labels: bug-in-dependency, needs-testing 🧪
