### ISSUE TITLE
After zooming or panning, clicking doesnt work

### ISSUE THREAD

**Issue by johnhs91** [Mapsui/Mapsui#898] opened 2020-04-23 06:52 UTC
Hello

I got a map, in little view, when you double click it, it will open in full screen.
Problem is, if I pan or zoom. (Via 2 fingers) something is triggered in Mapsui, so I can't double click anymore.
Everytime I double click afterwards, it still triggers pan or zoom.

I've debugged, and it go into SKTouchAction.Moved, if I just use 1 finger and double click.
Worst part of this is, when I go into OnTouchMove, the method that is triggered in touch. It actually belive I used 2 fingers on the map. 

I've tried to make a workaround where I disable pan and zoom on the little view. But it doesn't help, same bug occurred.

I'm using Mapsui 2.0 beta 35

Br. John Sørensen

**Comment by charlenni** [comment] 2020-04-23 07:37
You didn’t mention, which Mapsui control do you use. Android, iOS, UWP or Forms?

**Comment by johnhs91** [comment] 2020-04-23 07:46
I'm using forms sorry.
The issue is on both android and iOS.

**Comment by charlenni** [comment] 2020-04-23 13:52
I tried to reproduce this here on iOS, but couldn’t find a problem. Panning and zooming with two fingers and than double click on the map works perfect. Tested it with the “Add Pin Sample” for Forms.

Do you use two different MapViews for this? Could it be, that you didn’t set the double click flag to true?

**Comment by johnhs91** [comment] 2020-04-24 06:50
I use the same view for both.
I've been debugging in control to check, if it was my code. But it's all in Mapsui i find the issue.

OnTouch in MapControl (Forms) trigger only moved, if I moved with 2 fingers once. And when it call OnTouchMove it always find 2 fingers. So it make it pan or zoom instead of click somehow.

To be honest I'm not sure if iOS and android is the same problem. I've only debugged your code on android. So I don't know how there can be a difference here.
If you try to do same with android, does it work too then?

**Comment by johnhs91** [comment] 2020-04-24 06:55
I can easily double click the map, if I don't zoom or pan before that.
And I got no code that manipulate with mapsui code. So I have no clue why this happens.
Can it be the skiasharp version? or is it fixed ?

**Comment by charlenni** [comment] 2020-04-24 11:22
Ok, I now checked it on Android with the "Add Pin Sample". No problem. Moving/zooming with two fingers around and than make a double click on the map leads to a OnDoubleTapped event for the MapControl.

Could you test it with the normal Forms sample? Could you provide some code to test it here?

**Comment by johnhs91** [comment] 2020-04-27 06:58
Wierd part from my side is, that it only happen when the map is small.
Not when it's in fullscreen. (There is no difference in MapsuiView in small and big, only my own custom props)
After some debugging, I've found the reason. But how, is still a mystery.

Reason that I never get double tap, after zoom or pan, is that "_touches" doesn't get cleared after those 2 events, (Only in the small map, works fine in big)
So after zoom or pan, there is 1 TouchEvent in the list. So next time I double click, it never get to _touches.count == 0 in the release if.

**Comment by johnhs91** [comment] 2020-04-27 07:04
Maybe a stupid question.
But when the ActionType is Cancelled. Shouldn't the _touches directory be cleared, instead of just removing 1 item?

**Comment by johnhs91** [comment] 2020-04-27 07:11
Okey, I belive I got the reason now.
In the small view, the map is inside a scrollview.
When it's inside the scrollview, I can interact with the view with double fingers (Zoom and pan), but because the scrollview take over events, the MapControl throw ActionType.Cancelled. But as I wrote above, in cancelled it only remove 1 touchevent, but it only get called once. So there is always 1 touch in the directory left.

I can fix myself by clearing the directory on cancelled. But I don't know if you know a better way.

**Comment by charlenni** [comment] 2020-04-27 10:04
Looked into this for Android. It seems, that the ScrollView catch the one finger events, but not the two finger events. 

With this in mind, I would say, that this never works. Who should handle the one finger touch events? The ScrollView to move the ScrollView content around or the MapView to move the map around. I assume, that you have to create a special handling this use case. Perhaps check the ScrollView touch event and if it is inside the MapView, then let handle MapView this event and instead handle it by ScrollView.

**Comment by charlenni** [comment] 2020-04-27 10:37
I tested it here on a real device and would say, that this doesn't work.

Put a first finger onto the map, than a second one. If you move the second one, than you could zoom the map, but if you move the first finger, the ScrollView catches this move and cancel the touch of the first finger. If you now lift the second finger, than all touch events in MapView are cleared and you could start again.

I would say, that this is normal behavior of ScrollView: catch first finger movements and cancel this finger for all childs. If you have two fingers, ScrollView doesn't handle this touches. If you lift the first finger and move the second, than this is a single finger event for ScrollView and it is handled, which lead to a cancelled event for the second finger.

I assume, that you get the same problem, if you put a ScrollView inside a ScrollView. Which one should react? And you not the only one, who have this problem. If you have a map in a web page, you have to use two fingers to move it. If you only use one, than you move the web page.

**Comment by johnhs91** [comment] 2020-04-27 11:55
Well the problem isn't that they interact with each other.
I can turn off all zoom and pan on MapsuiView and it still doesn't get cancelled on other than 1 touch, from Skia. Meaning either is a error in Skia, or that cancelled is ment to be called once, if that's the case, then you need to make a _touches.clear().

I know phone or ipad device can't handle mapsui in scrollview, that make sense. But if I make panlock, zoomlock and only try to catch double click. It still doesn't get to me, if they used 2 fingers before that.

I'll just say again, the problem isn't the interaction with scroll and mapsui. The problem is Mapsui got a bug, if i hit the map with 2 fingers, while it's inside scrollview. In forms.

**Comment by charlenni** [comment] 2020-04-27 12:12
I tested it. If you put the first finger on map, than you get a pressed event. Than you put the second finger on the display and you get a pressed event for the second one. If you move the second finger, you zoom the map. If you now move the first finger, than the ScrollView send a cancelled event for this finger and catches after this moment all events. I would say, that this is a Xamarin.Forms bug, because say don't send a cancelled for the second finger nor send events for fingers beside the first one.

**Comment by charlenni** [comment] 2020-04-27 12:23
Did you tried to set [InputTransparent](https://docs.microsoft.com/de-de/dotnet/api/xamarin.forms.visualelement.inputtransparent?view=xamarin-forms) for the ScrollView?

**Comment by johnhs91** [comment] 2020-04-27 12:28
If I change that, Mapsui won't reciew any events, and I still need the double tap.

**Comment by johnhs91** [comment] 2020-04-27 12:34
Aha I understood the property wrong.
It works with this, thank you very much.

**Comment by johnhs91** [comment] 2020-04-27 12:36
I need to make custom change to Mapsui, so it clear propperly I guess, since you don't belive it's a bug, that's the only thing I can do.

**Comment by charlenni** [comment] 2020-04-27 12:40
Has nothing to do with beliving if this is a bug or not. You say, that I always have to clear all touches, if a cancelled event is raised. But is this correct for everyone? Did you tested this with other Xamarin.Forms view too? Is this the correct behavior?

If I understand you right, then you want only double clicks for the MapView controll, no pan or zoom. Is this correct? If yes, why not create your own events for this. Deactivate events for the MapView and catch them in your ScrollView.

PS: Perhaps it would be possible to see a screenshot of the screen.

**Comment by johnhs91** [comment] 2020-04-27 12:50
[https://imgur.com/a/WuILtNi](url)

As you see whole view except top is scroll. 
If I set InputTransparent I can't scroll if my finder is on either button, input or mapsui (Last is fine but not first 2)
If InputTransparent is false, I can't double click on the map, to get full screen.

**Comment by charlenni** [comment] 2020-04-27 13:26
It isn't easy to decide, what is the right way to do this. The [official documentation](https://developer.android.com/reference/android/view/MotionEvent.html) from Android says, that an ACTION_CANCEL abort the gesture. The important sentence is perhaps this: "The number of pointers only ever changes by one as individual pointers go up and down, except when the gesture is canceled." They say not more. Would be nice to read, that in this case all touches are aborted. But I assume, that this is meant.

I assume, that in case of a cancelled touch all touches should be cleared. I make a PR for this.

I'm not sure, how iOS handle this. If I look into [SkiaSharp](https://github.com/mono/SkiaSharp/blob/354d85d129e898071e002a3157e7fcba1d7830a7/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SKTouchHandler.cs#L85), then normally the cancelled should be called for every finger. So this should work. And after I tested it, I would say, it works. iOS handles it correct.

So, if I apply your suggested changes it would work on Android, but not on iOS. And what's going on with UWP, Mac and others?

**Comment by johnhs91** [comment] 2020-04-27 18:49
I can see it isn't easy. For me it's since, I only got one usercase here. But I know you got to handle more than this one.

I got same issue on iOS as android. So I assume, it's same reason, haven't done debug on iOS, so can't say for sure it's the same. But it happens too after using 2 fingers on the map.

**Comment by charlenni** [comment] 2020-04-28 07:48
Perhaps I could create a PR which cleares all touches when cancel is called on Android. But for iOS I should first find the problem. Can not reproduce it here. It would be helpful, if you could try to get the problem on iOS. Don't know, what to do with all the other platforms.

**Comment by johnhs91** [comment] 2020-04-28 08:12
We are not gonna update our app next 2 month anyway.
We found a solution, so our customers don't need this feature atm.

I will try to find time to debug iOS later this week. And I'll write when I know more.

**Comment by charlenni** [comment] 2020-04-30 14:30
See #902

**Comment by pauldendulk** [comment] 2020-05-02 10:31
Will be fixed in Mapsui-2.0.0.

**Comment by pauldendulk** [comment] 2020-05-02 10:32
> Will be fixed in Mapsui-2.0.0.

I enjoyed writing that :)

**Comment by pauldendulk** [comment] 2020-05-24 09:35
Assuming this is fixed.

**Closed by pauldendulk** 2020-05-24 09:35 UTC
Labels: bug 🐛, needs-testing 🧪
