### ISSUE TITLE
Map on tabbed page not shows when moving back to tab on Android (but does in windows)

### ISSUE THREAD

**Issue by raymondjstone** [Mapsui/Mapsui#1863] opened 2023-02-27 08:30 UTC
**Describe the bug**

Maui/Blazor app, tabbed pages (2), page 1 has the map on it (and also a maui control), page 2 has a maui control only.

Tab1 shows initially and is correct and shows the map along with the various layers I add to it. when switching to tab2 that page then shows correctly. 

Switching back to tab1 however the page shows but only the maui controls, the map itself is missing and calling refreshGraphics in the NavigateTo method does not help

running in windows this works fine, running on android device it does not (both emulator and physical machine).

map control is in an absolute layout object within the page

**To Reproduce**

switching from tab with map to tab without map and back again

**Expected behavior**
Tab1 should show as it did initially with the map

**Screenshots**

**Desktop (please complete the following information):**
Windows 11, VS2022, latest version of maui and mapsui as of 22nd Feb

**Smartphone (please complete the following information):**
Pixel 4a (physical machine)
Pixel 5 emulator

**Additional context**
Issue also happens when no layers are added to the map as well.

**Comment by janseris** [comment] 2023-03-16 23:29
Related https://github.com/Mapsui/Mapsui/issues/1816 ?

**Comment by pauldendulk** [comment] 2023-04-10 19:55
I am closing this because I assume this is fixed by setting `UseGPU = false;`.

**Closed by pauldendulk** 2023-04-10 19:55 UTC
Labels: bug 🐛

**Comment by janseris** [comment] 2023-04-11 07:45
> I am closing this because I assume this is fixed by setting `UseGPU = false;`.

Thank you however that is only a workaround. It's not a fix. UseGPU false seems like CPU rendering will be used instead of GPU rendering which probably has large effect on framerate and UI responsibility for demanding controls like maps.

**Comment by pauldendulk** [comment] 2023-04-11 09:33
> Thank you however that is only a workaround. It's not a fix. UseGPU false seems like CPU rendering will be used instead of GPU rendering which probably has large effect on framerate and UI respondability for demanding controls like maps.

@janseris Yes, but it is likely a SkiaSharp issue, which will probably not be fixed quickly. There have been problems with the GPU rendering for years. It is probably something with pointers going wrong on a native level,  nasty stuff, and not easy to reproduce. If you want to help you could try to create a minimal reproducing sample with SkiaSharp without Mapsui. Like this: https://github.com/Mapsui/Mapsui/issues/1896#issuecomment-1494233384

**Comment by janseris** [comment] 2023-04-11 13:23
> Found it again when searching for this old problem: [mono/SkiaSharp#1232](https://github.com/mono/SkiaSharp/issues/1232)

That issue should be reopened, right?

**Comment by pauldendulk** [comment] 2023-04-11 14:12
@janseris I think it would be the best option to rebuild @charlenni's [sample](https://github.com/charlenni/SkiaTest) with MAUI and submit a new issue. Refer to the old issue in the new issue.

**Comment by janseris** [comment] 2023-04-11 16:37
> @janseris I think it would be the best option to rebuild @charlenni's [sample](https://github.com/charlenni/SkiaTest) with MAUI and submit a new issue. Refer to the old issue in the new issue.

OK I don't have that much interest in doing it to take the time for that.

**Comment by anmelegov** [comment] 2023-06-19 15:31
Unfortunately, the only workaround is to fully reinstantiate map view but it causes an another problems like memory leaks, crashes when switching tabs fast, managing state map, etc. If anyone finds a better workaround please let me know
