### ISSUE TITLE
[QUESTION] App crashes when deployed to iOS. Mapsui.Maui 4.0.0-beta.8

### ISSUE THREAD

**Issue by erdogdum** [Mapsui/Mapsui#1872] opened 2023-03-08 09:35 UTC
I have just created a .net MAUI app (net6.0) and installed the Mapsui.Maui from NuGet.

I just followed the instructions defined in "Mapsui MAUI getting started" guide.

The app builds and runs well on Windows and Android. It also builds for iOS but when I try to launch the app in iPad and iPhone, it crashes with the following error output :

```
[0:] An error occurred: '@rpath/libSkiaSharp.framework/libSkiaSharp'. Callstack: '   at SkiaSharp.SKPaint..ctor()
   at Mapsui.Rendering.Skia.LabelStyleRenderer..ctor()
   at Mapsui.Rendering.Skia.MapRenderer..ctor()
   at Mapsui.UI.Maui.MapControl..ctor()
   at MauiApp1_60.MainPage..ctor() in D:\Projeler\TEMP\MauiApp1-60\MainPage.xaml.cs:line 11
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)'
The app has been terminated.
```
It sounds like there is problem with SkiaSharp. When remove the construction of mapcontrol, it runs. So i think it is not related to any provisioning or certificate issue.

I also added the .UseSkiaSharp() command in MauiProgram class as :

```
public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.UseSkiaSharp(true)
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

		return builder.Build();
	}
```

What i am doing wrong ? According to documentation, everything looks ok. 

**Expected Behavior**

Showing a basic map.

**Actual Behavior**

App crashes

**Basic Information**

- Version with issue:  
   Mapsui.Maui (4.0.0-beta.8) 

- IDE:  
  Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.5.0 (Windows 11)
- Platform Target Frameworks: 
  iOS:  13.6
- Target Devices:  
  iPad 9. Generation, iPadOs : 16.3.1

<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

Microsoft Visual Studio Enterprise 2022
Version 17.5.0
VisualStudio.17.Release/17.5.0+33414.496
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

ASP.NET and Web Tools   17.5.317.37931
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.317.37931
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.5.317.37931
Azure Functions and Web Jobs Tools

C# Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2307502+8b3141d86b738daf2ca3ed9c15b12513071fc676
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40118.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77


Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```
</details>

**Comment by inforithmics** [comment] 2023-03-11 14:33
I tried it with Visual Studio for Mac 2022 17.5 and it worked with .NET 6 MAUI and .NET 7 MAUI.

I suggest that you use .NET 7 MAUI because a lot of Bugs are fixed there. What I discovered that it didn't work on first try. Only after second or third try it worked. Sometimes the Dependencies especially the SkiaSharp native Dependencies are not resolved on the first try.

Sometimes it helps adding an Excplicit Dependency to SkiaSharp.

dotnet add package SkiaSharp.Views.Maui.Controls --version 2.88.3
dotnet add package SkiaSharp.Views.Maui.Controls.Compatibility --version 2.88.3
dotnet add package SkiaSharp.HarfBuzz --version 2.88.3
dotnet add package SkiaSharp --version 2.88.3

**Comment by pauldendulk** [comment] 2023-04-04 16:31
Could you try to run it with `MapControl.UseGPU = false;`?

**Comment by pauldendulk** [comment] 2023-05-17 08:21
@sylverbee Was this with `MapControl.UseGPU = false;`?

**Comment by Inrego** [comment] 2023-05-23 05:47
Just want to add some information and a workaround. This issue only appears when using Hot Reload (iOS device connected with USB cable to Windows). If connecting the iOS device to the Mac and deploying that way, the issue disappears. It does indeed seem like a SkiaSharp issue. You can track the issue on their repo here: https://github.com/mono/SkiaSharp/issues/2410

Although, it doesn't seem to have any involvement from the maintainers.

**Comment by pauldendulk** [comment] 2023-05-29 12:01
@Inrego Thanks for that information. Although I am not sure if this will apply to all situations. SkiaSharp uses a native library, and if something is wrong with pointers to native memory this does not always result in the same behavior. If you point outside of allocated memory what happens depends on what data is on the outside. It could be harmless, it could result in incorrect behavior, or it could crash the app. So, in the end I think there is a real bug in there but it does not always show. This makes it such a hard issue.

**Comment by sylverbee** [comment] 2023-06-02 07:56
> @sylverbee Was this with `MapControl.UseGPU = false;`?

Where do you set it? I saw many posts with this info but no details on how and where to set it.

**Comment by Inrego** [comment] 2023-06-02 08:17
> @Inrego Thanks for that information. Although I am not sure if this will apply to all situations. SkiaSharp uses a native library, and if something is wrong with pointers to native memory this does not always result in the same behavior. If you point outside of allocated memory what happens depends on what data is on the outside. It could be harmless, it could result in incorrect behavior, or it could crash the app. So, in the end I think there is a real bug in there but it does not always show. This makes it such a hard issue.

I disagree. It's always the same behavior as far as I'm aware (100% reproducible). As soon as you use any objects from the SkiaSharp namespace while using Hot Restart, the app crashes. I think it's more an issue related to native libraries not being loaded correctly when using Hot Restart (not to be confused with Hot Reload).

Hot Restart is such a weird name for debugging using an iOS device connected directly to the Windows dev machine. But the name does hint at why there's a difference between debugging one way versus another. Using Hot Restart, you don't need a Mac build host. I assume they ship an empty ios app shell, and just load the compiled assemblies into it when debugging. For the same reasons, you can't change the app icon among a few other metadata on Hot Restart. I guess there's a limitation with this way of doing things, where you can't load these native libraries. I've observed similar issues with SQLite.

I do think this issue is actually documented:
https://learn.microsoft.com/en-us/dotnet/maui/ios/hot-restart#limitations

> Static iOS libraries and frameworks aren't supported and you may see runtime errors or crashes if your app attempts to load these.

When plugging your iOS device into the mac, and debugging through a Mac connection this way - the complete app is built, and this process includes native libraries properly.

**Comment by pauldendulk** [comment] 2023-06-02 10:54
> > @sylverbee Was this with MapControl.UseGPU = false;?

> Where do you set it? I saw many posts with this info but no details on how and where to set it.

@sylverbee Exactly like that anywhere in your code. UseGPU is a static field. Of cours you need to use the namespace of the MapControl, which is different for each platform.

**Comment by pauldendulk** [comment] 2023-06-02 11:01
@Inrego aha, that changes my understanding. So, for Hot Restart it will never work, and this is not just a bug but a limitation of this solution. Thanks for pointing that out. Also, I did not realize the difference between Hot Restart and Hot Reload in your earlier remark, thanks.

**Comment by pauldendulk** [comment] 2023-06-10 07:01
### Conclusion

This is a limitation of Hot Restart

https://learn.microsoft.com/en-us/dotnet/maui/ios/hot-restart#limitations

**Comment by mattleibow** [comment] 2023-06-14 09:12
Which limitation specifically?

SkiaSharp is a dynamic framework and should work with debug builds of apps. I am going to check again as this was working and is usually how I do the SkiaSharp + MAUI development.

**Comment by pauldendulk** [comment] 2023-06-14 10:11
I assumed the 'Static iOS libraries and frameworks aren't supported' under the Limitations section here would apply https://learn.microsoft.com/en-us/dotnet/maui/ios/hot-restart#limitations. If not, and this could be fixed it would be great.

**Comment by pauldendulk** [comment] 2023-06-14 10:13
@mattleibow I do not use Hot Restart myself, so hardly know what I am talking about, perhaps others can chime in, @Inrego @inforithmics

**Comment by Inrego** [comment] 2023-06-14 10:38
I made the same assumption. It's not something I have deep knowledge about. It's just assumptions made based on the symptoms I see.
And those symptoms are, that the app crashes as soon as any SkiaSharp object is initialized when the app is launched with Hot Restart. When deployed using remote iOS device, it's working fine.
With those symptoms and that phrase under limitations, I just guessed that those two were connected.

**Comment by Inrego** [comment] 2023-06-14 10:40
@mattleibow when you do .NET MAUI + SkiaSharp development. Do you debug with iOS connected with USB port directly on the Windows machine? And deploy using `iOS Local Devices > Device Name`?

**Comment by mattleibow** [comment] 2023-06-15 07:12
I usually do. Let me confirm with all the latest stable bits just to make sure there is no new bug.

What version of VS, MAUI and IOS are people on these days?

**Comment by pauldendulk** [comment] 2023-06-15 08:41
@Inrego @erdogdum @sylverbee Could you help @mattleibow with this question? He is the maintainer of SkiaSharp so could help us determine the core problem.

**Comment by sylverbee** [comment] 2023-06-26 13:32
> I usually do. Let me confirm with all the latest stable bits just to make sure there is no new bug.
> 
> What version of VS, MAUI and IOS are people on these days?

iOS 15.7.15 / 16/5.x
VS 2022 17.6.4
not MAUI but Xamarin.Forms 5.0.0.2578

**Comment by pauldendulk** [comment] 2023-11-12 16:34
I assume this is fixed by the updating to the latest skiasharp

**Closed by pauldendulk** 2023-11-12 16:34 UTC
Labels: question
