### ISSUE TITLE
CenterOnAndZoomTo Not Working Unless Delayed

### ISSUE THREAD

**Issue by nm4568** [Mapsui/Mapsui#2275] opened 2023-11-12 01:27 UTC
**Mapsui Version**
Mapsui Version v4.1.1
Mapsui.ArcGis v4.1.1

**Mapsui Platform**
.NET MAUI

**Device**
iPhone 14 Pro Max

**Describe the bug** 
CenterOnZoom only works when delayed.

**To Reproduce**
1) Launch Sample App with MainPage provided.

**Expected Result** - CenterOnAndZoomTo should work within Map_Loaded event handler of MainPage.xaml.cs

**Actual Result** - CenterOnAndZoomTo does not work - only works when task is delayed by adjusting the ZOOM_DELAY constant at the top of MainPage.xaml.cs.  Change constant from 0 to 5000 for a workaround.

**Additional context**
Sample Repo - https://github.com/nm4568/MapsuiSamples/tree/bug/zoom-issue

**Comment by pauldendulk** [comment] 2023-11-12 08:27
Thanks a lot for the sample project! This makes things so much easier, and I learn from seeing your code. I like the image layer you use.

In Mapsui changing the viewport depends on the size of the canvas and the extent of the data and this not known during startup. This is why the Map.Home method was added. This method is called ones those are known. I could fix your problem by writing it like this:

```csharp
var layer = await CreateLayerAsync(default);
mapControl.Map?.Layers.Add(layer);

double x = -9188151.36056;
double y = 3235144.74039;
var point = new MPoint(x, y);
mapControl.Map.Home = (n) => n.CenterOnAndZoomTo(point, resolution: 1000, 500, Mapsui.Animations.Easing.CubicOut);

MyMapControl = mapControl;
Content = mapControl;
```

It now starts like this:

![image](https://github.com/Mapsui/Mapsui/assets/963462/f8107890-da01-4118-b916-6bea8d451cac)

###Notes:
- I tested on Windows, not on Mac or iOS, but I assume the fix also works there.
- Perhaps we should add the to the FAQ.
- I expect the Mapsui logger to log a warning when CenterOnAndZoom is called too early. I did not see that warning.
- You do not always need to the canvas size, and in this particular case (where resolution and center are set). I think you don't need it. Perhaps we can improve this.

**Comment by pauldendulk** [comment] 2023-11-12 08:27
Thanks a lot for the sample project! This makes things so much easier, and I learn from seeing your code. I like the image layer you use.

In Mapsui changing the viewport depends on the size of the canvas and the extent of the data and this not known during startup. This is why the Map.Home method was added. This method is called ones those are known. I could fix your problem by writing it like this:

```csharp
var layer = await CreateLayerAsync(default);
mapControl.Map?.Layers.Add(layer);

double x = -9188151.36056;
double y = 3235144.74039;
var point = new MPoint(x, y);
mapControl.Map.Home = (n) => n.CenterOnAndZoomTo(point, resolution: 1000, 500, Mapsui.Animations.Easing.CubicOut);

MyMapControl = mapControl;
Content = mapControl;
```

It now starts like this:

![image](https://github.com/Mapsui/Mapsui/assets/963462/f8107890-da01-4118-b916-6bea8d451cac)

###Notes:
- I tested on Windows, not on Mac or iOS, but I assume the fix also works there.
- Perhaps we should add the to the FAQ.
- I expect the Mapsui logger to log a warning when CenterOnAndZoom is called too early. I did not see that warning.
- You do not always need to the canvas size, and in this particular case (where resolution and center are set). I think you don't need it. Perhaps we can improve this.

**Comment by pauldendulk** [comment] 2023-11-12 16:01
I looked into the last two bullets. 

We do not log a warning when the navigator is called while width and height is zero. I think we should add this. It looks like the Navigator.SetViewport method is a good place for this. 

Calling CenterOnAndZoom before width and height are set actually works, the viewport is correctly initialized. However, after that, the default Home method does a ZoomToPanBounds() and overrides the earlier CenterOnAndZoom. The initial CenterOnAndZoom  actually works if `mapControl.Map.Home = (n) => { };` is called before (did this just to test the logic). Anyway, this was just to understand what is happening. Lets leave this like it is. When we add the logger users will understand what is going on.

**Comment by nm4568** [comment] 2023-11-13 18:16
Thank you so much for the quick response on this.  This makes perfect sense.  Just a thought but perhaps the usage of the 'InvalidOperationException' in scenarios like this might be appropriate as well.

**Comment by pauldendulk** [comment] 2023-11-13 19:18
Thanks for the suggestion, that might be the best option. I will close this as answered.

**Closed by pauldendulk** 2023-11-13 19:18 UTC

**Comment by Rankors** [comment] 2024-03-12 18:37
`var mapControl = new Mapsui.UI.Maui.MapControl();
mapControl.Map.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());

mapFrame.Content = mapControl;
mapControl.Map.Home = (n) => { };
mapControl.Map.Home = (n) => n.CenterOnAndZoomTo(new MPoint(54, 59), n.Resolutions[10]);`
Could you tell me what the problem is? it shows the map, but does not center the point I need, Maui project, android platform, Mapsui.Maui package
thx

**Comment by pauldendulk** [comment] 2024-03-15 07:59
@Rankors You are using LatLon coordinates. Mapsui v4 has no automatic conversion from LatLon to the coordinate system used in openstreetmap (SpherialMercator). You have to convert with SphericalMercator.FromLonLat(), (note, first lon, then lat).

**Comment by Rankors** [comment] 2024-03-15 15:38
thanks  bro
