### ISSUE TITLE
MAUI Flyout Locks Map

### ISSUE THREAD

**Issue by nm4568** [Mapsui/Mapsui#2000] opened 2023-05-26 18:48 UTC
**Mapsui Version**
Mapsui.Maui@4.0.0-rc.1

**Mapsui Platform**
MAUI

**Device**
iOS

**Describe the bug**
Swiping to open the flyout menu will eventually fully lock the map.  

**To Reproduce**

1. When swiping from the left to open/close the flyout menu, the map will eventually become locked.  The first step in becoming locked will manifest in the map thinking that it already has a Touch Point so triggering a TouchMove event with 1 finger will act as if 2 fingers were being used.  
2. Continue to open/close the Flyout and the map will eventually become locked. 

**Expected behavior**
The map should function as normal when the Flyout is closed.

**Additional context**
I suspect what is happening is that the TouchStarted event is being fired but the TouchEnded event is not.

**Comment by pauldendulk** [comment] 2023-05-27 08:47
Thank you for the clear bug report. We should investigate this before the release.

**Comment by pauldendulk** [comment] 2023-06-05 14:41
I can reproduce it. It takes quite a few retries. Once it is locked I can unlock it again by dragging the locked map and letting go. Is this also what you see?

**Comment by pauldendulk** [comment] 2023-06-05 15:35
I investigated what happend and as turns out there is no OnTouch event coming in at all in the scenario at all. So, it looks like it is a bug in MAUI or SkiaSharp. Since trying again solves the problem (or do you see something else @nm4568?) I don't see it as a big issue.

I don't thing there is a workaround possible on our side, since we do not get an event at all.

**Comment by nm4568** [comment] 2023-06-06 21:37
I have no problem reproducing it on my end.  In fact, here is a video that shows the problem.

https://github.com/Mapsui/Mapsui/assets/3853981/c67a7d9d-6680-4e9d-bbfc-85a443b37dc4

Steps in Video 
1) Shows the map functioning normally (1 finger)
2) Flout menu is opened
3) Flout menu is closed
4) Shows the map zooming and tilting as if I am using more than 1 finger but in reality, only 1 finger is used.

As I mentioned before, if the Flyout Menu is opened and closed again, the entire map locks up and doesn't respond to a drag at all.  I didn't feel this would provide any value showing this in the video.

Also, here is a link to the repo that I created the video from.

https://github.com/nm4568/MapsuiMauiFlyoutLocksMap

Other details: 

Device - iPhone Pro Max 14 (physical device)
.NET Workloads - 

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.86/7.0.100         VS 17.6.33723.286
maui-maccatalyst           7.0.86/7.0.100         VS 17.6.33723.286
maccatalyst                16.4.7054/7.0.100      VS 17.6.33723.286
maui-ios                   7.0.86/7.0.100         VS 17.6.33723.286
ios                        16.4.7054/7.0.100      VS 17.6.33723.286
maui-android               7.0.86/7.0.100         VS 17.6.33723.286
android                    33.0.46/7.0.100        VS 17.6.33723.286

Let me know if you need any other information.

**Comment by charlenni** [comment] 2023-06-06 22:34
Where do you click to close the fly out? Is this in the area of the map? If yes, I would say, that MAUI doesn't mark the touch start as handled and so the system gives the touch to Mapsui, the next view. Mapsui then thinks, that there is already one finger on the screen and makes gestures for two fingers.

So I would start to search in the touch start handling of MAUI fly out.

**Comment by nm4568** [comment] 2023-06-06 22:53
Flyout is closed by swiping the Flyout to the left.  It doesn't matter where you swipe it to close it.

**Comment by nm4568** [comment] 2023-06-06 23:17
> So I would start to search in the touch start handling of MAUI fly out.

I think what may be happening is the touchstart is  firing as the flyout is opened and the touchend event is NOT firing at all.  This explains the behavior of what I’m seeing.

**Comment by pauldendulk** [comment] 2023-06-07 07:50
@nm4568 As mentioned above I can reproduce the locking, but it only locks on the first touchdown. On the second one it is panning again. This is not what you are seeing? In your case the map stays locked?

I could not reproduce the pinch behavior yet, but I will try your sample.

What I saw investigating the lock is that there was no OnTouch event coming in at all. So, that seems to be a bug in SkiaSharp or MAUI.

**Comment by pauldendulk** [comment] 2023-06-07 07:57
> there was no OnTouch event coming in at all

To clarify. All the Mapsui Touch events (Start, End, Move, Exit) come from the MAUI OnTouch event. So, we can not do anything if no event comes in.

**Comment by nm4568** [comment] 2023-06-07 16:17
@pauldendulk it is very easily reproducible with the sample provided.  I was able to confirm through some logging that the MapControl.TouchStarted event is fired as the Flyout is opened but the MapControl.TouchEnded event is not.

**Comment by janusw** [comment] 2023-06-07 19:36
It might be worth checking if `UseFling = false` makes any difference here (it does for #2017, which might be related).

**Comment by charlenni** [comment] 2023-06-07 20:12
I would say, that this is the problem. Mapsui gets a TouchStart, but no TouchEnd. With this, Mapsui belives, that the finger is still on display. When the fly out is closed, the next touch is for Mapsui the second finger on display. With this, you zoom in and out.

**Comment by nm4568** [comment] 2023-06-07 21:36
> It might be worth checking if `UseFling = false` makes any difference here (it does for #2017, which might be related).

I set `UseFling = false` and it didn't make a bit of difference.

**Comment by charlenni** [comment] 2023-06-07 21:44
Sorry for the stupid question, but I didn't worked with a fly out before. How do you activate it? In your video, I didn't see, where your finger touch the screen. Do you activate it by the hamburger menu in the left upper corner? Or by a swipe from outside? Perhaps we could check, if the finger was already on the screen when the touchStart begin.

**Comment by nm4568** [comment] 2023-06-07 21:46
> Sorry for the stupid question, but I didn't worked with a fly out before. How do you activate it? In your video, I didn't see, where your finger touch the screen. Do you activate it by the hamburger menu in the left upper corner? Or by a swipe from outside? Perhaps we could check, if the finger was already on the screen when the touchStart begin.

I activated the Flyout by swiping right from the left hand edge of the device.

**Comment by charlenni** [comment] 2023-06-07 22:11
I think, that is the problem. When the finger is entering the SkiaSharp view, Mapsui gets a touch event (finger down). When you lift the finger, Maui get the information, that this is a swipe and handle the TouchEnd (finger up). So SkiaSharp didn't see a TouchEnd event, that could be handled.

Could you check what happens, if you do the same with a normal view (image, edit or so). Do you get the TouchStart there too? And do you get a TouchEnd?

**Comment by charlenni** [comment] 2023-06-07 22:12
Problem is, that Maui could not recall the TouchStart, which shouldn't had send to the view. If I'm right, then Android has the possibility.

**Comment by janusw** [comment] 2023-06-09 07:48
> I set `UseFling = false` and it didn't make a bit of difference.

Alright, then it seems this issue is different from #2017, after all (probably a MAUI framework bug?). Thanks for checking.

**Comment by pauldendulk** [comment] 2023-06-09 14:52
The reported problem is on iOS. Unfortunately I can not test on iOS and I can not reproduce the problem on Android.

- I looked at the logic of the skiasharp OnTouch. The OnTouch event is about individual fingers. There is a Pressed and Release event which both apply to individual fingers. So, if you touch with two fingers and release one finger the Release event is fired. We have to keep track of the touches. The logic to add and remove touch events seems to be correct.  My guess is still that the problem is related to MAUI/SkiaSharp, but I could not reproduce it myself so I can not be sure.
- @nm4568 mentions that
  > the touchstart is firing as the flyout is opened and the touchend event is NOT firing at all.'touchstart is firing as the flyout is 
What I see on Android is that a Pressed event is not followed by a Released event, but instead i see a Cancelled event, and on Cancelled the _touches are cleared. Perhaps the Cancelled event is missing on iOS.

I tested with a workaround where I implemented the parents View TouchEnded, but it was not called at all when the fly out was opened. 
```csharp
        this.TouchEnded += MapControl_TouchEnded;
    }

    private void MapControl_TouchEnded(object? sender, TouchedEventArgs e)
    {
        _touches.Clear();
    }
```

So, at the moment I don't have a workaround. There are other events like Exited and Entered which perhaps could be used for a workaround, but on Android they are not called at all.

@nm4568 Does the problem you describe persist? Is the only way to fix it to close and reopen te application?

**Comment by nm4568** [comment] 2023-06-09 14:57
@pauldendulk yes, the problem persists and the only way to fix it is to close and reopen the application.

**Comment by pauldendulk** [comment] 2023-06-09 15:44
Perhaps someone with a Mac can investigate this (CC @inforithmics , @janusw). 

Possible workaround. Add a small margin between the map and the side where the flyout is opened.

**Comment by pauldendulk** [comment] 2023-06-10 06:35
### Summary of what I know
Mapsui uses the SkiaSharp OnTouch event. In this event we get Pressed and Released events about individual fingers. We need to keep track of this to know which fingers are pressed in the _touches field. If one event is missing there is no way to correct for this. It is not possible to request the current touch state. 

There is a Cancelled event which is called when the flyout is opened on Android. In that event we reset the _touches. It looks like this is missing in iOS. Perhaps on iOS instead of Cancelled the Exited event is called. If so, we can easily fix this by called _touches.Clean() on Existed.

This should be investigate by putting a breakpoint in the OnTouch and opening the flyout on iOS to see which events come in.

@inforithmics Is this something that you could look at?

**Comment by inforithmics** [comment] 2023-06-10 14:05
I logged the Events that lead to an lock and discovered.  there are moved events without a release or other function causing the freeze of the map.

Pressed
Moved
Moved 
-- mising Released.
Pressed
Moved
...
Released

**Comment by charlenni** [comment] 2023-06-10 15:38
As I said: the first pressed is registered for a possible swipe event and additionally forwarded to Mapsui. Then all the moves are registered. Then Maui detects, when the released comes, that the press and moves belong to swipe. So it opens the fly out and doesn't forward the release event to Mapsui. Mapsui thinks still, that the finger is on the display. When the next press event comes, there is already a finger registered.

Perhaps Maui sends an "lost focus" event in this case and if this happens, all touches should be cleared.

**Comment by inforithmics** [comment] 2023-06-10 17:33
https://github.com/Mapsui/Mapsui/issues/2000

**Comment by pauldendulk** [comment] 2023-06-16 05:04
Judging from the code below UseGPU is true on iOS and thus SKGLView is used. It would be interesting to know if the SKCanvasView has the same behavoir.

https://github.com/Mapsui/Mapsui/blob/9be56129e417eb6bd69db8f1c2303a23322ee4f6/Mapsui.UI.Forms/MapControl.cs#L68-L78

**Comment by pauldendulk** [comment] 2023-06-16 05:17
I submitted a bug at SkiaSharp https://github.com/mono/SkiaSharp/issues/2493

**Comment by charlenni** [comment] 2023-06-16 05:17
@pauldendulk For the answer see [here](https://github.com/Mapsui/Mapsui/issues/2000#issuecomment-1581543480)

SkiaSharp uses the OnTouch event of the normal Maui views, so I wouldn‘t expect any difference.

**Comment by pauldendulk** [comment] 2023-06-16 05:48
> SkiaSharp uses the OnTouch event of the normal Maui views, so I wouldn‘t expect any difference.

So perhaps it should be submitted as a MAUI bug?

**Comment by charlenni** [comment] 2023-06-16 08:59
I assume, that Maui couldn‘t change something on this problem.

What I found is, that Maui has more possibilities than Forms. See [this](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/tap) for the description of GestureRecognizers for Maui. Perhaps we could remove the SkiaSharp touch handling at all from MapControl and use this instead?

**Comment by pauldendulk** [comment] 2023-06-16 10:52
What if we let the users use the GestureRecognizers and add extension methods on the event args to fetch the MapInfo for that screen coordinate? The users can use the classes they know from that platform and we do not have to deal with it in our code (less chance to break something).

**Comment by pauldendulk** [comment] 2023-06-17 18:33
This was fixed with a workaround in Mapsui:
https://github.com/Mapsui/Mapsui/pull/2053

**Closed by pauldendulk** 2023-06-17 18:33 UTC
Labels: bug-in-dependency
