### ISSUE TITLE
PresentationSource is null when using mapsui in WPF usercontrol with Skia

### ISSUE THREAD

**Issue by manepeg** [Mapsui/Mapsui#916] opened 2020-05-12 12:07 UTC
Hi everyone

I'm using mapsui in a WPF project. I normally display the map in a WPF window with the Skia renderer and of course it works just fine. Today i needed to add the map control inside a Syncfusion docking manager as a child so i created a WPF usercontrol to contain the map... but i got and error:

> System.Exception
  HResult=0x80131500
  Messaggio=PresentationSource is null
  Origine=Mapsui.UI.Wpf
  Analisi dello stack:
   in Mapsui.UI.Wpf.MapControl.DetermineSkiaScale()
   in Mapsui.UI.Wpf.MapControl.DetermineScale()
   in Mapsui.UI.Wpf.MapControl.MapControlLoaded(Object sender, RoutedEventArgs e)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   in System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   in System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   in System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   in System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   in MS.Internal.LoadedOrUnloadedOperation.DoWork()
   in System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   in System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   in System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   in System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   in System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   in System.Windows.Interop.HwndTarget.OnResize()
   in System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   in System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

I switched to the WPF render mode and it works.

I found a post on stackoverflow also suggesting switching to the WPF render mode: https://stackoverflow.com/questions/53883180/mapsui-error-how-to-fix-presentationsource-is-null

I'm using nuget v1.4.8.0

Any idea how to solve this?
Thanks

**Comment by pauldendulk** [comment] 2020-05-12 18:16
@manepeg Thanks for reporting this but this is not something I will find time for to dig into. It is using 1.4.8 which is one and half years old and we just released 2.0.0. My advice would be to try to use 2.0.0. Perhaps the problem is fixed. If it not I am not sure if it easy to reproduce for us.

**Comment by manepeg** [comment] 2020-05-13 07:12
You were right, i upgraded to 2.0.0 (geez, a lot of new dependencies) and now it works. I guess fixing it in the old version has no sense.

Thank you for your feedback Paul, have a nice day

**Comment by charlenni** [comment] 2020-05-13 07:14
If it is solved, could you please close this issue?

**Closed** 2020-05-13 07:16 UTC
Labels: possible bug, v1
