### ISSUE TITLE
Map not responding to mouse gestures after resizing control - WPF

### ISSUE THREAD

**Issue by TAlecksen** [Mapsui/Mapsui#2803] opened 2024-11-18 16:34 UTC
**Mapsui Version**
Mapsui.Wpf 4.1.8

**Mapsui Platform**
WPF

**Device**
Windows

**Describe the bug**
The mouse down and dragging does not seem to be recognized on the map after a resize of the window is performed.

**To Reproduce**
1. Load the map with some basemap (OpenStreetMap)
2. Resize the window, or maximize the window.
3. Try clicking and dragging the map starting at the bottom of the map screen. The map will not respond to mouse gestures anywhere in the space added after the window resize.

**Expected behavior**
The map should respond to the mouse in all areas after a resize.

**Additional context**
This problem appears to be worse when dealing with dpi scaling.

**Comment by pauldendulk** [comment] 2024-11-18 21:10
Thanks for the report. I could not reproduce it with the WPF sample in the develop/4.1. Can you? If not there must be something specific about your setup. Do you have any idea what that could be?

**Comment by TAlecksen** [comment] 2024-11-18 22:07
Thank you for the quick reply. You are correct, I tried it in a fresh project and it worked fine. It turned out to be a hidden grid row that was preventing it from receiving the mouse events. Sorry for the hassle.

Somewhat related - I would like to switch to the beta version 5 to make sure I am working with the most recent version, but I noticed the WPF version does not appear to handle mouse panning correctly. Is this a known issue? I could not find it in the current list of bugs. Thanks!

**Comment by pauldendulk** [comment] 2024-11-19 08:30
I test regularly with Mapsui.Samples.Wpf and have noticed nothing like that. Under what circumstances do you run into this?

**Comment by TAlecksen** [comment] 2024-11-19 16:07
I made a fresh project and added the WPF version 5.0.0 beta.4 in Visual Studio 2022 and added it as outlined in the quick guide:

![image](https://github.com/user-attachments/assets/b7cb130f-bceb-4bac-8d8f-f4aa7019c9e2)

![image](https://github.com/user-attachments/assets/24ae290b-0b54-40c8-845f-6e0933116040)

When I run the sample, it seems as though it is not recognizing the mouse move events since the map only appears to update at the end of the mouse movement. Zooming with the mouse wheel appears to work fine. I tried to capture this in the video below.

https://github.com/user-attachments/assets/f7490bdb-dd7f-45f2-a760-3fcfc9dfabb5

**Comment by pauldendulk** [comment] 2024-11-20 08:54
I can not reproduce that on the main branch. I hope to have time for this Friday.

**Comment by TAlecksen** [comment] 2024-11-20 16:19
Please let me know if I can provide anything to assist. It seems to be specific to version 5 because when I downgrade to 4.1.8 in the same project it works fine. Thank you

**Comment by pauldendulk** [comment] 2024-11-22 08:54
I could reproduce it easily with the getting started as you describe. Since it is not on main it could be a problem with the pre-release of SkiaSharp. So before I investigate this further I will release a new beta and try it again.

**Comment by TAlecksen** [comment] 2024-11-22 23:55
Thanks for everything Paul, please feel free to delete this Issue Report since the error was obviously my own.

**Comment by pauldendulk** [comment] 2024-11-25 19:02
It is not fixed in 5.0.0-beta.5. I do don't know cause yet. I created a new issue https://github.com/Mapsui/Mapsui/issues/2810. 

I will close this one.

**Closed by pauldendulk** 2024-11-25 19:02 UTC
