### ISSUE TITLE
[Xamarin.Forms WPF] Question: Map is placed over every element?

### ISSUE THREAD

**Issue by TheProme** [Mapsui/Mapsui#775] opened 2020-01-16 08:23 UTC
Having an issue with map placement. Seems like it places as topmost element. Even Alert is placed below.
![maps](https://user-images.githubusercontent.com/22505666/72506240-31a73b00-384a-11ea-99bf-720477a30ccb.png)

**Comment by pauldendulk** [comment] 2020-01-16 09:14
Wat are you using? Xamarin.Form WPF?

**Comment by TheProme** [comment] 2020-01-16 09:15
@pauldendulk Yes, I'm using Xamarin.Forms WPF

**Comment by charlenni** [comment] 2020-01-16 09:15
I assume, that he is using Forms, because he mention MapView.

**Comment by charlenni** [comment] 2020-01-16 09:17
I’m not sure, if this is a Mapsui or a Xamarin.Firms.Wpf problem.

**Comment by pauldendulk** [comment] 2020-01-17 21:49
When I put a button on top of the map it is visible in XF UWP.

![image](https://user-images.githubusercontent.com/963462/72648486-741c6500-397b-11ea-9724-2b7de03cf24c.png)

But it is not in XF WPF. The code is all the same. Don't see how this could be Mapsui.

**Comment by pauldendulk** [comment] 2020-01-17 21:50
Button was added like this:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:mapsui="clr-namespace:Mapsui.UI.Forms;assembly=Mapsui.UI.Forms"
             x:Class="Mapsui.Samples.Forms.MainPageLarge">
    <ContentPage.Content>
        <StackLayout Orientation="Horizontal">
            <StackLayout Orientation="Vertical">
                <Picker x:Name="picker" />
                <ListView x:Name="listView"
                    VerticalOptions="FillAndExpand" 
                    HorizontalOptions="Start"
                    WidthRequest="200"
                    Margin="10"
                    ItemSelected="OnSelection"/>
            </StackLayout>
            <Grid    		    VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand">
            <mapsui:MapView x:Name="mapView"
    		    VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand"
		        BackgroundColor="Gray" 
		        Margin="0" />
                <Button WidthRequest="160" HeightRequest="160" HorizontalOptions="Center" VerticalOptions="Center" Text="Hello"></Button>
            </Grid>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

**Comment by pauldendulk** [comment] 2020-01-17 22:18
I posted an issue at skiasharp
https://github.com/mono/SkiaSharp/issues/1108

**Comment by radderz** [comment] 2020-01-19 18:48
@pauldendulk have you tried specifying both as Grid.Row = 0?

From your sample XAML I'd expect the button to be below the skia view rather than over it as they don't share the same location in the grid. I think the grid starts vertically stacking when the child position isn't specified.

**Comment by pauldendulk** [comment] 2020-01-19 20:33
Thanks, I am not an expert in xaml, I can use some help, I will check that. I assumed it had to be on top because the same xaml shows the button in uwp, but perhaps there is undefined behavior of you don't set the Grid.Row.

**Comment by pauldendulk** [comment] 2020-01-19 21:38
I added the Grid.Row = 0 as in the xaml below. This is what you mean? I has the same behavior.

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:buttondoesnotshow="clr-namespace:ButtonDoesNotShow"
             mc:Ignorable="d"
             x:Class="ButtonDoesNotShow.MainPage">
    <ContentPage.Content>
        <Grid
            VerticalOptions="FillAndExpand"
            HorizontalOptions="FillAndExpand">
            <buttondoesnotshow:MyCustomView 
                Grid.Row="0"
                x:Name="mapView"
    		VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand"
		BackgroundColor="Gray" 
		Margin="0" />
            <Button
                Grid.Row="0"
                WidthRequest="160" 
                HeightRequest="160" 
                HorizontalOptions="Center" 
                VerticalOptions="Center" 
                Text="Hello">
            </Button>
        </Grid>
    </ContentPage.Content>
</ContentPage>
```

Here is a minimal reproducible example.
https://github.com/pauldendulk/ButtonDoesNotShow

**Comment by radderz** [comment] 2020-01-19 21:51
Yes that is what I had meant, doing the above works for me when I do the same thing in Android/iOS/UWP, I haven't tried WPF, it could be a problem with the Skia library or Xamarin itself. 

I Don't think there are many users of Xamarin in WPF to be fair.

I'll have a quick tinker with your repro.

**Comment by radderz** [comment] 2020-01-19 21:57
@pauldendulk definitely seems and issue with the skia view in WPF

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:buttondoesnotshow="clr-namespace:ButtonDoesNotShow"
             mc:Ignorable="d"
             x:Class="ButtonDoesNotShow.MainPage">
    <ContentPage.Content>
        <Grid
            VerticalOptions="FillAndExpand"
            HorizontalOptions="FillAndExpand">
            <!--<buttondoesnotshow:MyCustomView 
                Grid.Row="0"
                x:Name="mapView"
    		    VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand"
		        BackgroundColor="Gray" 
		        Margin="0" />-->
            <Grid 
                Grid.Row="0"
    		    VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand"
		        BackgroundColor="Gray" 
		        Margin="0" />
            <Button
                Grid.Row="0"
                WidthRequest="160" 
                HeightRequest="160" 
                HorizontalOptions="Center" 
                VerticalOptions="Center" 
                Text="Hello">
            </Button>
        </Grid>
    </ContentPage.Content>
</ContentPage>
```

Changing to the above shows the button, so the skia one should also do the same.

**Comment by TheProme** [comment] 2020-01-19 22:06
I faced similar problem when I was using WinForms controls inside WPF application. (https://social.msdn.microsoft.com/Forums/vstudio/en-US/52c077ed-4f9a-4d38-9326-f6875255fe79/hosting-a-winforms-control-inside-a-wpf-window-problem?forum=wpf)
Maybe this can help you somehow.
There are some workarounds but they are pretty bad. Maybe the problem is inside Skia renderer?

**Comment by sailman342** [comment] 2020-01-20 13:30
> Yes that is what I had meant, doing the above works for me when I do the same thing in Android/iOS/UWP, I haven't tried WPF, it could be a problem with the Skia library or Xamarin itself.
> I Don't think there are many users of Xamarin in WPF to be fair.
> I'll have a quick tinker with your repro.

We are some waiting on you :-) :D 

For the time being it is the only alternative to be compatible with non 10 versions of Windows :-)

**Comment by pauldendulk** [comment] 2020-01-20 20:24
> I Don't think there are many users of Xamarin in WPF to be fair.

Yes, it does not seem very mature. I worked with it for the first time. Creating the sample took a lot more time than I expected because there is no template. You have to edit an ordinary WPF template. I followed the tutorial here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/wpf

**Comment by sailman342** [comment] 2020-04-14 05:42
You can have a look here [#892 ](https://github.com/Mapsui/Mapsui/issues/892)

Very likely due to a bad handling of the GPU in SkiaSharp ...

**Comment by pauldendulk** [comment] 2020-04-17 10:43
Here is an update about this issue: https://github.com/mono/SkiaSharp/issues/1108#issuecomment-614730682

**Comment by pauldendulk** [comment] 2020-05-05 08:26
Status: This will not be fixed in the near future. This means to WPF Forms MapView is not a viable option for most applications. There will be a fix at some point. Subscribe to the issue mentioned above to stay up to date.

**Comment by sailman342** [comment] 2020-05-05 15:07
If you change the type of MapControl to SKCanvasView instead of using SKGL... it works like a charm on WPF too, it also solves the blank screen problem on old iMacs.

I had only a couple of lines to change in the module. see #892  

The problem is you use Conditional compilation in this module ...

I departed from Mapsui due to the WPF problems, besides that, you did a really great job ! Congratulations :-)

**Comment by charlenni** [comment] 2020-05-05 16:19
If you leave, where did you go?

**Comment by sailman342** [comment] 2020-05-07 21:51
I am investigating writing my own ... I don't need all that complexity ... but I would like to cover all platforms, same if I have to design with workarounds solutions ! 

My mind is not set up yet :-) But thanks you all :-)

**Comment by pauldendulk** [comment] 2020-05-12 06:34
I would think Xamarin WPF is not in high demand so do not want to invest in it. It seems an easy fix to use the SKCanvasView instead but it is not so easy. It needs a separate build. If MapView was not derived from SKGLView but had it as a member like the MapControls there could be a runtime switch. That might be a solution. Still I think there are higher priority issues so let's just wait for the fix in SkiaSharp.

@sailman342  Good luck with your project. Perhaps it is possible to use part of Mapsui. You could start with a copy of the MapView or MapControl, simplify this to your own purpose and still make use of the Mapsui nuget for core functionality.

**Closed by pauldendulk** 2020-05-12 06:34 UTC
Labels: bug-in-dependency

**Comment by sailman342** [comment] 2020-05-12 08:25
You are right, I did a separate build and I understand the complexity of changing at runtime. The SKGLView also has problems with some old iMacs. My target users are not equiped with the latest generations of computers, therefore ...

Thank you for the proposal of using Mapsui parts but Mapsui uses tons of third parties libraries so for the time being I decided to solely stick to Xamarin Forms and SkiaSharp Forms.

The usage of SkiaSharp touch as detector of pin click is also a problem, I laready mentioned the problem of the transparent hole in the standard pin resulting in map click rather than pin click. I am using very small pins and with my big fingers I most of the time get map clicks instead of pin clicks :-)

But mapsui is a very good engineered product, it outperforms in my mind most of the "native" solutions, thanks to the community, I will keep you posted. Kindest

**Comment by charlenni** [comment] 2020-05-12 08:53
Regarding the touch: we decided to check for clicks by really drawn pixels. So, if you want to check the hole, give this hole a color with a low opacity.

Regarding the third party libraries: which one ist to much. Perhaps we could make Mapsui much leaner.

**Comment by pauldendulk** [comment] 2020-05-12 18:58
Perhaps the Mapsui core project should be in a separate nuget without further dependencies. This was in line what I was thinking wrt the v3 roadmap. A Mapsui.Layers could have a TileLayer (depending on BruTile), VectorLayer (depending on NTS) and more like these.

About the touch. It should be optional to increase the touch area by some margin. I think the parameter is already there, just not implemented.
