### ISSUE TITLE
Mapsui 2.0 - Raster mbtiles appear blurred at higher zoom levels

### ISSUE THREAD

**Issue by jin-khera-eastpoint** [Mapsui/Mapsui#551] opened 2018-12-03 16:23 UTC
This relates to the latest 2.0 of the sdk(beta 8). The map is created using MBTilesSource and it works fine. One thing we noticed is that the tiles appear quite blurred. I have attached images of the same area at different zoom levels. Is this something you will be looking at?

![screenshot_2018-12-03-16-13-05](https://user-images.githubusercontent.com/40358958/49386534-aaffcf00-f717-11e8-9516-bb22e4a320fc.png)
![screenshot_2018-12-03-16-12-44](https://user-images.githubusercontent.com/40358958/49386535-aaffcf00-f717-11e8-9d9a-a464692942ac.png)
![screenshot_2018-12-03-16-12-59](https://user-images.githubusercontent.com/40358958/49386536-aaffcf00-f717-11e8-9d68-ab41676bdda2.png)

**Comment by charlenni** [comment] 2018-12-03 16:48
Do you use the correct resolution/zoom levels for your tile source? If not, than the bitmaps have to be scaled and than they get blurred.

**Comment by jinkhera** [comment] 2018-12-03 16:54
I can get the current resolution but then how would I convert that to a zoom level specified in the tile source sqlite?

**Comment by charlenni** [comment] 2018-12-03 18:22
Your ````TileLayer```` contains a property ````Resolutions````, which contains an array with all valid resolutions for this layer. If you select one of this resolutions, the map shouldn't get blurred.

**Comment by charlenni** [comment] 2018-12-08 19:18
Did this solve your problem?

**Comment by jinkhera** [comment] 2018-12-11 07:30
@charlenni can you close this issue. I will create a new one regarding panning.

**Comment by charlenni** [comment] 2018-12-11 10:03
@jinkhera No, only the owner of the issue or a maintainer (@pauldendulk) could do this.

**Comment by pauldendulk** [comment] 2018-12-11 10:51
So the conclusion of this issue is that the resolutions in the mbtiles were not correct? ... and the new issue is unrelated?

**Comment by jinkhera** [comment] 2018-12-11 10:54
The new issue is unrelated.

This issue I'm not sure about as the same tiles work fine on iOS using MapBox. It's when you are zooming in and out slightly that you get the blurred isssue

**Comment by jinkhera** [comment] 2018-12-11 19:21
@pauldendulk I'm also using BruTile 1.0

`var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(path, true));
 var mbTilesLayer = new TileLayer(mbTilesTileSource);`

**Comment by pauldendulk** [comment] 2018-12-14 11:33
There seems to be a serious bug with the refresh. If I zoom in with mouse the layer is not redrawn for the current resolution. If I pan a little bit this is resolved. Do you see this too?

**Comment by pauldendulk** [comment] 2018-12-14 16:21
I published 2.0.0-beta.11. Could you test it?

**Comment by jinkhera** [comment] 2018-12-14 16:38
Hi @pauldendulk . This is great! We are currently using beta-9, will there be many breaking changes by going to beta-11? I will try this tonight.

**Comment by jinkhera** [comment] 2018-12-14 22:35
I just realised the change made was for WPF, I am using Android but I'm assuming the same change could be tried here too?

**Comment by pauldendulk** [comment] 2018-12-27 12:56
Closing as I can not reproduce this with the data/info I have right now. There could be a real problem.

**Comment by johnpudd** [comment] 2018-12-31 08:43
Hi @pauldendulk

It seems possible this is to do with the bitmap quality setting in the skiarenderer (set to low), but may also be something else (source material, or zoom level defined in SQLite or Brutile tile selection).

@jinkhera reported different outcomes between different versions, so I’m tempted to think the quality setting maybe at play. I need to verify this with him next week (I have a local version set to Medium quality).

I noticed a todo note about passing in some configuration to allow definition of this property (and pressumably other properties elsewhere too). Is that something we could help with? If so, do you already have an approach in mind?

Cheers

John

**Comment by pauldendulk** [comment] 2018-12-31 13:35
Additional question. If you use the +/- buttons you end up going to the 'proper' resolutions for the tile layers. There tiles should look good there. If you start pinch zooming you end up between those proper resolutions and the renderer has to decide which tile to show, either a sized down high resolution tile or a blown-up low resolution tile (let's call it interpolation). 

The question: if you use the +/- buttons do you see a difference between 1.4.8 and 2.0? If not then the issue may be with the interpolation strategy.

**Comment by jin-khera-eastpoint** [comment] 2019-01-10 08:21
Hello @pauldendulk. @johnpudd has done some more investigations and has found a  a likely candidate for the blurring of tiles, this change could be behind the other issue I mentioned #523. 

The details are as follows, you can see the change on this commit -> https://github.com/EastpointSoftware/Mapsui/commit/689a08984dde00012456e757cff58b958eb38fcb

After making the change the tiles appear sharper but the impact is that performance is not as good, this was apparent in 1.4.8.

**Comment by johnpudd** [comment] 2019-01-10 08:54
To clarify - we’re not suggesting this as the solution... but using it to demonstrate we’re the issue is occurring for us.

E.g. on a tablet, tiles fill one quarter of the screen natively, and are then stretched to nearly double their intended size (rather than selecting a tile designed for that resolution).

As @jin mentioned, this change does impact performance of slower android devices, due, I presume, to rendering more tiles.

**Comment by pauldendulk** [comment] 2019-01-16 06:05
oh, the scale issue gave me lot of headaches. I still have an open issue at skiasharp which I should test with the new version:
https://github.com/mono/SkiaSharp/issues/527

What I would like is to have all positioning in [device-independent-units](https://mapsui.github.io/Mapsui/documentation/skia-scale.html).

It seems that on your device you do receive the coordinates in device-independent-units instead of pixels.

Did you upgrade the skiasharp version? Do you have the same issue with 1.60.0?

**Comment by pauldendulk** [comment] 2019-01-18 09:12
@jin-khera-eastpoint and @johnpudd I will have some time for this this morning but I don't have a clear picture what the story is. Perhaps you could start a new issue for the remaining problem. 

Is the problem on both phone and tablet?

**Comment by charlenni** [comment] 2019-01-23 20:57
FYI [Link](https://groups.google.com/forum/m/#!topic/skia-discuss/Hpjma8785HA)

**Comment by pauldendulk** [comment] 2020-03-28 15:02
I am closing this because I assume the underlying issue is the [IgnorePixelScaling](https://github.com/Mapsui/Mapsui/issues/580) issue.

**Closed by pauldendulk** 2020-03-28 15:02 UTC
Labels: can-not-reproduce
