### ISSUE TITLE
RasterizingLayer and IsMapInfoLayer doesn't play nicely

### ISSUE THREAD

**Issue by frkfromnowhere** [Mapsui/Mapsui#499] opened 2018-08-20 06:12 UTC
Is there some reason why using IsMapInfoLayer = true for RasterizingLayer (not directly, of course, but via MemoryLayer, for example) doesn't work? For example, wrap all layers in [this sample](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/InfoLayersSample.cs) in RasterizingLayer  and the clicking isn't working (because MapInfoEventArgs.MapInfo.Feature is null).

I can't use other layer types because I have really heavy geometries.

**Comment by pauldendulk** [comment] 2018-08-21 19:45
This was never properly implemented for RasterizingLayer. 

## What is going on
If the point layer of the InfoLayerSample you pointed to is wrapped in a RasterizingLayer and you also set IsMapInfoLayer to true, like this:

```c#
    map.Layers.Add(new RasterizingLayer(CreateInfoLayer(map.Envelope)){IsMapInfoLayer = true});
```
.. then map info does return a feature, but the feature is a raster of the entire screen, so useless for this purpose. The problem is that the GetFeaturesInView method is used for two purposes, 1) to get the features that need to be rendered (which could be rasterized), and 2) query for the features. For the RasterizingLayer we would like to call the GetFeaturesInView method of the child layer. Perhaps there should be separate methods for features to render and for features to query. I am not sure what would be a good solution here so I want to think about this a bit more.. 

## Workaround
Perhaps a workaround for you is not to use the built in map info but create your own. You should intercept the touch event on the mapcontrol and in there you could call the static MapInfoHelper.GetMapInfo and pass the feature layer (the non-raster layers) as argument.

**Comment by pauldendulk** [comment] 2018-09-07 09:43
Closing. Still interested if you got a workaround to work.

**Closed by pauldendulk** 2018-09-07 09:43 UTC
Labels: design, enhancement, question

**Comment by frkfromnowhere** [comment] 2018-09-13 06:27
Yeah, I just added a new variable "layersForQuery" and then added needed layer both to map.Layers and _layersForQuery_. And used GetMapFeatures for _layersForQuery_. Maybe not the most efficient solution, but it works pretty nice :)

**Comment by pauldendulk** [comment] 2018-09-13 06:57
Thanks for the info.
