### ISSUE TITLE
Stretched images through IgnorePixelScaling and .ToDeviceIndependentUnits(PixelDensity) create blurring

### ISSUE THREAD

**Issue by johnpudd** [Mapsui/Mapsui#580] opened 2019-01-18 09:30 UTC
In follow up to #551. 

Testing on various Android tablets shows a consistent behaviour of stretching images and causing blurring. 

The following code change demonstrates this on our test devices. Tiles are not rendered on the entire screen (the right hand side, and bottom edge are often missed).

[Mapsui.UI.Android/MapControl.cs Line 47 ](https://github.com/Mapsui/Mapsui/blob/a2ac8de4537250235b96f9a1fb9d7307503e9d10/Mapsui.UI.Android/MapControl.cs#L47)
```
-             _canvas = new SKCanvasView(Context) { IgnorePixelScaling = true };
+             _canvas = new SKCanvasView(Context) { IgnorePixelScaling = false };
```

Eliminating the .ToDeviceIndependentUnits(PixelDensity) conversion ensures the whole view is rendered, however this is clearly not the intended direction. It also leads to other items being drawn in inconsistent positioned (e.g. the scale bar margin varies by device).

Also, IgnorePixelScaling is not available on the most recent versions of SkiaSharp, so presumably this issue is coming down the line soon enough.

I feel a viable solution maybe to apply a scaling factor to the Viewport where Renderer.Render is called... but I'm mainly just guessing there.

**Comment by pauldendulk** [comment] 2019-01-18 09:45
Thanks. Some questions

- On which version of SkiaSharp are you?
- So there is no problem with the phone version right now?
- Did you test this on one kind of tablet  or more?
- What is the brand/type of the tablet?

**Comment by johnpudd** [comment] 2019-01-18 09:58
Hi @pauldendulk,

We've tried on a number of tablets, I don't know whether the same occurs on phones (tablet is our main use case) - will test and let you know.

The version of SkaiSharp is 1.60.3

This has been tried on a number of tablets:
- two Samsung Tab tablets (I would to check the exact model);
- Huawei MediaPad M3 8 Lite Tablet
- Huawei MediaPad T3 10" Tablet

**Comment by pauldendulk** [comment] 2019-01-18 10:33
Do you see the same problem when you run Mapsui.Samples.Droid?

**Comment by johnpudd** [comment] 2019-01-18 11:31
I’ll need to check and report back (unfortunately I’m away from my desk today).

**Comment by pauldendulk** [comment] 2019-01-18 11:42
Is the behavior for 1.4.8 different than 2.0?

**Comment by johnpudd** [comment] 2019-01-18 11:53
I believe so, but will run some tests as soon as I can and confirm. 
I’ve been told the versions prior to 2.x.x exhibited sharper images (but slower performance - presumably partly as a result of drawing more tiles), however I haven’t tested this myself yet.

**Comment by pauldendulk** [comment] 2019-01-18 12:44
When I run Mapsui.Samples.Droid on my own tablet it looks as I expect it to look. I am not sure if what you seeing is a bug or by design. Tablets do have bigger device-independent-units so the images are supposed to be bigger and stretched out more than on the phone. On some tables this might now look that great, especially if they have a large screen.

**Comment by pauldendulk** [comment] 2019-01-19 08:39
btw, if the current behavior is by design it might still be an option to add a customer scale multiplier. Here is something about scale: https://mapsui.github.io/Mapsui/documentation/skia-scale.html

**Comment by johnpudd** [comment] 2019-01-20 11:09
Hi,
I've put some info together which explains what we're seeing. I hope this helps...

First of all, to help my debugging, I've added an boundaries and info about each tile in blue. 

The screenshots here are on a Huawei MediaPad M3 8 Lite Tablet, which has a screen resolution of 1920x1200. Based on 256x256 tiles, that would be roughly 7.5 x 4.5 tiles per view.

The first two screenshot shows zoom level 15, reasonably close to the switch to zoom level 16.

This shows the normal behaviour (code as per the repo):
![image](https://user-images.githubusercontent.com/6009552/51438272-273b7b00-1ca2-11e9-8404-f7aab6c32a9a.png)

This next image shows how much the image has been stretched to achieve the above (demo'd by setting IgnorePixelScaling = false).
![image](https://user-images.githubusercontent.com/6009552/51438274-33273d00-1ca2-11e9-9ed3-2dead8c850f3.png)

And this screenshots show the screen again at zoom level 15's min zoom (i.e. just before it moves to zoom level 14 - again with IgnorePixelScaling = false).
![image](https://user-images.githubusercontent.com/6009552/51438281-463a0d00-1ca2-11e9-948b-1bf112bc59df.png)

Renderer.Render is providing a viewport of 853 x 461 (based on a pixel density of 2.25). This suggests that images are being stretched by a factor of 2.25 in order to achieve a full resolution of 1919x1037. 

Indeed, Image 1 shows the full 1920 pixel device width being covered by 2.5 tiles (with a agregate width of 768px). So rather than showing crisp images at the screen's available resolution, we're stretching images, and causing blurring. 

The following image is the closest to utilising the full resolution of the device for zoom level 15. (5.5 tiles => 1,408px stretched to 1,920 pixels).
![image](https://user-images.githubusercontent.com/6009552/51438301-7aadc900-1ca2-11e9-90cf-f4b2cd1b4d47.png)

If my logic is valid then I think, at best, we're stretching images by 30% above there intended resolution. At worst, it's 2.25 times.

This potentially could be helped by a configuration preference. My personal preference is to show an image up to and including it's resolution (i.e. shrink but not stretch) as this keeps the images look good at all times. Other's might prefer the ability to zoom further, or to prefer performance (as my preference requires more tiles to be drawn to cover the same area).

But whichever your preference, I do feel it should be possible to see images at their native resolution at some point, which doesn't seem possible currently.

**Comment by pauldendulk** [comment] 2019-01-20 20:12
About the tile info. There is a static property Utilities.DeveloperTools.DeveloperMode which was meant for things like this. At the moment it is only used for drawing thick lines around tiles in the xaml renderer. 

If you could make drawing of this tile information depend on this DeveloperMode I would like to take it as a pull request.

**Comment by pauldendulk** [comment] 2019-01-20 20:18
About the issue. I would think sticking to device-independent-units makes the most sense as default mode. If you don't performance will also suffer. Performance becomes an important issue for many apps that grow more complex. 

Some option to customize the units would make sense. Perhaps the best option is to offer user a lambda which takes the size and default scale and returns the desired scale.

**Comment by pauldendulk** [comment] 2019-02-09 08:24
So what could done is open openstreetmap.org on the tablet and compare the tile stretching there with Mapsui's. 

If it is the same it is clear there is no bug. Then we can simply add the option to adjust the scale.

If there is a difference we can figure out what makes it different and perhaps apply that same logic to Mapsui.

**Comment by johnpudd** [comment] 2019-02-11 06:10
Hi @pauldendulk, 
I'll look into this further as soon as I have the chance. 
From a purely philosophical standpoint, I personally think device independent pixels is the wrong way to select the images to be show. This will always end up with scaled-up mdpi images no matter how good the screen is. 
Higher pixel density displays can deliver higher resolution images, but there's no point having a 4k screen (for example) if you're only going to supply it with standard definition content. 
But from a practical standpoint, the device's capability to render the images, especially while panning and zooming, also needs to be considered.
I really like the idea of supplying a lambda for customised implementations.

**Comment by pauldendulk** [comment] 2019-03-01 16:35
I compared the openstreetmap website with Mapsui. They use the same resolution. So, I think we do nothing weird. So, no bug. Still the request to set a different scale is valid. So I see this as a feature request. I am not sure when this will be added.

**Comment by hajmajeboss** [comment] 2020-02-24 09:10
Not sure if it's still relevant, but this issue has been resolved in most recent release. 
#676

**Comment by pauldendulk** [comment] 2020-02-24 18:23
ah, that means I never understood the problem. I will close it as a solved bug.

**Closed by pauldendulk** 2020-02-24 18:23 UTC
Labels: feature-request
