### ISSUE TITLE
Is it possible to render Polygons only with filled area only?

### ISSUE THREAD

**Issue by PChristoph** [Mapsui/Mapsui#401] opened 2018-05-02 11:55 UTC
Hello Paul,

Im adding several polygons adjacent to each other on a layer and want to have them filled with a solid color only - like when you draw a rectangle without a border.
So I added a VectorStyle to the Polygon features and setting the 'Fill' property, but noticing the outlines. From the mapsui code I noticed that 'Line' and 'Outline' will be initialized with black. Setting these attributes to null will get me an NullReferenceException while rendering. 
Defining the Style like this
`new VectorStyle() { Fill = color, Line = new Pen(new Color(0,0,0,0)), Outline = new Pen(new Color(0, 0, 0, 0)) };`
e.g. setting Alpha for the Lines to 0, doesn't render the polygons at all. I'm using Skia renderer.

What am I doing wrong?

Thank you and best regards
Christoph

**Comment by PChristoph** [comment] 2018-05-03 14:32
thank you both for your response! 

@charlenni I did not see any change when setting this.

@pauldendulk setting Line and Outline to null will produce an NullReferenceException like I said, in Mapsui.Rendering.Skia.dll. However this seems to be catched internaly, the program won't shut down.
wpf renderer behaves the same.

to elaborate more:

that line posted above works - but not the way I would need:
`new VectorStyle() { Fill = color, Line = new Pen(new Color(0,0,0,0)), Outline = new Pen(new Color(0, 0, 0, 0)) };`
where color is a Brush with FillStyle.Solid.

This does set the outline as transparent, so I have small spaces between each polygon. However I need a uniform colored area, formed of the adjacent polygons. It looks like this:
![alpha == 0 for outline and line](https://pasteboard.co/HjtAeTU.png)

as I said, setting Line and Outline to null doesn't work. What does work is setting these properties to the same Color, like this
`new VectorStyle() { Fill = color, Line = new Pen(color.Color), Outline = new Pen(color.Color) };`
where color is a Brush with FillStyle.Solid.

**But** there is a problem with opacity in this approach:

I learned Skia doesn't support opacity on layers, so I wrote this Extension method for setting the opacity on each individual feature on a layer:
        `
public static void SetOpacity(this IStyle style, double value)
        {
            var alpha = (int)Math.Round(255 * value, MidpointRounding.AwayFromZero);

            if (style is VectorStyle || style is SymbolStyle)
            {
                var actualStyle = style as VectorStyle;
                if (actualStyle.Fill != null && actualStyle.Fill.Background != null)
                {
                    actualStyle.Fill.Background.A = alpha;
                }
                if (actualStyle.Fill != null && actualStyle.Fill.Color != null)
                {
                    actualStyle.Fill.Color.A = alpha;
                }
                if (actualStyle.Line != null && actualStyle.Line.Color != null)
                {
                    actualStyle.Line.Color.A = alpha;
                }
                if (actualStyle.Outline != null && actualStyle.Outline.Color != null)
                {
                    actualStyle.Outline.Color.A = alpha;
                }

                if (style is SymbolStyle) //SymbolStyle is subclass of VectorStyle
                {
                    ((SymbolStyle)actualStyle).Opacity = value;
                }
            }
            else if (style is LabelStyle)
            {
              //...
            }
        }
`

this normaly does the trick, but somehow the Outline and the Fill Brushes look not equally transparent when using this function on the VectorStyle from above. It looks like that:

![Fill, Line and Outline with same Color, Alpha 255](https://pasteboard.co/HjtCny5.png)

![Fill, Line and Outline with same Color, reduced Alpha](https://pasteboard.co/HjtCLvN.png)

![Fill, Line and Outline with same Color, much more reduced Alpha](https://pasteboard.co/HjtDnmk.png)

**Comment by pauldendulk** [comment] 2018-05-03 14:44
The outlines are a separate draw step. Drawing two semi transparant color over each other will result in the last image you posted. Basically the very first image you posted should be correct. Not sure how the outlines are formed there? Is something drawn, or is there just a space between the geometries. If it is the latter it won't be easy to fix. 

btw, the skia implementation does support transparency on layers (perhaps implemented after your initial inquiry). Unfortunately it also uses transparency on individuals geometries internally because I don't see another option within skia. So it will have the same problem as the last image.

**Comment by pauldendulk** [comment] 2018-05-03 14:46
One more thing to test. What if you set the Pen width to 0?

**Comment by pauldendulk** [comment] 2018-05-03 19:57
Just pushed some adjustments to the code. This should be published soon as a nuget of latest build. See here: https://github.com/Mapsui/Mapsui/wiki/NuGet-of-latest-build

**Comment by PChristoph** [comment] 2018-05-04 09:13
"Not sure how the outlines are formed there? Is something drawn, or is there just a space between the geometries."
the lines are truly transparent - so I would guess these are spaces.

"What if you set the Pen width to 0?"
No difference.

"Just pushed some adjustments to the code."
Awesome, thank you! Now how would I have to set up my Style? With Line and Outline set to null?

At the moment nuget shows v1.4.0 from 25th april. The nuget source in the link you provided shows v.1.3.1 from 20th jan. So I can't test your changed at the moment. Not sure if I'm doing it right?

**Comment by pauldendulk** [comment] 2018-05-04 09:27
There should now be a 1.4.1-beta.1.buildnumber in the buildserver nuget repo.

**Comment by PChristoph** [comment] 2018-05-04 12:45
Thank you charlenni for the fix! I now was able to fetch v1.4.1.

However setting outline to null like this,
`new VectorStyle() { Fill = color, Line = null, Outline = null };
where color is a Brush with FillStyle.Solid.`

produces the following result
![outline 1 4 1](https://user-images.githubusercontent.com/18269443/39628385-3972fbd4-4fa9-11e8-8aac-1dc1b6d7bab0.jpg)
So there still seem to be problems.

But I'm still with version 1.1.1.0 of Mapsui.Desktop. Maybe this is not relevant, but how can I get a new version from nuget? (in github there are the sources, but I can't find a compiled version in nuget)

**Comment by charlenni** [comment] 2018-05-04 13:32
Do you think, it is possible to get a small demo application for testing?

**Comment by PChristoph** [comment] 2018-05-07 07:39
yes, I hope this helps!

[polygonTestProject.zip](https://github.com/Mapsui/Mapsui/files/1978919/polygonTestProject.zip)

**Comment by charlenni** [comment] 2018-05-07 20:13
You should add a `layer.Style = null;` to your function `AddTestPolygons()`. If you don't do this, the default layer style adds an outline to your polygons. If you do this, than you get very, very narrow lines between the polygons. I'm not sure, if we could remove this lines. Have to investigate a little bit more.

**Comment by pauldendulk** [comment] 2018-05-07 20:53
I have not looked into the details but I can image this is hard to solve. When you draw a polygon at a random position it is likely to cover part of a pixel. Anti aliasing will cause partial coloring of the pixel. When drawing tiles this has been a problem. I solved this with the RasterRenderer.RoundToPixel method. This seems to work for skia in all cases but for wpf the lines between tiles still show under some circumstances (it depends on my monitor).

**Comment by PChristoph** [comment] 2018-05-09 07:58
@pauldendulk glad I'm using skia :) thanks for the insights
@charlenni this solved the problem, even with the old mapsui version I'm using!

Thank you very much! It's very nice that one can count on quick help here!

**Comment by charlenni** [comment] 2018-05-09 08:19
Good to hear.

Do you have very, very small lines too?

**Comment by PChristoph** [comment] 2018-05-09 11:03
Hello again,

in my real life application the issues still occur. However I have no time at the moment to investigate further. The problem may still be existent.
I did use the latest nuget beta pakage, set the layer style to null and outline/line to null. But there still are these wide transparent lines.

@charlenni yes, very small lines - but when zooming in the small lines won't get wider (in the test project). I could live with that even though it is not ideal.

**Comment by charlenni** [comment] 2018-05-09 11:14
Wide transparent lines? Than perhaps the coordinates of your polygons aren‘t correct? Perhaps you added some space, which shouldn‘t be there now?

**Comment by pauldendulk** [comment] 2018-05-10 09:10
I think we really need a representative sample to be able to fix this. Good to keep it open though. 

Do the gaps get wider when you zoom in? If so the problem is probably in your data.

**Comment by pauldendulk** [comment] 2020-02-01 14:50
I will close this since we are not going to work on this soon. Also I assume it is not a critical feature for most users. Also, I am not sure if it can be fixed. It depends on the possibilities of skia.

**Closed by pauldendulk** 2020-02-01 14:50 UTC
Labels: question
