### ISSUE TITLE
Incorrect zoom behavior

### ISSUE THREAD

**Issue by sergei66666** [Mapsui/Mapsui#2409] opened 2024-01-10 12:26 UTC
**Mapsui Version**
4.1.2

**Mapsui Platform**
Only Wpf

**Device**
Windows 11

**Describe the bug**
The zoom result varies depending on animation time and resolution

**To Reproduce**
   In map.Home

```csharp
var box = new MRect(10340390, 7554750, 10340735, 7554670);

double resolution = ZoomHelper.CalculateResolutionForWorldSize(box.Width, box.Height,
    mapControl.Map.Navigator.Viewport.Width, mapControl.Map.Navigator.Viewport.Height, MBoxFit.Fit);
var p = box.Centroid;
long d = 300;//-1;
//resolution = 1;
mapControl.Map.Navigator.CenterOnAndZoomTo(p, resolution, d);
```

Step 1. Use animation duration 300
Step 2. Use resolution 0.22558593212161226 - zoom result over west cost of Africa or inside Africa, but box is point to Russia
Step 3. resolution 1 - zoom result is correct

Step 4. Use animation duration  -1
Step 5. Use resolution 0.22558593212161226 - zoom result is correct
Step 6. Use resolution resolution 1 - zoom result is correct

**Expected behavior**
I expected the same zoom result regardless of animation time and resolution

**Additional context**
All research was carried out only on my relatively simple project.

Perhaps I made some mistake. But it seems to me that there is a bug hidden somewhere :)

**Comment by pauldendulk** [comment] 2024-01-11 08:16
I can reproduce a similar problem by adding your code to the OsmSample. In my case it either zoomed to Africa or Russia depending on the way the map was opened (navigating from another category to Demo OsmSample) or by selecting it from within the demo sample. It did not depend on the animation. See code below.

For me this bug has no high priority since it is possible to work with no animation, and in main the Home mechanism is replaced with another method.

```
using Mapsui.Extensions;
using Mapsui.Tiling;
using Mapsui.Utilities;
using Mapsui.Widgets;
using Mapsui.Widgets.ScaleBar;
using Mapsui.Widgets.Zoom;
using System.Threading.Tasks;

namespace Mapsui.Samples.Common.Maps.Demo;

public class OsmSample : ISample
{
    public string Name => "1 OpenStreetMap";
    public string Category => "Demo";

    public Task<Map> CreateMapAsync()
    {
        return Task.FromResult(CreateMap());
    }

    public static Map CreateMap()
    {
        var map = new Map
        {
            CRS = "EPSG:3857"
        };
        map.Layers.Add(OpenStreetMap.CreateTileLayer());
        map.Widgets.Add(new ScaleBarWidget(map) { TextAlignment = Alignment.Center, HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Top });
        map.Widgets.Add(new ZoomInOutWidget { MarginX = 20, MarginY = 40 });

        map.Home = (n) =>
        {
            var box = new MRect(10340390, 7554750, 10340735, 7554670);

            double resolution = ZoomHelper.CalculateResolutionForWorldSize(box.Width, box.Height,
                map.Navigator.Viewport.Width, map.Navigator.Viewport.Height, MBoxFit.Fit);
            var p = box.Centroid;
            long d = 300;//-1;
                         //resolution = 1;
            map.Navigator.CenterOnAndZoomTo(p, resolution, d);
        };

        return map;
    }
}
```

**Comment by pauldendulk** [comment] 2024-01-12 15:12
BTW. It is simpler to use Navigator.ZoomToBox which uses ZoomHelper.CalculateResolutionForWorldSize internally.

```csharp
var box = new MRect(10340390, 7554750, 10340735, 7554670);
map.Navigator.ZoomToBox(box, d, MBoxFit.Fit);
```

but I don't think this will solve the problem.

**Comment by pauldendulk** [comment] 2024-01-12 15:13
Closing this as wontfix, sorry 🙄

**Closed** 2024-01-12 15:13 UTC
Labels: wontfix
