### ISSUE TITLE
Difference in Polyline Rendering on Mapsui and KML Viewer

### ISSUE THREAD

**Issue by BrianVance** [Mapsui/Mapsui#1212] opened 2021-09-14 18:50 UTC
Hi, 
   I have noticed a difference in the rendering of a polyline on Mapsui and on a KML viewer(using the polylines returned from the Mapsui library).  The angles don't align properly. The polylines rendered on the KML view is correct since I corroborated it with other KML viewers. I used version 2.0.3 of Mapsui.Forms

KML viewer used - http://kmlviewer.nsspot.net/

**Snapshot taken from Mapsui -**
![vvg_map](https://user-images.githubusercontent.com/10665687/133315502-34cad44d-d7b7-4230-a16c-5e18b96ff54f.png)

**Snapshot taken from the KML Viewer -**
![image](https://user-images.githubusercontent.com/10665687/133315801-cd70da5c-e340-4ec7-9a81-fbd033063533.png)

This is the contents of the kml file -

`<?xml version="1.0" encoding="utf-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Folder>
    <Placemark>
      <name>Start Point</name>
      <Point>
        <coordinates>-73.613861083984375,45.540431976318359</coordinates>
      </Point>
    </Placemark>
    <Placemark>
      <name>Final Path</name>
      <description>Final Path</description>
      <LineString>
        <extrude>true</extrude>
        <tessellate>true</tessellate>
        <altitudeMode>absolute</altitudeMode>
        <coordinates>-73.613861083984375,45.540431976318352,0
-73.613826212056935,45.540420586979728,0
-73.613799110292646,45.540461294483322,0
-73.613775862327316,45.540453701592085,0
-73.613786703028424,45.54043741858883,0
-73.613763455072956,45.540429825697579,0
-73.613752614370156,45.540446108699811,0</coordinates>
      </LineString>
    </Placemark>
  </Folder>
</kml>
`

**Comment by pauldendulk** [comment] 2021-09-15 15:33
Congratulations, you are now the record holder 'finding the oldest bug in the Mapsui'. It stems from the initial commit 'adding the trunk of the svn repository' from 24-1-2012. That is 3522  days. This is the initial import so it is even older.

The problem is that in SphericalMercator we round to float which is not necessary because Point is type double (and was double at the time of the initial import).

**Comment by pauldendulk** [comment] 2021-09-15 15:49
I created a PR which will probably be in the next release.

In the meantime you could make a copy of SphericalMercator.cs and remove the rounding (see PR) and make a copy of MinimalTransformation.cs and rename that and assign that to Map.Transformation (see the projection sample).

Apparently no-one even investigated this level op detail so there could be even more rounding errors.

**Comment by BrianVance** [comment] 2021-09-20 16:06
Hi Paul, 
    As as work around I made a copy of the SphericalMercator class and fixed the rounding issue and it worked when I create 'LineStrings' and add it to the layers of the Map. I did not try the MinimalTransformation yet. Can you suggest a time frame as to when we might get this fix as part of the release.

Thanks for suggesting a workaround. :)

**Comment by pauldendulk** [comment] 2021-09-20 16:49
The fix will be in the next RC release which I expect in a week, or maybe two.

I see that there is also direct use of SphericalMercator in Positioncs:

```csharp
public Mapsui.Geometries.Point ToMapsui()
{
    return Mapsui.Projection.SphericalMercator.FromLonLat(Longitude, Latitude);
}
```
So the MinimalTransformation fix will have no effect here. So perhaps wait for the release.

**Comment by janusw** [comment] 2021-09-20 19:25
> So perhaps wait for the release.

Note: You don't necessarily have to wait for a release. The fix has been merged to master and we have CI builds that generate nupkgs for every revision. You could just use the nuget packages of the current master branch (via a local packages source in VS): https://ci.appveyor.com/project/pauldendulk/mapsui/builds/40834197/artifacts

HTH.

**Comment by pauldendulk** [comment] 2021-09-24 13:46
The fix has now been released as part of rc.3. I will close this issue.

**Closed by pauldendulk** 2021-09-24 13:46 UTC
Labels: bug 🐛

**Comment by BrianVance** [comment] 2021-09-27 16:35
> The fix has now been released as part of rc.3. I will close this issue.

We tested the rc.3 version and the lines are rendering as expected. Thanks a lot Paul for this hotfix!!!
