### ISSUE TITLE
WmsLayer

### ISSUE THREAD

**Issue by Kortdag** [Mapsui/Mapsui#395] opened 2018-04-23 08:25 UTC
This is half contribution /
[Demo.zip](https://github.com/Mapsui/Mapsui/files/1937200/Demo.zip)
 half bug.

I´ve been fighting the ImageLayer for days. In our case the WMS source is not very fast. When moving the map it locks up. There is a FetchDelay but there is no way to fint a sweetspot between performance and removing the locking behavior. Its reproduced in the attaced sample. 

To reproduce (I´m om iOS):
1) Leave the FetchDelay as the default 1 sek. 
2) Make zoom / pan operations. Leave the map for 1 sek, do it agin. In a few operations the map locks up. The WMS source is VERY slow for demo purposes.

Now the the custom WMS layer in the sample. It does no lock up.
Its rewritten to be taskbased (task/await).

Im sure there is a way to fix the excisting layer using the excisting infrastructure. I just think a asynchronous approach is better. Use the sample if you want. 

The reasoning behind.
The GetFeaturesInView view API are all synchronous i.e. return IEnumerable and not Task.
This leads to you having to implement all backend fetching using Task.Run to get it off the UI thread. This does not work well for ImageLayer - but could of course....
If its slow it does not work at all like shown in the sample. The map locks up. I assume thats why there is implemented a FetchDelay to try to work against this? Anyway I have made a Task based implementation that does not do that even in the case of a very slow backend. This has the benefit of not locking the UI on quick map movements if the backend is slow and not punishing the user with a delay if one doing a single map operation.

A few thoughts on synchronous vs async.

Fetching tiles and / or WMS maps are going to end up in a HttpClient ind the end - the one the users implement. Its an almost 100% IO bound operation with very little CPU stuff going on. Basicly just making a feature from bytes.
Task/Await does not block the UI so I think its perfect for a task like this and much simpler than multithreadding stuff.

A HttpClient has a limit on the concurrent connections allowed to the same host - default is two I believe. In a synchrounous API there is no way you can tell the HttpClient to cancel an ongoing task. Of course the backend server would still finish the work, but who cares :-). In the case of your tile layer there are 4 workes internally but if using the same HttpClient it wil not allow more than two at a time unless you increase that limit. So the user must keep stuff in sync or it will seem like its not working. 
Of course a async tilelayer is a bit more complicated since there needs to be some bookkeeping on whih uncompleted tasks (tiles) can be cancelled since they are not needed. Which shoul be left to complete and which can be left to complete. But on the other hand async does not need to to specify both number of threads and number of concurrent connections in the HttpClient.

I attached an async WmsLayer that you can compare the the sync counterpart if you like. The only VERY tricky issue was related to the use of at feature bounding box apparently beeing parsed around the api and some threadding stuff not updating it, so I had to clone it or the feature would not update on pan before new fetch. Of course a async tilelayer is a bit more complex since there have to be some bookkeeping of pending work that is not needed (and can be cancelled) if moving the map quicly.

I think the benefit for you woould be much less stuff to maintain. Just let the user worry about how much is goind on at the same time and starting an cancelling tasks from the API.

In (Core 2.0 atleast) one can set the http concurrent limit like so
ServicePointManager.DefaultConnectionLimit = 20;

There is a lot of stuff to get for free in the async world like retry on error. If your interested se my favorite article and related stuff.
https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern

**Comment by Kortdag** [comment] 2018-04-24 06:29
Atleast on iOS physical device the sample attached reproduces the issue. 
The map does not lock up indefinitely but it seems that its locked until some work is has been completed. 
I watched a user just panning like crazy when it locked up and then it seemed like some of the operations were kept so you saw the map trailing previous user actions - lagging. 

In the sample I allowed the default FeatchDelay (which is not in my real life app since using the latest release build). To reproduce you of course then needs to make a map zoom / pan, then wait 1+ sek, make another,..... Then in a few operations the UI locks. The WMS is VERY slow since this is the best way to demonstrate the issue.

Im not sure about other components since I fixed the issue in my real life app. The demo does not have much else. But I think other parts of the app was alive - but not sure.

**Comment by pauldendulk** [comment] 2018-04-28 11:16
I could reproduce this bug in the wmslockup branch:
https://github.com/Mapsui/Mapsui/tree/wmslockup

This is all I can do for today. I did not look into the cause. A very old (known) issue is that the boundingbox fetchting is not async. This could be the cause here.

**Comment by pauldendulk** [comment] 2018-05-06 13:31
In my latest commit I have things working like I had in mind. Envelope is calculated on a background thread and an envelope property changed is sent when it changes. 

I did not dig in into the async/await solution. In general I am not a big fan of async/await because it infects everything else calling it. If a library can library can solve the async problem for the user and present it with a sync interface I think this is a better option, but I am open for alternative suggestions.

**Comment by pauldendulk** [comment] 2018-05-06 13:32
A automatic build nuget should be published soon. https://github.com/Mapsui/Mapsui/wiki/NuGet-of-latest-build

**Comment by pauldendulk** [comment] 2018-05-10 18:51
Locking should now be fixed in 1.4.1. Closing this. 

Please open an other issue to discuss asynchronous design. A short note. Not everything right now is how I want it to be. In general I would like an approach where few locks are necessary. In most cases data is fetched on a background thread. While it is fetched it is not exposed to anything, once it is fetched the renderer and info requests should be able to access it from the main thread.

**Closed** 2018-05-10 18:51 UTC
Labels: bug

**Comment by Kortdag** [comment] 2018-05-13 15:40
Sorry for the late reply.
Sounds great - it looked like a fix in the wms lockup branch sp looking forward to trying out 1.4.1
