### ISSUE TITLE
How can we create a complete cross-plateform solution for xamarin.form?

### ISSUE THREAD

**Issue by RidaNoor** [Mapsui/Mapsui#696] opened 2019-09-09 18:51 UTC
Hi, I need one urgent and quick fix , please?
I have been using Mapsui in Xamarin.Android project and it has been working great. 
Now, its required that I need to create a complete cross platform solution where all the code should be only inside the shared project. 
I have some issues and troubles. 
1. When I install Mapsui.Forms inside the Xamarin.Forms Core project, I am unable to use this namespace inside the xaml page 
xmlns:mapsui="clr-namespace:Mapsui.UI.Forms;assembly=Mapsui.UI.Forms"
And thus not able to use 
<mapsui:MapView x:Name="mapView"
    		    VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand"
		        BackgroundColor="Gray" 
		        Margin="0" /> 
What's the issue?

2. I need some good example/sample code please for xamariin.forms project where I can render the map in XamlPage from ViewModel of the CoreProject. 

Any quick help will be much helpful .

Regards

**Comment by charlenni** [comment] 2019-09-09 22:43
Did you looked into the [samples](https://github.com/Mapsui/Mapsui/tree/master/Samples/Mapsui.Samples.Forms)?

**Comment by RidaNoor** [comment] 2019-09-10 04:26
Thankyou so much for the reply @charlenni !

And yes I did. but look at this sample for Shared project:

https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared/MainPageLarge.xaml

Its not clear which method does what. Or how to call/render map in ContentPage from ViewModel.
Also as I have put in the description that the namespace for mapsui used in the xaml page is not supported when I install the Mapsui.Forms nuget package.

**Comment by charlenni** [comment] 2019-09-10 07:13
Each MapView is a MapControl and has a Map property, which is the normal common Map object, all Mapsui MapControl implementations have. For samples, how to use Map see [here](https://github.com/Mapsui/Mapsui/tree/master/Samples/Mapsui.Samples.Common). An example for adding a layer with an OSM map see [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/OsmSample.cs).

Regarding the namespace: I don't see, where the problem is. Up to now, you are the first, who had this problem. Did you add the NuGet package to the common part and the device dependent part?

**Comment by RidaNoor** [comment] 2019-09-10 08:37
When I install Mapsui.Forms nuget package then inside the Xaml page, I
cannot use Mapsui.UI.Forms namespace. Please see the image below.
On the right side you can see that I have installed both the Mapsui.Forms
and Mapsui Nuget package and installing one of it either doesn't help. and
on the left side you can see the errors:

[image: image.png]

**Comment by charlenni** [comment] 2019-09-10 08:57
Sorry, but I don't see the image.

**Comment by RidaNoor** [comment] 2019-09-10 08:59
<img width="948" alt="Untitled" src="https://user-images.githubusercontent.com/34579371/64599613-21321000-d3d3-11e9-9c4b-9d3088924b8d.png">

**Comment by charlenni** [comment] 2019-09-10 09:25
Ah, you use Mapsui 1.4.8 and the old Mapsui.Forms 0.2.1, but code for the new Mapsui.Forms implementation. If you want to use Mapsui.Forms 0.2.1, than you have to use

````
xmlns:mapsui="clr-namespace:Mapsui.Forms;assembly=Mapsui.Forms"
````

as you could see in the [samples](https://github.com/charlenni/Mapsui.Forms/tree/master/Samples) for 0.2.1.

But don't forget: 0.2.1 isn't supported any longer.

**Comment by RidaNoor** [comment] 2019-09-10 09:32
Hmmm okay one last thing please?
Why don't I see the version 2.0 to download?
In my nuget packages, it shows that latest stable verion is 0.2.1

**Comment by charlenni** [comment] 2019-09-10 09:48
Did you add the checkbox "Include prerelease" in your NuGet manager?

**Comment by RidaNoor** [comment] 2019-09-10 09:52
I have downloaded the Version 2.0.0 beta 25 using Package Manager. 
One very last thing, please?
In samples, in xaml page it is something like this:

  <mapsui:MapView x:Name="mapView"
    		    VerticalOptions="FillAndExpand" 
                HorizontalOptions="FillAndExpand"
		        BackgroundColor="Gray" 
		        Margin="0" Map="{Binding VM_Map}"/>

or inside the View.cs file , it is binding to VM Map, but when I use this Map in xaml or .cs class it says no bindable property or method found for Map

**Comment by RidaNoor** [comment] 2019-09-10 09:53
Should I use something other than MapView? I dont see anything else used. 
Basically I need to bind this map with ViewModel map

**Comment by RidaNoor** [comment] 2019-09-10 10:05
And also after I have added Version 2.0.0 of Mapsui it is causing this error that :

Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `SkiaSharp.Extended.Svg`, referenced by `Mapsui.UI.Forms`. Please add a NuGet package or assembly reference for `SkiaSharp.Extended.Svg`, or remove the reference to `Mapsui.UI.Forms`.	Tunnll.Passenger.Droid

**Comment by RidaNoor** [comment] 2019-09-10 10:14
Ah, Its working, finally!
But why don't I see any map in it?
<img width="246" alt="Untitled" src="https://user-images.githubusercontent.com/34579371/64605503-b0442580-d3dd-11e9-967a-f6c3c4d254b4.png">

**Comment by charlenni** [comment] 2019-09-10 10:41
Did you add a map? See for this the OSM sample I mentioned earlier.

**Comment by charlenni** [comment] 2019-09-10 10:45
I assume, that Map isn’t a bind able property. So you have to assign it in the xaml.cs.

**Comment by RidaNoor** [comment] 2019-09-10 12:18
One error remain, please help me with it. Please!
When I run its working fine but after the initialize method of the ViewModel is finished it returns the error that :
**System.MissingMethodException:** 'Default constructor not found for type Mapsui.Forms.Android.MapViewRenderer'

Although everything works I mean it is adding layers and everything but at the end it throws this exception and I cannot even catch it

**Comment by charlenni** [comment] 2019-09-10 12:21
Mapsui.Forms.Android.MapViewRenderer is a part of the 0.2.1 version.

Did you deleted all all parts? Cleared before build?

**Comment by RidaNoor** [comment] 2019-09-10 13:17
Now I get this Charlenni :(
 System.MissingMethodException: Method not found: void Mapsui.Providers.MemoryProvider..ctor(Mapsui.Providers.IFeatures)

**Comment by charlenni** [comment] 2019-09-10 13:43
Go into your project folder and delete all "obj" and "bin" folders you find. In subfolders too. Than compile the project again.

If this doesn't work, provide a sample project to test it.

**Comment by RidaNoor** [comment] 2019-09-10 14:14
@charlenni  you are my most favourite support engineer.! I wish I could give 100/100 rating for you, somewhere?
Okay I am trying it

**Comment by RidaNoor** [comment] 2019-09-10 17:04
Unfortunately, it didn't help.
Here is the link to my public Git Repo. Please let me know if you find troubles in setting up this project. 
https://github.com/RidaNoor/Sample-Mapsui

Also, while debugging, debugging the line 109 of MapsViewModel. It is the where this error occurs. 
Many thanks in advance. You are wonderful!

**Comment by charlenni** [comment] 2019-09-10 18:27
First of all, Mapsui.Forms is an addon for Mapsui. So you have to install Mapsui too. And this Mapsui needs the same version than Mapsui.Forms.

Than you have to understand, which object holds which informations. The Map object holds informations regarding genaral map settings and layers. MapControl/MapView shows the map on the screen. If you want to see another part of the map, you should do this with the Navigator of the MapControl/MapView. This is done wrong in MapService.cs, line 44 and following. You have to call 
````
MapView.Navigator.NavigateTo();
````

MapViewModel.cs, line 147 should be changed to 
````
currentLayer.DataHasChanged();
````

If you change this, it should run. I could run it, set an circle with an running man, but see no OSM data. I assume, that the app hasn't net access allowed.

**Comment by RidaNoor** [comment] 2019-09-11 04:23
Can you please send me the  MapService.cs class after what you have changed?
MapView.Navigator.NavigateTo is not accepting any of the existing arguments of MapService class. 

And I really want to tell you how hard it was to code it. because of the lack of the documentation of Mapsui. But it was working on Native Xamarin Project. 

Anyway, I am waiting for a response from you on this. Like you did yesterday. You are a life save @charlenni ! My company and I have been your client since very long. 

And yes, one more thing, Internet is enable in Droid settings of the app. I don't know why is it not picking up the OSM then. Maybe because of the changes we have made, no?

**Comment by charlenni** [comment] 2019-09-11 06:00
How could I access MapView in MapService?

**Comment by RidaNoor** [comment] 2019-09-11 07:48
You can create a new instance of MapView in MapService something like:

public MapView MapView;

**Comment by RidaNoor** [comment] 2019-09-11 07:50
You can change the code in any file if you need. I just need to make it run and fetch the OSM data and show.

**Comment by charlenni** [comment] 2019-09-11 10:37
Changed the files in the zip file. Works for me.

[ChangedFiles.zip](https://github.com/Mapsui/Mapsui/files/3600300/ChangedFiles.zip)

**Comment by RidaNoor** [comment] 2019-09-11 16:42
Charlenni, are you sure this is picking the same data as I have mentioned in my coordinates?
Also, I only see this on screen
<img width="196" alt="Untitled" src="https://user-images.githubusercontent.com/34579371/64717083-0ba90d00-d4dd-11e9-8dc0-e05c4d706a70.png">

**Comment by charlenni** [comment] 2019-09-11 19:39
Are you pressed the + button?

**Comment by RidaNoor** [comment] 2019-09-12 04:14
No no, I didn’t.
Even Later after few seconds when I couldnt understand I tried to move
around and saw few addresses in the map but not like a map look

**Comment by RidaNoor** [comment] 2019-09-12 04:39
Are you sure you didn't change anything in any other file?

**Comment by charlenni** [comment] 2019-09-12 07:03
You have to install Mapsui additionally to Mapsui.Forms as I mentioned yesterday. Did you do this?

**Comment by RidaNoor** [comment] 2019-09-12 07:22
Yes, both in Core and Droid project I have installed Mapsui v2.0.0-beta.25
by Paul Den Dulk and Mapsui.Forms v2.0.0-beta.25 by Dirk Weltz.

**Comment by RidaNoor** [comment] 2019-09-12 07:39
Also, the pointer in the map doesn’t show the same latitude/longitude that
I want to use and its given in Passenger Factory inside the Factory folder
of app

**Comment by RidaNoor** [comment] 2019-09-16 07:53
@charlenni  did you get a chance to look into API KEY REQUIRED issue?

**Comment by charlenni** [comment] 2019-09-16 08:44
I thought, that is so easy, that I must not explain.

OSM data is free, but not the server, that hosts the data. So the most server, where you could download OSM tiles, are not free. To pay the correct amount of fee, you add an API key for each access via URL. If you don't do this, than you get an API key required message over the map tiles.

In this case I used an OpenCycleMap. You could find their terms and conditions [here](https://www.thunderforest.com/terms/).

**Comment by RidaNoor** [comment] 2019-09-16 14:55
@charlenni  you are the champion ! You owe me a lot!

One last question, please?
Can I put an icon/image at the end of the line in mapsui? something like below image where the bus icon is placed at the end of the line. Also, I need to make sure that bus is placed exactly at the end of the line and not at start or anywhere in between?[
<img width="338" alt="Untitled" src="https://user-images.githubusercontent.com/34579371/64968566-d5440700-d8bb-11e9-8b5f-7f35246e08de.png">
](url)

**Comment by charlenni** [comment] 2019-09-17 07:35
You have the position of the end, so set a symbol at this position. See the [samples](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/SymbolsSample.cs).

**Comment by RidaNoor** [comment] 2019-09-17 10:21
@charlenni  should I expect something from you on this?

**Comment by RidaNoor** [comment] 2019-09-17 10:51
@charlenni  documentation contains no comments or anything :(
Please tell me one thing?

In my code sample, I used to following code to draw the line:

Route = (List<WktPath>)parameter. //It means Route has WKT List for path
var originPoint = new Point { X = 106.7361752, Y = -6.3404558 };
StringLayer = Route.DrawLineFrom(originPoint);

Does the above line works in a way that it takes all the WKT points and draw a line on them? Then why are we passing originPoint to it? Does it mean that line starts from this originPoint and then draw the line on Wkt points?

Another thing is, when we have drawn a line and we have put another layer of current user;s position on it, then why in the .cs file of xaml page, we write this:
mapView.Navigator.NavigateTo(SphericalMercator.FromLonLat(106.736, -6.34159), Resolution);

Last thing, why it is calculating  a higher resolution? I think it should be lower. Is it a good practice if I hardcode this resolution?

**Comment by RidaNoor** [comment] 2019-09-17 10:55
@charlenni please explain the above things in a little details and easy words. I shall be grateful forever!

**Comment by charlenni** [comment] 2019-09-17 11:59
@RidaNoor The greate advantage of open source is, that you could look into the source code. At each stage, you could see, what the programmer did.

I made only a few parts of Mapsui, not the whole library. I learned, how it works, by reading the code and looking at the samples. Yes, there are not so many comments in the code. But it easy to understand, when you look at the samples.

Your code, by the way, uses MvvmCross, something, that I never saw before in code. And there are not comments too. So I have to jump in many different parts and try to understand, what you are doing.

You ask, if `Route.DrawLineFrom(originPoint)` will work and how. Route is a `List<WktPath>`, where WktPath is an object of your library. So, how should I know, what you are doing? I would say, look into file `Tunnll.Passenger.Core.Helpers.Layers` (one of your code files) and check, what's going on. If there aren't any comments, than ask the author (you).

`mapView.Navigator.NavigateTo(SphericalMercator.FromLonLat(106.736, -6.34159), Resolution);` changes the position of the center of the map part you see in MapView.

The Resolution is the reciprocal of the ZoomLevel, which you perhaps know from Google Maps. If the ZoomLevel gets bigger, the Resolution (lets say the meters per pixel) are getting smaller.

**Closed** 2019-09-20 14:18 UTC
Labels: question
