### ISSUE TITLE
MapInfo2 

### ISSUE THREAD

**Issue by Kortdag** [Mapsui/Mapsui#393] opened 2018-04-23 08:05 UTC
The InfoHelper GetMapInfo return only on MapInfo. If you have more than one layer with info the API only returns info for the last feature. It would be nice if you would get MapInfo for all layers hit.

so 
new MapInfoEventArgs
                {
                    **MapInfo = List<mapInfo>,**
                    NumTaps = numTaps,
                    Handled = false
                };
instead of 
new MapInfoEventArgs
                {
                    **MapInfo = mapInfo,**
                    NumTaps = numTaps,
                    Handled = false
                };

**Comment by charlenni** [comment] 2018-04-23 08:38
I'm sure, @pauldendulk will be happy to review a PR with this extension 😁

**Comment by pauldendulk** [comment] 2018-04-23 20:05
I did consciously choose this solution. It seemed to me that if you click on something you want it to show up. If you want to ignore it then why is it in the layer list. I had this request before however, so let's go for it. 

What is exactly is your scenario?

**Comment by Kortdag** [comment] 2018-04-23 20:26
We have different types of map types e.g. georeferenced images and notes - memory layer - along with ordinary WMS map overlay. When the user clicks on a note og image we show it. Sometimes these things are close sine the notes are often a recomandation to document by taking an image. These are point features. 
Furthermore there is a polygon feature and the notes and images are always inside this. They can register info on the polygon by using images and notes along with classification info. 

So feature info
1) Register info on a polygon 
2) Show image inside the polygon - point layer
3) Show note inside the polygon - point layer.

We have implemented the ability for the user to turn of "Feature Info" on individual layers. 
The users just find it annoying that the click on e.g. a note and gets the image or vice versa and then have to go an deselect info on notes to get the image and go back an enable it for use in another place. They would like the App to provide them with an easy option to show both or choose which one

**Comment by pauldendulk** [comment] 2018-04-24 05:08
Okay thanks for that explanation. So the issue is that there are several types of features in one layer. I will accept a PR with this change.

Sounds like you are developing a fancy application :)

**Comment by Kortdag** [comment] 2018-04-24 06:11
Ahhh I think we´re miunderstanding eachother here. Im toltally fine with the idea that you just fetch a single feature from a layer if there is more. Like FirstOrDefault. What Im looking for is instead of finding one feature "globally" like 

foreach (var layer in reversedLayer)
            {
                if (layer.Enabled == false) continue;
                if (layer.MinVisible > resolution) continue;
                if (layer.MaxVisible < resolution) continue;
var features = layer.GetFeaturesInView(layer.Envelope, resolution);

                var feature = features.LastOrDefault(f => 
                    IsTouchingTakingIntoAccountSymbolStyles(worldPosition, f, layer.Style, resolution, symbolCache, margin));
if (feature != null)
                {
                    return new MapInfo
                    {
                        Feature = feature,
                        Layer = layer,
                        WorldPosition = worldPosition,
                        ScreenPosition = screenPosition,
                        Resolution = resolution
                    };
                }

What Im looking for is a **per layer** notification.
So if you have info enabled on three layers (A, B and C) and clicking in the map finds 1 feature in layer A, 0 in layer B and 3 in layer C then one would get a feature response that includes

The one feature from Layer A
Ingonring Layers B - nothing found
Picking the first feature from Layer C.

Yes its a very nice project. Pretty advanced app. Only thing. Its iOS which is always painful :-)

**Comment by pauldendulk** [comment] 2018-04-24 19:03
Or could it be a names tuple?

**Comment by Kortdag** [comment] 2018-04-24 19:50
Good we got that misunderstanding off the table☺
Exactly something like your enumerable example. Container object / keyvaluepair / tuple or whatever typed pairing of feature and layer would be beneficial

**Comment by pauldendulk** [comment] 2018-04-26 06:35
For your use case do you really need both the first feature of the first layer and the first feature of the second layer or do you only need the first feature of the second layer?

**Comment by pauldendulk** [comment] 2018-04-26 06:37
I can imagine other use cases where you would want all features hit within a single layer. Perhaps we should just return them all. 

Performance could be an issue here. Especially when doing hovering. Maybe this should be optional. Perhaps we should pass an enum with:
- FirstFeatureFeatureLayer
- AllFeaturesFirstLayer
- FirstFeatureAllLayers
- AllFeatureAllLayers

**Comment by pauldendulk** [comment] 2018-04-26 06:38
Or two enum. But the list of arguments is already big.

**Comment by Kortdag** [comment] 2018-04-29 08:11
I would need first feature of each layer hit.
But It might make sense to make it optional like you suggest

**Comment by pauldendulk** [comment] 2020-02-15 21:26
Work on this is in progress and will be in v2. In the current design a list is returned that contains objects with feature, style and layer. So no grouping for layers but users have the info to do it themselves with a GroupBy.

**Closed by pauldendulk** 2020-02-15 21:26 UTC
Labels: feature-request
