### ISSUE TITLE
new Pin - bug with scale

### ISSUE THREAD

**Issue by PioChoBia** [Mapsui/Mapsui#1767] opened 2022-12-11 18:08 UTC
**Describe the bug**
I'm creating a project with a map using Mapsui. I noticed when I create a new Pin there is a bug with the scale.

**To Reproduce**
--------------------------------------------------------------------------
        void PinAdd1(double latitude, double longitude, 
            string label, string adress, 
            Color color, float scale, 
            bool showCallout)  
        {
            Pin pin0= new Pin();
            pin0.Position = new Mapsui.UI.Forms.Position(latitude, longitude);
            pin0.Label = label;            
            pin0.Address = adress;
            pin0.Color = color;
            
            pin0.Scale= scale;
            
            mapView.Pins.Add(pin0);
            if (showCallout) mapView.Pins[mapView.Pins.Count - 1].ShowCallout();
        }
----------------------------------------------------------

Error
System.NullReferenceException: 'Object reference not set to an instance of an object.'

When
--------------------------------------------------------
        void PinAdd1(double latitude, double longitude, 
            string label, string adress, 
            Color color, float scale, 
            bool showCallout)  
        {
            Pin pin0= new Pin();
            pin0.Position = new Mapsui.UI.Forms.Position(latitude, longitude);
            pin0.Label = label;           
            pin0.Address = adress;
            pin0.Color = color;
            
           // pin0.Scale= scale;
            
            mapView.Pins.Add(pin0);
            if (showCallout) mapView.Pins[mapView.Pins.Count - 1].ShowCallout();
        }
-----------------------
create Pin and is OK.

Windows 10, VisualStudio 2022, XamarinForms, I run on mobile Xiaomi Redmi Note 11s
greetings Piotr

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charlenni** [comment] 2022-12-11 18:24
Seems to be in Pin.cs, line 436. But I don't know why. Is it the same with MaxVisible?

**Comment by charlenni** [comment] 2022-12-11 18:44
Try to set the PinType before setting the scale

**Comment by charlenni** [comment] 2022-12-12 07:49
Ok, I tried to reproduce this, but could not. Even if I make the same in the Forms pin sample as you do, I couldn't get this error.

Could you provide a working sample, with which it is possible to reproduce this error?

**Comment by pauldendulk** [comment] 2023-02-21 08:37
Closing this as 'can not reproduce'. Please reopen if you want to help us track this down.

**Closed by pauldendulk** 2023-02-21 08:37 UTC
Labels: can-not-reproduce
