### ISSUE TITLE
The RotateTo method invalidates the subsequent mapView.Map.Home method

### ISSUE THREAD

**Issue by gpsaliola** [Mapsui/Mapsui#1888] opened 2023-03-15 11:19 UTC
After Navigator.RotateTo method, the MmapView.Map.Home has no effects.

**Steps to reproduce**
`mapView.Navigator.RotateTo(0);`
`mapView.Map.Home = n => n.CenterOn(position.ToMapsui());`
`mapView.MyLocationLayer.UpdateMyLocation(position, true);`

** Behavior**
The map remains centered in 0,0 coordinates.

**Expected behavior**
The map is positioned at the coordinates contained in the "position" variable.

**Smartphone:**
 - Device: Samsung A53
 - OS: Android 13

**Comment by pauldendulk** [comment] 2023-03-15 14:42
I can reproduce the problem with the current master with this code:

```csharp
using Mapsui.Extensions;
using Mapsui.Projections;
using Mapsui.Tiling;
using System.Threading.Tasks;

namespace Mapsui.Samples.Common.Maps.Demo;

public class OsmSample : ISample
{
    public string Name => "1 OpenStreetMap";
    public string Category => "Demo";

    public Task<Map> CreateMapAsync()
    {
        return Task.FromResult(CreateMap());
    }

    public static Map CreateMap()
    {
        var map = new Map();
        map.Layers.Add(OpenStreetMap.CreateTileLayer());

        var centerOfLondonOntario = new MPoint(-81.2497, 42.9837);
        var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(centerOfLondonOntario.X, centerOfLondonOntario.Y).ToMPoint();
        map.Navigator.RotateTo(90);
        map.Home = n => n.CenterOn(sphericalMercatorCoordinate);
   
        return map;
    }
}

```

**Comment by pauldendulk** [comment] 2023-03-15 15:10
### What happens:
- The call to `map.Navigator.RotateTo(90)` results in a call to `Map.Navigated`
- In `Map.Navigated` `Initialized = true;` is set
- If later `CallHomeIfNeeded()` is called the `Initialized` field is already true and it will not call home (it is not needed)

### Is this a bug?
The `Initialized = true;` was explicitly added. It is set nowhere else except after the first call to home. It was probably added intentionally to prevent the call to Home (which has a default set that zooms to the full extent of the map). But there also other solutions for this. For instance set `Home = null`, or do the Navigate call on the Home action. I think is clearer if Initialized is only set after Home is called (And Maybe `Initialized` should be renamed to 'HomeIsCalled' instead). So, let`s consider this a bug. 

### Future considerations.
So, this can be fixed by just removing the `Initialized = true` line from Navigated. Still the construction with the Home method is not very clear. The reason it exists is that during Map creating the full extent of the Map (or of a specific layer, or specific data you may want to zoom into) is usually not known. Also the ScreenWidth and ScreenHeight may not be known which makes is also needed for some navigation method. Still if you do not have that problem and just know the extent it is so much simpler if you could just set it on the map. Also I wonder if we need Navigated at all or would it be better to use ViewportChanged as alternative. It is similar and it is always triggered when there is a Viewport change.

**Comment by gpsaliola** [comment] 2023-03-15 15:14
I've used mapView.Navigator.NavigateTo and now works fine.
Thank you!

**Closed** 2023-03-15 23:03 UTC
Labels: bug 🐛
