### ISSUE TITLE
Mapsui.Forms: problems on Android with 4.0.0-beta.4/5

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1653] opened 2022-06-24 21:49 UTC
**Describe the bug**

In my MapView-based application, I'm seeing problems and instabilities on Android with 4.0.0-beta.4 and beta.5, while beta.3 works fine.

At first everything seems to work, but after a while the problems begin: Sometimes the Callouts are not being shown any more, or other parts of the map (Pins or Drawables) are not being rendered. Sometimes the map freezes completely and no further updates happen at all. This happens only on Android, iOS seems to be ok.

I had a look at the Mapsui log, and the only error I found was this:

```
Error: The CancellationTokenSource has been disposed. - System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at System.Threading.CancellationTokenSource.ThrowObjectDisposedException () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:538 
  at System.Threading.CancellationTokenSource.ThrowIfDisposed () [0x00008] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:533 
  at System.Threading.CancellationTokenSource.Cancel (System.Boolean throwOnFirstException) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:320 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:291 
  at Mapsui.Fetcher.FetchWorker.FetchAsync (System.Threading.CancellationTokenSource cancellationTokenSource) [0x00082] in <41f3bb80db3a454e9cc79a38d1817734>:0 
```

This must have started somewhere between beta.3 and beta.4.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - OS: Android 12

**Comment by pauldendulk** [comment] 2022-06-25 08:32
Thanks for the wonderfully clear report and testing on specific versions. The stacktrace is informative. Looking in the history this PR could have caused the problem:
https://github.com/Mapsui/Mapsui/pull/1576/files#diff-d19b105a0f35f331106f820f86db0fc27f40152ecbf12d69b9a34bdd8d35acca

Reverting is not a real option because we need tile fetching in wasm to work as well. 

This code was overly complicated in the first place. I had been planning to replace it with the use of [Channels](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channel?view=net-6.0). Perhaps I can do that before the next release.

**Comment by inforithmics** [comment] 2022-06-25 12:09
Maybe somewhere in mapsui there is a async void function without error handling meaning that an exception occurs which kills the thread. For finding this out some more error handling logging is needed. 

Some questions for further analyzing it.

How long does the Android version work until it crashes or freezes. 
Can it be reproduced in mapsui itself.
Does disabling GPU rendering help.

**Comment by pauldendulk** [comment] 2022-06-25 12:42
I think it would be better to put our energy on rewriting it using Channel. I will try to find some time for it coming week.

**Comment by inforithmics** [comment] 2022-06-25 22:09
I agree with you, I made a quick test on an Samsung Tablet, but it worked without problems.
So I guess I will create a pull request that logs more possible errors to investigate further.

**Comment by pauldendulk** [comment] 2022-06-26 07:02
Looking at the code I would think it was an existing bug that started to appear because the added async logic changed the order things were executed.

- In a first call to ```Start``` ```FetchAsync``` is started on thread1. 
- thread1 calls ```cancellationTokenSource.Cancel() ```
- Before thread1 does anything else there is a new call to Start on thread2
- At that point the if will be true because of the second part ```_fetchLoopCancellationTokenSource.IsCancellationRequested``` and then calls ```_fetchLoopCancellationTokenSource?.Dispose();```
- thread1 calls  ```while (cancellationTokenSource is { Token: { IsCancellationRequested: false } })``` while cancellationTokenSource is Disposed. 


```csharp
        public void Start()
        {
            if (_fetchLoopCancellationTokenSource == null || _fetchLoopCancellationTokenSource.IsCancellationRequested)
            {
                Interlocked.Increment(ref RestartCounter);
                _fetchLoopCancellationTokenSource?.Dispose();
                _fetchLoopCancellationTokenSource = new CancellationTokenSource();
                Task.Run(async () => await FetchAsync(_fetchLoopCancellationTokenSource));
            }
        }
```

```csharp
        private async Task FetchAsync(CancellationTokenSource? cancellationTokenSource)
        {
            try
            {
                while (cancellationTokenSource is { Token: { IsCancellationRequested: false } })
                {
                    if (_fetchDispatcher.TryTake(out var method))
                        await method();
                    else
                        cancellationTokenSource.Cancel();
                }
            }
            catch (ObjectDisposedException e)
            {
                Logger.Log(LogLevel.Error, e.Message, e);
            }
        }
```

**Comment by janusw** [comment] 2022-06-26 10:03
Thanks for all the comments so far!

> Some questions for further analyzing it.
> 
> How long does the Android version work until it crashes or freezes.

It depends. Until one sees the first rendering problems, it can take 10-20s or longer. But the first error in the log usuall comes very quick.

> Can it be reproduced in mapsui itself.

I tried with the sample app, but did not see any rendering problems so far. Haven't actually checked if one sees the error message in the logs.

> Does disabling GPU rendering help.

No, the error still occurs.

> Does it hang or crash only in the release version or in the debug version too.

Both!

> Does this behavior occur on other Android Phones too.

Yes (tried a Huawei MediaPad - same error there as well).

**Comment by pauldendulk** [comment] 2022-06-26 11:58
> This must have started somewhere between beta.3 and beta.4.

So we are looking for a change between:
- Release beta 3: 2022-03-21
- Release beta 4: 2022-05-29

**Comment by inforithmics** [comment] 2022-06-26 14:55
I had a look what changed between this dates I suspect this Checkin

https://github.com/Mapsui/Mapsui/commit/0eef51492beeb6bf8b716efdbee86cefb08959a4

Because according to this stackOverflow

https://stackoverflow.com/questions/24139084/semaphoreslim-waitasync-before-after-try-block

this can deadlock

```
await _providerLock.WaitAsync();
try
{
    var features = await _provider.GetFeaturesAsync(_fetchInfo);
    _dataArrived.Invoke(features, _timeOfRequest);
}
finally
{
    _providerLock.Release();
}
```

if not done properly when a thread abort exception occours.

**Comment by inforithmics** [comment] 2022-06-26 14:55
I'm thinking to ouse the proposed SemaphorSlimExtensions

**Comment by janusw** [comment] 2022-06-27 11:59
After some more investigation, it seems improbable that the error posted above (`System.ObjectDisposedException`) is the origin of the rendering issues I see. In fact I see the exception also with beta.3, but the rendering looks complete fine there and no map freezing occurs.

It's certainly still worth to fix the exception, but this seems to be a different bug. My rendering issues must be caused by something else, I assume. I'll try to narrow down the window in which it appeared a bit more ...

**Comment by pauldendulk** [comment] 2022-06-27 12:14
@janusw Yes, I agree, I did a careful analysis of the steps it goes trough but only afterwards I saw the catch of ```System.ObjectDisposedException``` so, I now think this can not cause a problem. Hence my update:

> UPDATE: This explains why the exception in the log occurs, but since ObjectDisposedException is caught it does not explain the problems observed.

**Comment by janusw** [comment] 2022-06-27 12:51
> I had a look what changed between this dates I suspect this Checkin
> 
> [0eef514](https://github.com/Mapsui/Mapsui/commit/0eef51492beeb6bf8b716efdbee86cefb08959a4)

I think I can rule this out as the origin of my Android rendering issues: I just built with Mapsui 4.0.0-build.3445 (corresponding to 709b3ccfd1e14d7ef667f5f857e4642f40394e18), and this seems to be ok.

So the problem must have been introduced between these commits:
* 709b3ccfd1e14d7ef667f5f857e4642f40394e18 (Apr 23)
* 137796e201e63ee4e54aced2371c806b29c32fbb (May 26)

**Comment by janusw** [comment] 2022-06-27 13:13
Mapsui 4.0.0-build.3463 / afb6533af7bec27180320bb20fc5f520c0e2439c (May 8) also seems to be ok.

**Comment by janusw** [comment] 2022-06-27 13:48
Mapsui 4.0.0-beta.3-379 / aa24f3081418b3393b6975ccd04518af7bb41d67 (May 25) appear to be bad.

**Comment by janusw** [comment] 2022-06-27 14:20
Mapsui 4.0.0-beta.3-356 / ebe4603b68e59ee49c8dfa615fe7e23d4ad07c25 is also bad.

**Comment by janusw** [comment] 2022-06-27 15:07
And Mapsui 4.0.0-beta.3-353 / 2046ba069903b245c5a3b9f81ddad47a39803a20 is also bad,
but Mapsui 4.0.0-beta.3-348 / 1e23592163a362b1e3f815a7ba741a7f28e27924 appears to be good.

So it looks like this particular problem was introduced by #1600.

**Comment by janusw** [comment] 2022-06-27 15:39
> So it looks like this particular problem was introduced by #1600.

... most probably by commit 326e30804a06811894d630ffcccfa8c2ba25e9e2. And since the problems occur without me using any 'own' MemoryLayers, the issue is probably due to the changes in MapView, where all 'internal' layers were converted from MemoryLayer to Layer: https://github.com/Mapsui/Mapsui/commit/326e30804a06811894d630ffcccfa8c2ba25e9e2#diff-0e6fef08bb062d3377a6b10f4793a5606809e0fd58aeeefacb7e0b7f4267cd8a

This is only a hypothesis for now, but I'll try to verify it soon. Also I have no idea how this change of layers could trigger such problematic behavior (as described in my original report above). In fact the rendering problems exactly concern the Pins, Drawables and Callouts in the MapView. The "background" map layer is always rendered correctly, just like the MyLocationLayer, which stays a MemoryLayer.

@pauldendulk How were the changes in MapView motivated? Do you have any idea how they could cause such strange misbehavior?

**Comment by janusw** [comment] 2022-06-27 16:00
> > So it looks like this particular problem was introduced by #1600.
> 
> ... most probably by commit [326e308](https://github.com/Mapsui/Mapsui/commit/326e30804a06811894d630ffcccfa8c2ba25e9e2).

I verified by now that this is indeed the commit that introduces the breakage.

**Comment by pauldendulk** [comment] 2022-06-27 18:22
@janusw Thanks for your excellent detective work!

**About converting the Layers in MapView to Layers**
The MemoryLayers in MapView required a bigger rewrite to convert to the new MemoryLayer and I was not sure what the consequences of that would be. Converting them to Layer should cause some delay in drawing but should not cause a malfunction. 

Another possible problem is the new MemoryLayer itself. Perhaps the Features field is accessed on different threads. Could that play a role? You use your own MemoryLayer, is that to replace the Layers in MapView or do you also replace the new MemoryLayer with your own MemoryLayer?

The motivation to change the MemoryLayer itself is because now all providers are async it not appropriate anymore to use a provider withing the sync method of the ILayer (which is called on the draw loop). Also it was until now up to the developer to make sure that a MemoryLayer used a MemoryProvider instead of a provider that does a remote call, this is often been a problem in the past.

**Comment by pauldendulk** [comment] 2022-06-28 05:17
> Converting them to Layer should cause some delay in drawing but should not cause a malfunction.

Perhaps it is a combination of using Layer iso MemoryLayer and the commit Thomas mentioned ([0eef514](https://github.com/Mapsui/Mapsui/commit/0eef51492beeb6bf8b716efdbee86cefb08959a4)). The Layer depends on that code in that commit precedes it.

I will have time to work on this issue Wednesday.

It still think it is important to try to rewrite all the fetching logic into using Channels. It is a queuing mechanism.
 A request to a provider is put on the queue. There are a fixed number of listeners who handle them. There should be less locks and less waiting.

**Comment by janusw** [comment] 2022-06-29 09:15
> **Could the new MemoryLayer cause a problem?** Another possible problem is the new MemoryLayer itself. Perhaps the Features field is accessed on different threads. Could that play a role?

I don't think this is the origin of the problems I see. The issues seem to be caused by moving away from MemoryLayer to Layer in the MapView. So if anything, the `Layer` class has a problem, not the `MemoryLayer`.


> You use your own MemoryLayer, is that to replace the Layers in MapView or do you also replace the new MemoryLayer with your own MemoryLayer?

I'm using a MemoryLayer in some situations, but not to replace anything in MapView, but rather to add another layer with special contents.

**Comment by pauldendulk** [comment] 2022-07-04 07:06
Status update. Last Wednesday I did spent some time on this. I think a rewrite of the fetching logic is necessary but a bigger change than I hoped. 

I mentioned Channel, this can be useful to replace the FetchWorker. Fetch requests can be put on the Channel and a number of listeners can be assigned to the channel. But this is just part of the problem. The most important improvement I had in mind is to have fetching centralized, so not every layer for themselves, because this can cause too many fetch requests in parallel. This can be fixed but I have to think about it a bit more. This week I will have no time for it.

I have so far not tried to reproduce the problem myself. @janusw Do you see the problem in the Mapsui samples as well? Or what kind of setup do I need to reproduce it?

**Comment by pauldendulk** [comment] 2022-07-04 07:07
btw, I have been developing with beta 5 with Maui on Windows and it seems to work fine.

**Comment by inforithmics** [comment] 2022-07-18 21:15
I had again a look at the code, and I have the feeling that the whole Fetcher architecture isn't totally thread safe. I think the callouts are constantly created and update a new fetchcycle and during a fetchcycle a new fetch is created maybe because a new callout is added. And this somehow stops the fetcher or causes a deadlock somewhere in mapsui. Because there are plenty of lock(object) locks and with async code together this can cause deadlocks.

So maybe to reproduce it a test has to be written that faster generates callouts than the fetch cycle can run, and the a deadlock or a crash will occour in mapsui. Because the fetches before the callouts where less frequent and because Android is always the slowest Xamarin platform there the problem manifests first.

**Comment by inforithmics** [comment] 2022-07-18 21:17
So rewriting this with channels as @pauldendulk suggested could solve the problem.

**Comment by inforithmics** [comment] 2022-07-18 21:53
This is the code that causes the problems. in GetFeaturesAsync

```
    lock (_syncRoot)
            {
                foreach (var item in Collection)
                {
```

1) this lock should be an asynclock so when it is waiting the thread is freed. (Deadlock potential when it is the UIThread.
2) foreach(var item in Collection)   Collection is an ObservableCollection which is not threadsafe. So here only the iteration is guarded with a lock and not the adding, The exception means while I'm iterating an item was added.

1) First thing replace the lock(_syncRoot) with AsnyLocks (Can be easily done).
2) There are several Possibilities here
    1) Make a ConcurrentObservableCollection (ThreadSafe Observable Collection):
    2) Make a ShadowCollection that is a ConcurrentCollection and copy the items from the Observable to the ShadowCollection 
        On every add or remove. (The events don't looks to be threadsafe).

**Comment by inforithmics** [comment] 2022-07-18 22:01
Maybe for the ConcurrentObservableCollection https://github.com/stewienj/SwordfishCollections can be used.

**Comment by charlenni** [comment] 2022-07-18 22:09
Perhaps lock while copying the Collection, remove the lock and then do the foreach?

**Comment by inforithmics** [comment] 2022-07-18 22:20
An implementation with a Shadow Collection (No locks needed except in the Shadow collection itself)

https://github.com/Mapsui/Mapsui/pull/1673

**Comment by inforithmics** [comment] 2022-08-01 10:01
I'm Improving the RasterizingTiling Sample Provider (So that it works with labels) and I discovered a concurrency bug in the LabelStyleRenderer

https://github.com/Mapsui/Mapsui/pull/1683

**Closed** 2022-11-06 09:15 UTC
Labels: bug 🐛
