### ISSUE TITLE
[Xamarin Forms] App crash on PinClicked

### ISSUE THREAD

**Issue by ptufail** [Mapsui/Mapsui#654] opened 2019-04-23 12:53 UTC
Hi, 

We have a project that show services near the user's location. As we have many services we load services by moving the map deleting the old ones and adding the new ones.

When you move the map ( especially when zooming out ) and fast click on a pin the app crash and we have this exception 

04-23 13:01:38.503 E/mono    ( 6488): System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
04-23 13:01:38.503 E/mono    ( 6488):   at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.503 E/mono    ( 6488):   at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.503 E/mono    ( 6488):   at Mapsui.UI.Forms.MapView.HandlerTap (System.Object sender, Mapsui.UI.TappedEventArgs e) [0x0004a] in <50211ea8af5c495cb451c6bd76da743e>:0 
04-23 13:01:38.503 E/mono    ( 6488):   at Mapsui.UI.Forms.MapControl.OnSingleTapped (Mapsui.Geometries.Point screenPosition) [0x00012] in <50211ea8af5c495cb451c6bd76da743e>:0 
04-23 13:01:38.503 E/mono    ( 6488):   at Mapsui.UI.Forms.MapControl+<>c__DisplayClass40_0.<OnTouch>b__5 (System.Object l) [0x00051] in <50211ea8af5c495cb451c6bd76da743e>:0 
04-23 13:01:38.503 E/mono    ( 6488):   at System.Threading.Timer+Scheduler.TimerCB (System.Object o) [0x00007] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.503 E/mono    ( 6488):   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.503 E/mono    ( 6488):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.503 E/mono    ( 6488):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.513 E/mono-rt ( 6488): [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
04-23 13:01:38.513 E/mono-rt ( 6488):   at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.513 E/mono-rt ( 6488):   at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.513 E/mono-rt ( 6488):   at Mapsui.UI.Forms.MapView.HandlerTap (System.Object sender, Mapsui.UI.TappedEventArgs e) [0x0004a] in <50211ea8af5c495cb451c6bd76da743e>:0 
04-23 13:01:38.513 E/mono-rt ( 6488):   at Mapsui.UI.Forms.MapControl.OnSingleTapped (Mapsui.Geometries.Point screenPosition) [0x00012] in <50211ea8af5c495cb451c6bd76da743e>:0 
04-23 13:01:38.513 E/mono-rt ( 6488):   at Mapsui.UI.Forms.MapControl+<>c__DisplayClass40_0.<OnTouch>b__5 (System.Object l) [0x00051] in <50211ea8af5c495cb451c6bd76da743e>:0 
04-23 13:01:38.513 E/mono-rt ( 6488):   at System.Threading.Timer+Scheduler.TimerCB (System.Object o) [0x00007] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.513 E/mono-rt ( 6488):   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.513 E/mono-rt ( 6488):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-23 13:01:38.513 E/mono-rt ( 6488):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

In the pin clicked event we have this code 

`private async void MapView_PinClicked(object sender, PinClickedEventArgs e)
        {
            Device.BeginInvokeOnMainThread(async () =>
            {

                try
                {

                    if (!IsPinClicked && !IsBusy)
                    {
                        IsPinClicked = true;
                        e.Handled = true;

                        if (e.Pin.Tag != null)
                        {
                            var id = (int)e.Pin.Tag;

                            await _navigationService.NavigateAsync("DetailService");

                        }
                    }

                }
                catch (Exception ex)
                {
                    await ShowUserMessage(ex.Message);
                }
                finally
                {
                    IsPinClicked = false;
                }
            });
        }`

But never goes into the catch. 

We have created a sample project(https://github.com/antunesl/MapsuiProblemExample) so that it is possible to replicate the error. When you run the project zoom out and fast click a pin

**Comment by charlenni** [comment] 2019-05-13 13:44
Thank you for providing the sample project. It was possible to reproduce the problem and I found a solution. 

See #657.

**Comment by pauldendulk** [comment] 2019-09-23 19:31
@charlenni So, you consider it fixed? 

In some cases I await conformation of the fix from the user but since this issue is old we should close it.

**Comment by jabools** [comment] 2020-01-15 16:58
Actually this problem wasn't fixed if it comes to mutlithreaded apps. Using beta.32 with this [https://github.com/Mapsui/Mapsui/pull/657](url) PR merged, problem seems to be happening - if I modify pins collection (just by simply adding one or modifying from Task) I get this exception:
`System.InvalidOperationException: Collection was modified; enumeration operation may not execute.`
`List`1+Enumerator[T].MoveNextRare ()
List`1+Enumerator[T].MoveNext ()
MapView.HandlerTap (System.Object sender, Mapsui.UI.TappedEventArgs e)
MapControl.OnSingleTapped (Mapsui.Geometries.Point screenPosition)
MapControl+<>c__DisplayClass40_0.<OnTouch>b__5 (System.Object l)`
I was thinking about changing List to some kind of thread-safe collections, like SynchronizedCollection, which expose SyncRoot property - you should be able to lock Pins collection from the outside. What do you think, @pauldendulk ?

**Comment by pauldendulk** [comment] 2020-02-20 18:02
@charlenni Do you know the status of this issue?

**Comment by charlenni** [comment] 2020-02-20 18:55
Now, that callout doesn't use any Views from Forms, it should work even the map is changed from a background thread. But we have to test this, because now the complete pin part is nearly new.

**Comment by pauldendulk** [comment] 2020-02-21 14:12
This can be tested in 2.0.0-beta.34.

**Comment by jabools** [comment] 2020-02-21 21:25
II'm not too experienced in multithreaded programming, but - as stated in the first post - I wonder if calling `ToList()` on _pins or _callouts collections won't throw the "collection was modified" exception if during the `ToList()` function a collection would change in another thread? Just curious :)

**Comment by charlenni** [comment] 2020-02-21 22:47
Perhaps we should make a lock when copying collection to list to be sure, that collection doesn’t change meanwhile.

**Comment by jabools** [comment] 2020-02-21 23:09
I think this lock should be publicly available as readonly to allow others to lock it when needed.

**Comment by charlenni** [comment] 2020-02-22 07:17
But it is only for internal functions. It would be used, if you add or remove a pin from the list. So if the user locks the list and internally it is tried to lock the list too, than we get problems. So for me it isn’t a good idea to make the lock public.

**Comment by pauldendulk** [comment] 2020-02-22 12:46
Users should not need the lock. We should just make sure our collection can return a list without the enumeration exception. I just investigated a enumeration exception for the LayerCollection and understand what's going on. This is fixable.

**Comment by jabools** [comment] 2020-02-22 13:23
Alright, now I understand - locks should not be available publicly and should be used only within publicly available methods, like AddPin.

**Comment by pauldendulk** [comment] 2020-05-05 07:13
I consider this fixed.

**Closed by pauldendulk** 2020-05-05 07:13 UTC
Labels: bug 🐛, mapview, needs-testing 🧪
