### ISSUE TITLE
Abandon WPF renderer support

### ISSUE THREAD

**Issue by charlenni** [Mapsui/Mapsui#319] opened 2018-02-17 08:28 UTC
Perhaps we should, for the next major release, abandon WPF support. It is silly to support two rendering engines on the same system. WPF works only on WIndows, while SkiaSharp supports much more platforms, is faster and much easier to understand. And for the user it is the same. To support 2 renderers need horrible effort. So it would be much easier for us to refactor the code or add new things.

I implemented a new geometry: Circle. It has a center and a radius in meters. Implemented it in Skia in 1 h. The next 4 h I tried to implement the same in WPF and it isn't running up to now. So the next time I wouldn't make a new feature, because I had to implement it in both renderers. It's to much work.

I read the list with differences of the both renderers. The most say, that Skia is better or aren't anymore a problem (see  #318 and [fill pattern](https://forums.xamarin.com/discussion/88011/is-there-a-way-to-hatch-fill-a-rectangle) ). The only remaining difference is, that Skia couldn't display symbols in world units. Is this worth the effort?

Is there someone, who needs WPF desperatly?

**Comment by charlenni** [comment] 2018-02-18 10:45
For Skia I have the implementation for Circle ready, but for WPF I have problems with the matrices. If circles are shown, than the move not with the map. Or they aren't shown at all :(. I could make a PR and you could look, if it is ok or not.

Ok, it is good to have a reference implementation, but there are not many things, that are different. And if no one detect this differences up to now, they shouldn't be very heavy.

**Comment by pauldendulk** [comment] 2018-02-18 11:39
Summary: 
- I do not want to abandon the WPF renderer very soon
- I do not want to waste time investing in WPF
- I want to work towards equal functionality for WPF and Skia in v1. I do not want to increase the differences.

**Comment by pauldendulk** [comment] 2018-02-18 11:39
@charlenni Yes, just do a PR, I will have a look.

**Comment by pauldendulk** [comment] 2018-05-27 14:43
I will close this. My choice is not to remove WPF in the near future, but also not waste time investing in it. I think it is good to keep WPF for now because:
- I allows something to compare skia to.
- Having more than 1 implementation enforces an implementation independent interface. There have been many renderers in the past, there could be more coming. Perhaps a faster hardware accelerated one. Perhaps an implementation for Unity3D. Perhaps something more suited for web browser embedded rendering (although skia seems a good choice here).
- It makes it easier to spot regression bugs in skia.

**Closed by pauldendulk** 2018-05-27 14:43 UTC
Labels: roadmap
