### ISSUE TITLE
Sliding Map 1.4.4

### ISSUE THREAD

**Issue by Wil69** [Mapsui/Mapsui#479] opened 2018-07-23 09:08 UTC
I tried to update ma version 1.42 -> 1.44  : 
With the 1.42 I slid the map with my finger (refresh realtime) but with the 1.44 I must to lift everytime my finger for refresh the map. 
Something has changed or bug ?
Thks

**Comment by pauldendulk** [comment] 2018-07-23 21:29
Are you using xamarin forms?

There were some changes, they should have no effect, but perhaps...

**Comment by Wil69** [comment] 2018-07-24 06:46
Hello, Yes I use Xamarin Forms. 
Is there a solution or it's a bug ?

**Comment by NicoVermeir** [comment] 2018-07-24 07:14
I"m seeing the same thing, I've tried Xamarin Forms and Xamarin Android, both with 1.4.2 and 1.4.4

**Comment by pauldendulk** [comment] 2018-07-24 07:18
@NicoVermeir Do you have this problem with 1.4.2 as well?

**Comment by NicoVermeir** [comment] 2018-07-24 07:20
yes

**Comment by pauldendulk** [comment] 2018-07-24 07:21
The refresh is now always dispatched on the ui thread, even when it is already on the ui thread. Perhaps the dispatch messages are not immediately handled when other processes use too many resources.

**Comment by pauldendulk** [comment] 2018-07-24 07:22
@NicoVermeir So, this is not what @Wil69's is seeing.

**Comment by NicoVermeir** [comment] 2018-07-24 07:31
The problem @Wil69 is describing is the same as what I'm seeing, but I keep seeing it when I downgrade the nuget package to 1.4.2

**Comment by pauldendulk** [comment] 2018-07-24 19:43
I now only run on ui thread when needed and create the main looper handler only once, but I'm not really sure if this fixes the problem. This will be part of 1.4.5.

**Comment by pauldendulk** [comment] 2018-07-24 19:43
I do not test this myself on xamarin forms.

**Comment by pauldendulk** [comment] 2018-07-25 06:45
Even with Xamarin Android? I have never seen this. Could you check if all your projects updated to 1.4.5? Could you delete bin's and obj's and rebuild.

I will test with the nuget package.

**Comment by NicoVermeir** [comment] 2018-07-25 06:58
removed bin and obj, uninstalled the app from my phone, did a clean solution > rebuild solution.
issue is the same

my device is a OnePlus 5T running android 8.1

![image](https://user-images.githubusercontent.com/3177418/43184421-d55866f4-8fe8-11e8-8f9d-2f6fb37562d7.png)

**Comment by pauldendulk** [comment] 2018-07-25 08:03
Thanks for testing. I will try to look at it tonight. I have three devices to test on. I could try to the nuget package and vary the API level.

One more thing you could test. If you clone the repo and do 'git checkout 1.4' and run Samples/Mapsui.Samples.Android, do you have the same result?

**Comment by pauldendulk** [comment] 2018-07-26 09:06
I created a new Android sample (in master) using AppCompatActivity. Unfortunately it runs smooth on my Android 8.0 and Android 5.1 device. 

Could you checkout master and run the new sample? btw, deleting bin and obj is obligatory when switching between 2.0 and 1.4. Samples/Mapsui.Samples.Droid (named Droid instead of Android to avoid namespace conflicts).

**Comment by pauldendulk** [comment] 2018-07-26 09:21
oh! I can reproduce it in the 1.4 branch. No need to test for you.

So, I can reproduce it, and apparently I can fix it :) because that is what I have done in master.

**Comment by Wil69** [comment] 2018-07-26 09:49
Hi @pauldendulk I would like to know if you publish soon a new version with bug fixed, Sliding map and Label visibility (zoom) ? Thks

**Comment by pauldendulk** [comment] 2018-07-26 09:53
I will try to publish today.

**Comment by pauldendulk** [comment] 2018-07-26 09:56
btw, label visibility should already be fixed in 1.4.5, which was published earlier this week. Could you test that? Even with the sliding bug you could test it.

**Comment by pauldendulk** [comment] 2018-07-26 10:56
1.4.6 was released

**Comment by Wil69** [comment] 2018-07-26 11:33
@pauldendulk Good Job ! The bugs are fixed ! Thank you.

**Comment by pauldendulk** [comment] 2018-08-02 07:31
Great, thanks for testing @Wil69 and @NicoVermeir

**Closed by pauldendulk** 2018-08-02 07:31 UTC
Labels: bug
