### ISSUE TITLE
Blank image when I screenshot mapview on Android

### ISSUE THREAD

**Issue by xFoRdeX** [Mapsui/Mapsui#729] opened 2019-11-18 13:28 UTC
I'm trying to take a screenshot of the my MapView when I click on a button. 
It works perfectly on UWp but when I try on android, the map is totally blank. 
There is the code i'm using fot this : 
        `public Task<byte[]> TakeShot()
        {
            var _activity = CrossCurrentActivity.Current;
            if (_activity == null)
            {
                throw new Exception("You have to set ScreenshotManager.Activity in your Android 
            project");
            }
   
            var view = _activity.Activity.Window.DecorView;
            view.DrawingCacheEnabled = true;

            Bitmap bitmap = view.GetDrawingCache(true);
            view.BuildDrawingCache();

            byte[] bitmapData;

            using (var stream = new MemoryStream())
            {
                bitmap.Compress(Bitmap.CompressFormat.Png, 0, stream);
                bitmapData = stream.ToArray();
            }

            return Task.FromResult(bitmapData);
        }`
I'm using dependency injection for this. 
It is a known about mapsui or it's about android specifically ?

**Comment by pauldendulk** [comment] 2019-11-18 14:33
This might be caused by the hardware accelerator, although I don't necessarily expect this.

**Comment by xFoRdeX** [comment] 2019-11-18 15:14
I disable it and nothing change...
Do you know if i need some autorization for this ?

**Comment by pauldendulk** [comment] 2019-11-18 18:04
How did you disable it?

**Comment by xFoRdeX** [comment] 2019-11-19 08:48
In Visual Studio : Tool > Options > General and I disable the option

**Comment by johnhs91** [comment] 2019-12-16 08:01
I've run into same issue. After updating from one of the first mapsui versions. (None forms) to new forms. Now I can't get screenshot to work.
Did the hardware accelerator work at the end?

**Comment by johnhs91** [comment] 2019-12-16 08:07
Have to add, I can see the icons on the screenshot, zoom in and out. But the map isn't there.
Saw some issues with white background, is it possible that there is a middlelayer with white background (Only on screenshots) that tile layer is hiding behind somehow?

**Comment by xFoRdeX** [comment] 2019-12-16 10:47
@johnhs91 no, that didn’t change something. I search à lot about layers, but I didn’t found something good. If you have some news about this, please tell them here.

**Comment by johnhs91** [comment] 2019-12-16 11:21
My old mapsui worked. And I took screenshot of the MapControl at that time. Since MapControl is where all layers are rendered. But didn't work in this sadly. (Was a custom android renderer, that used MapControl, I used before)

Since I use forms, I can't create custom renderer for android at mapcontrol. So at the moment I'm lost.

But need to have new app version out this week, so I'm working hard on solution.

**Comment by johnhs91** [comment] 2019-12-16 13:12
I've come up with a solution.
IRenderer got a function RenderToBitmapStream(). 
This methode return memorystream of a snapshot that skiasharp made.

So what you have to do is create custom view of "Mapsui.UI.Forms.MapView" with new methode:
`        public byte[] GetSnapshot(IEnumerable<Mapsui.Layers.ILayer> layers)
        {
            using (var stream = MapControl.Renderer.RenderToBitmapStream(Viewport, Map.Layers))
            {
                return stream.ToArray();
            }
        }`

this will return byte array with snapshot of current layers (Not overlays on map).

Hope it help you.
Isn't tested on iOS. Only android.

**Comment by xFoRdeX** [comment] 2019-12-16 13:49
Thank’s a lot, i’ll try this soon. Which type is your MapControl ? Your view inherate from MapView ?

**Comment by johnhs91** [comment] 2019-12-16 13:52
It's just MapControl from MapView. IMapControl got the IRenderer. And from there you are able to call RenderToBitmapStream.

Maybe you need MapSui source files. Because I may have changed MapControl in MapView to be public instead of internal.

But the only way I had access to this.

**Comment by charlenni** [comment] 2019-12-16 17:42
I tried to implement this in MapControl and MapView. See PR #744.

**Comment by pauldendulk** [comment] 2020-01-15 18:17
I assume this was fixed with the PR. Please tell us when it's not.

**Closed by pauldendulk** 2020-01-15 18:17 UTC
Labels: question
