### ISSUE TITLE
[Xamarin] CPU usage increases when clicking map

### ISSUE THREAD

**Issue by Feroks** [Mapsui/Mapsui#575] opened 2019-01-16 08:59 UTC
When you zoom in and start clicking the map, CPU usage increases with each click and never goes down.
This is reproducible in Mapsui.Samples.Forms.UWP. In Forms.Android threads are not exiting as well, but CPU usage does not rise that quickly.

Used version: 2.0.0-beta.13

I have investigated a bit and it seems that threads are stuck in:
```
RenderGetStrategy.GetRecursive(IDictionary<TileIndex, IFeature> resultTiles, ITileSchema schema,
            ITileCache<Feature> cache, Extent extent, IList<KeyValuePair<string, Resolution>> resolutions, int resolutionIndex)
```
Here is GIF with behavior:
![cpu_usage](https://user-images.githubusercontent.com/14258841/51236819-6a7cad80-1973-11e9-91f3-d9a45b3e023b.gif)

**Comment by pauldendulk** [comment] 2019-01-16 16:22
Thanks for your clear report and gif.

**Comment by charlenni** [comment] 2019-01-16 18:22
Sorry, could reproduce this.

Problem is only, when ````InvokeInfo()```` is called, what I do in the Forms MapControl.

The problem is, that the OSM map (as all other maps too) is created with ````IsMapInfoLayer = true````. If you set this to ````false````, than the CPU usage is going down to normal 3-4%.

@pauldendulk Perhaps you could look into this, why this happens.

**Comment by charlenni** [comment] 2019-01-17 08:52
This is a bug in the Forms MapControl. When there was no user handling of single tap and double tap events, a standard handling take place. This used all layers for ````InvokeInfo()````, which is wrong. Removed the bug with #577.

Thank you for reporting the bug.

@pauldendulk It is interesting, that ````InvokeInfo()```` use so much time for a tile layer with higher zoom levels. Even if this problem is solved, perhaps it is a worth a look.

**Comment by pauldendulk** [comment] 2019-01-17 18:00
I created a new issue for the TileLayer. Will close this.

**Closed by pauldendulk** 2019-01-17 18:00 UTC
Labels: possible bug
