### ISSUE TITLE
System.AccessViolationException when call MapControl.GetMapInfo().

### ISSUE THREAD

**Issue by rogamaral** [Mapsui/Mapsui#1057] opened 2021-01-30 21:52 UTC
I am writing a WPF Behavior, for MapControl, that subscribes to the MouseMove event to provide, in addition to MouseEventArgs, the MapInfo for that position.

Some times, when dragging the map and de mouse cursor crosses the upper or lower border of MapControl, a System.AccessViolationException is throwed.

This can also be reproduced with the example provided in Mapsui.Samples.Wpf.Editing.

Run the sample, in debug mode, and drag the map until the mouse cursor crosses the upper map border.

**Comment by rogamaral** [comment] 2021-02-03 23:10
I think the MouseMove event is fired even when the mouse is outside of Viewport.Extent, which I think is not correct. 
On a standard control this does not happen. After de mouse leaves the control the MouseMove event stops firing.

I changed my behavior so that the MouseMove event is not triggered when the mouse cursor is outside that range: 

`
private bool PointIsOutOfViewport(Point point)
{
    return !AssociatedObject.Viewport.Extent.Contains(point);
}
`

Same problem occurs with MouseLeftButtonUp event.

**Comment by pauldendulk** [comment] 2021-02-12 08:40
Thanks, your instructions made this easy to reproduce.

> I think the MouseMove event is fired even when the mouse is outside of Viewport.Extent, which I think is not correct.
On a standard control this does not happen.

This is because MouseCapture is used. This can be pleasant when dragging the map because you can drag is a longer distance. See gif.

![animated-features2](https://user-images.githubusercontent.com/963462/107746444-20af4e80-6d16-11eb-8cbc-bca3a4982a8a.gif)

So at this point I would rather fix it in the GetMapInfo method. Also disabling MouseCapture would change the behavior which might be an unpleasant surprise for some users.

**Comment by pauldendulk** [comment] 2021-02-12 09:01
Fixed with https://github.com/Mapsui/Mapsui/pull/1065

**Closed by pauldendulk** 2021-02-12 09:01 UTC
Labels: bug 🐛
