### ISSUE TITLE
Polyline click not detected ? (Xamarin.Forms)

### ISSUE THREAD

**Issue by tonyfonager** [Mapsui/Mapsui#765] opened 2020-01-09 09:09 UTC
Hi there. I have searched thru the samples, and tested the Polyline sample. It has added "Clicked" event on the polyline, but it seems like the event i never raised ?

Same thing in my own app.

So the question is, if Polyline "Click" event is not implemented ? Or maybe a bug ?

Anyone used it with success ?

**Comment by pauldendulk** [comment] 2020-01-15 19:08
@tonyfonager Perhaps you could use the 'native' LineString geometry instead of the Polyline.

@charlenni Why do we have XF specific geometries? When should they be used instead of the native geometries?

**Comment by tonyfonager** [comment] 2020-01-16 09:28
Paul, I could do that - but Polyline works fine for me, so would love the "Clicked" event to work, instead of changing everything already made to LineString.

Also, on Polyline I add gps positions - it seems like I can only add Points on the LineString ?

**Comment by tonyfonager** [comment] 2020-01-16 10:06
Also, how would I detect "Click" on a LineString ?

**Comment by pauldendulk** [comment] 2020-01-25 09:27
The MapInfo sample in Mapsui.Samples.Wpf show how to get feature info in Mapsui.

**Comment by pauldendulk** [comment] 2020-01-25 14:07
@tonyfonager I noticed the MapInfo sample did not show the info in the Xamarin.Forms sample. I added this to the sample and also made the callback run on the ui thread.

**Comment by pauldendulk** [comment] 2020-01-25 14:14
@charlenni The MapInfo callback did not run on the UI thread. Although each user could sync it individually it is better to have it in the UI thread right away. I needed to do some digging to find the cause. This was in the logic to detect a double tab. A timer was started and from the code on that timer thread the callback events were invoked. I now used an async delay instead. 
https://github.com/Mapsui/Mapsui/commit/44130afc4cd2bb42429b22d7ff2e49795de619fd#diff-b6ea5c0d984ed5d18f836ec68b88b6c3R175

I hope this has no other consequences. It is hard to judge because the touch detection logic has grown quite convoluted. Lots of code and long methods in the form MapControl and the MapView. Perhaps we could also take a look at that when fixing the callout.

**Comment by pauldendulk** [comment] 2020-01-25 15:51
@charlenni I now also replace the timer itself with a boolean to check if we it is waiting on a double tap (waitingForDoubleTab). 

But now that OnSingleTabbed is on the UI thread creating the Callout locks the UI. Something that came up on the other thread. Lets discuss this further on this thread: https://github.com/Mapsui/Mapsui/issues/783

**Comment by charlenni** [comment] 2020-01-27 11:01
> @charlenni Why do we have XF specific geometries? When should they be used instead of the native geometries?

I assume I had to say something about structur of the Xamarin.Forms part. We have a normal MapControl as all other Mapsui platforms. It provides things like touch handling and so on. And than there is a MapView component. This component mimics the original Xamarin.Forms MapView control. So it is possible to replace the normal maps component with the Mapsui one. Because of this, we have Pins and Polylines and another coordinate system. This are all things, which don't belong to the normal Mapsui and special for Xamarin.Forms. 

> @charlenni The MapInfo callback did not run on the UI thread. Although each user could sync it individually it is better to have it in the UI thread right away. I needed to do some digging to find the cause. This was in the logic to detect a double tab. A timer was started and from the code on that timer thread the callback events were invoked. I now used an async delay instead.
44130af#diff-b6ea5c0d984ed5d18f836ec68b88b6c3R175

I'm not sure, if callbacks of events should always run in the main thread. If you want to do something in this callback that needs functionality of the main thread, than the user have to run it on the main thread. But not all events should by default run on the main thread.

**Comment by charlenni** [comment] 2020-01-27 14:20
In this case, the problem is the LineString implementation at [line 237](https://github.com/Mapsui/Mapsui/blob/18c1c2330533518cd0a60ad36dee60301af0ea2e/Mapsui.Geometries/LineString.cs#L237). The Forms MapView checks, if LineSring.Contains the clicked point. But LineString doesn't check, but returns false immediatly.

This part of the code was made before creation of GetMapInfo(). I now changed handling to the new functions. See #785. Should now work for Pins and all Drawables.

**Comment by pauldendulk** [comment] 2020-01-29 08:51
This should be fixed in the next release 2.0.0-beta.33.

**Comment by tonyfonager** [comment] 2020-01-29 19:08
Thanks. Looking forward to the update. Any ETA ?

**Comment by pauldendulk** [comment] 2020-02-01 14:30
@tonyfonager There is some work to be done for the callout feature so it could take a while.

**Closed by pauldendulk** 2020-02-01 14:30 UTC
Labels: possible bug

**Comment by sailman342** [comment] 2020-02-03 12:38
if you are working with sources from the master

https://github.com/Mapsui/Mapsui/blob/master/Mapsui.Geometries/LineString.cs

you can modify the contains() method
```

        public override bool Contains(Point point)
        {
            // Stupid correction by Z92 alias sailman342
            double someParameterToBeDefinedByMapsuiDesigners = 50.0;
            double distance = this.Distance(point);
            if (distance < someParameterToBeDefinedByMapsuiDesigners)
            {
                return true;
            }
            else
            {
                return false;
            }

        }


```


So you Don't have to modify your code waiting for the implementtation ;-)

**Comment by sailman342** [comment] 2020-02-03 12:40
Just to note that Polyline has a IsClickable property while Pin has none :-)
