### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by gpsaliola** [Mapsui/Mapsui#1414] opened 2021-12-10 11:05 UTC
I have encountered in iOS a performance problem when many lines (eg 400) are drawn.
The problem occurs when all the lines are visible.
I have tried in Android and there are no problems.

**Comment by pauldendulk** [comment] 2021-12-10 12:16
That is peculiar. Does the zoom level make a difference?

**Comment by gpsaliola** [comment] 2021-12-10 12:52
Actually the problem occurs when all the lines are visible.
If I reduce zoom and make all lines visible the problem occurs.
If all the lines are in a small phisical space they are always visible.

**Comment by pauldendulk** [comment] 2021-12-11 07:13
> I render the lines only in OnAppearing form event with an asyncronous task.

You render to the lines? What if you add the lines to MemoryLayer/MemoryProvider like in the LineStringSample?

**Comment by gpsaliola** [comment] 2021-12-11 08:53
This is the code I've used:

```
                LineString line = new LineString();
                List<Feature> featureList = new List<Feature>();

		// Get points from GPX (more than 1500 points)
                foreach (XsdGpx.trksegType seg in trk.trksegCollection)
                {
                    foreach (XsdGpx.wptType wpt in seg.trkptCollection)
                    {
                        var point = SphericalMercator.FromLonLat((double)wpt.lon, (double)wpt.lat);
                        line.Vertices.Add(point);
                    }
                }

                VectorStyle lineStyle = new VectorStyle
                {
                    Fill = null,
                    Outline = null,
                    Line =
                    {
                        Color = new Mapsui.Styles.Color(255, 0, 0),
                        Width = 3,
                        PenStyle = Mapsui.Styles.PenStyle.Solid
                    }
                };

                Feature lineFeature = new Feature()
                {
                    Geometry = line,
                };
                lineFeature.Styles.Add(lineStyle);
                featureList.Add(lineFeature);

                Layer lineLayer = new Layer
                {
                    DataSource = new MemoryProvider(featureList),
                    Name = "layerName",
                    Style = null
                };
                mapView.Map.Layers.Add(lineLayer);

```

**Comment by pauldendulk** [comment] 2021-12-11 09:19
Could you provide a minimal reproducible sample?

**Comment by gpsaliola** [comment] 2021-12-11 10:38
for iOS?

**Comment by pauldendulk** [comment] 2021-12-11 14:40
You do not have android version? You do use Xamarin.Forms, or not?

**Comment by gpsaliola** [comment] 2021-12-11 15:52
Yes the problem is on Android also. I am preparing it.....

**Comment by gpsaliola** [comment] 2021-12-11 17:07
You can download the sample here: https://www.okmap.org/a/OkMapXamarin.zip
On Android emulator works fine but on iPhone phisical device, after created some tracks, the program freezes.
The tracks are on Rome - Italy.

**Comment by pauldendulk** [comment] 2021-12-12 11:40
Thanks for the sample, that helps a lot. If you could exclude the bin, obj and packages folder next time it would be even better.

### Reproducing

I can reproduce the problem. It is indeed peculiar. When zoomed out it is not fast, but when zooming in (and less vertices are drawn) it becomes even slower. You would expect the opposite. 

### Possible Explanations
- We have a clipping algorithm. Perhaps that is slower when more vertices fall outside of the clipping box.
- Perhaps skiasharp is somehow slower when it has to draw outside of the visible area. This is something we have observed before, and that is why the clipping was added. Then again, if the clipping works as it should this should not happen.

### Workarounds

- Wrap the layer in a RasterizingLayer. For instance in line 115 of Maps.xaml.cs you could write: ```mapView.Map.Layers.Add(new RasterizingLayer(lineLayer));```. There are some disadvantages. Ugly blown up pixels during zooming in, and when panning the points outsize of the previous extent are not immediately visible.
- Do some preprocessing in your own IProvider. So you need to create a custom IProvider. You can start out with a copy of the MemoryProvider. Two options that come to mind:
  - Use a modified version of the clipping method of Mapsui to return only the clipped LineString. See 'ClippingExtension.ToSkiaPath(this IEnumerable<Point> lineString, ... '. This one transforms to SkiaPath. You will need to rewrite it to transform to LineString. The clipping may still be slow but it will be on a background thread.
  - Do not build the gps path as one big LineString, but create a lot of smaller LineStrings. Perhaps cut up in sections of 100 vertices, or 1000. Just see what works. Selecting the LineString as a whole might not work as expected.

### Priority

Unfortunately, for me personally there are several other things that I should give priority.

### CC 

@tonyfonager. Perhaps this is also relevent for you?

**Comment by tonyfonager** [comment] 2021-12-12 13:31
@pauldendulk I sounds like the same performance issues I am having, indeed.

But as I sometimes have up to 20-30k lines, I saw no other resolution that using the RasterizingLayer and just accepting the blown up lines when zooming and slow adding when panning.

But do let me know if you figure something out ;-)

**Comment by gpsaliola** [comment] 2021-12-12 16:59
@pauldendulk Thank you very much!
The solution you have provided me:
`mapView.Map.Layers.Add(new RasterizingLayer(lineLayer));`
works fine.
Ugly blown up pixels during zooming in last about a second and it is an acceptable behavior.
In your opinion, could it be useful to use this method for pins as well?

**Comment by pauldendulk** [comment] 2021-12-13 05:25
> In your opinion, could it be useful to use this method for pins as well?

Mapsui draws all pins on every iteration, so it is always possible there are too many pins to handle, so when the number of pins becomes too large you have to. But then again, what sense does it make to draw an immense number of pins on the screen? This will be confusing for the user. So, you should also think of showing pins depending on the zoom level. Or perhaps doing some filtering in a custom provider. Do only return a selection of pins if they are too many returned by a request.

**Comment by gpsaliola** [comment] 2021-12-13 08:49
@pauldendulk Thanks for the reply. What you say seems very reasonable to me.
Are you planning to release a new version soon?

**Comment by pauldendulk** [comment] 2021-12-17 06:12
> Are you planning to release a new version soon?

Well, this might take some time. I want to do some work on Animations now. Then I need to get the NTS port done. Then we have to get to a stable release will multiple new UI frameworks. That will take some time. And that will not include a performance fix.

**Comment by inforithmics** [comment] 2021-12-18 16:40
I had a quick look at it (I profiled it in Windows UWP). What I saw was that most time was used drawing the pathes in Skia. So it could be a Skia Sharp issue.  (75% rendering in Skia Sharp and 25% Clipping Time). But I didn't see an immediate fix because as I said most time was used in Skia Sharp drawing. So Rasterizing Layer would definitly help

**Comment by pauldendulk** [comment] 2021-12-23 18:56
I don't know how the clipping works. 
- Does it add new points where the line crosses the extent of the visible map.
- or does it keep all original points and just remove the segments that do not cross the visible extent. 
 
If it it is that last option that it could be that long stretches outside of the visible area take a lot of time in skiasharp. It is weird dat something not visible should take so much time but I have seen it before. 

Apart from our own point clipping function there is also the option in SkiaSharp to add a clipping extent. That might also help (but perhaps we already do that).

**Comment by charlenni** [comment] 2022-01-10 16:04
Another approach would be to convert the LineStrings by yourself to SKPath and add them in IFeature.RenderedGeometry. It takes much time for Skia, if a SKPath is always new. If it is always the same, then Skia could upload it to the GPU and use it again and again. For this you need an own style and an own style renderer.

The clipping was done, because Skia has problems with dashed lines, that are very big. One of the tests used this.

**Comment by pauldendulk** [comment] 2023-06-23 20:34
Closing this. Directly drawing a LineString can always be a  problem if it has too many features. In Mapsui this can be solved by adding the RasterizingLayer or the RasterizingTileLayer. Also the is the option to Simplify. See the samples in the 'Performance' category.

**Closed by pauldendulk** 2023-06-23 20:34 UTC
Labels: possible-bug
