### ISSUE TITLE
Disable WMS when internet is not available

### ISSUE THREAD

**Issue by LeoCarriere** [Mapsui/Mapsui#2123] opened 2023-07-28 08:36 UTC
Hello,
I have made a simple WPF application using MapsUI (great work btw).
Bing Aerial and OpenStreetMap layers was added like it is done in the samples (KnownTileSource for Bing and Mapsui.Tiling.OpenStreetMap for OSM).
I aslo added a Google Maps layer and a Google Maps Satellite view using @pauldendulk solution here https://github.com/Mapsui/Mapsui/issues/954#issuecomment-650984123 and some Mbtiles layer for offline use.
Then a UserControl is here to enable or disable each layer of my MapControl.
![Screenshot 2023-07-28 100444](https://github.com/Mapsui/Mapsui/assets/45718362/7824feb2-93fe-400f-b3fc-236daa04cf1c)

Everithing works fine while an internet connection is available however if there is no internet the app become unusable probably due to BruTile always trying to fech unreachable tiles.

I was thinking of a workaround where I test for internet on the first load of the map control to disable each layer that need a connection (as they are helpful but not crucial for my use case), but I will still have a problem if the connection fails during work with the app.

Do you have some ideas of a strategy to avoid the problem ?

**Comment by inforithmics** [comment] 2023-07-30 21:38
You could use SqlPersitentCache for caching the tiles. In the KnownTileSource Create there is a persistentCache Parameter where you could use sqlPersistentCache,  because it implements the IPersistentCache interface.

Something like this
```
var persistentCache = new SqlitePersistentCache(cacheFilePath);
KnownTileSources.Create(KnownTileSource.OpenStreetMap, persistentCache:persitentCache);
```

**Comment by LeoCarriere** [comment] 2023-07-31 08:57
Thank you @inforithmics, using a persistent cache was a good addition but it seems like I still run into the same issue when I restart the app offline and navigate outside of the cached area.

_I recorded a short video clip to better understand the situation :_
https://github.com/Mapsui/Mapsui/assets/45718362/c49a65bb-c57c-46f1-ac2b-0fc55565a6e4

_Here is one working fine with tiles layers disabled :_
https://github.com/Mapsui/Mapsui/assets/45718362/4f63d20e-a4f7-4d4a-8672-06941fc88cb5

Note that the CPU/GPU load stays pretty low this is why I think loading tiles is overloading the main UI thread blocking user inractions in the process, however I am not sure how to debug this and I might be targeting the wrong issue.

**Comment by inforithmics** [comment] 2023-08-01 06:46
The problem is that currently Mapsui Executes the Requests on the UIThread. With this Pull Request it should be fixed.
https://github.com/Mapsui/Mapsui/pull/2109

**Comment by LeoCarriere** [comment] 2023-08-01 08:59
Hey @inforithmics sorry I never used a nuget.config file before so it took me couple minutes to figure it out.
I used **Mapsui.Wpf.4.0.0-91-gb93fafc6c.nupkg** and **Mapsui.Extensions.4.0.0-91-gb93fafc6c.nupkg** from your download and made sure to disable BruTile  / BruTile.MbTiles from nuger.org package source, clean solution rebuilt etc.

It is not working but I think you are very close to the solution. After adding the right packages, **my testing scenario was the following :**
- I fire the application with the Ethernet cable connected.
- Then if I unplug it while running it's working most of the time. The bug is rarely happend by navigating for a while and somtimes I experiance ocasionnal shuttering which is managable. 

It is just when I first load the MapControl offline (and stay offline) that the app is unusable.

(I let you know in case you missed an easy fix but i can see my first idea work on my use case.)

**Comment by LeoCarriere** [comment] 2023-08-01 09:39
If it can help I just created a brand new project **WPF .Net 6** with just a simple map :
```cs
var map = new Map();
/* Add Bing Map Aerial online */
string path = @"C:\ProgramData\MyMaps\cache";
var persistentCache = new SqlitePersistentCache(path);
var source = KnownTileSources.Create(KnownTileSource.BingAerial , persistentCache:persistentCache);
TileLayer bingSat = new TileLayer(source);
bingSat.Name = "Bing Aerial";
map.Layers.Add( bingSat );
MyMapControl.Map = map;
```
When the bug is happening the Debug Output window get flooded with some of these messages (in random order) :
`Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll`
`Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll`
`An error occurred while fetching data. Exception: No such host is known. (t1.tiles.virtualearth.net:443)`
`An error occurred while fetching data. Exception: No such host is known. (t2.tiles.virtualearth.net:443)`
...
`MapsuiOfflineTests Warning: 0 : An error occurred while fetching data. Exception: An error occurred while sending the request.`
`MapsuiOfflineTests Warning: 0 : An error occurred while fetching data. Exception: No such host is known. (t3.tiles.virtualearth.net:443)`

**Comment by inforithmics** [comment] 2023-08-01 09:42
I made some fixes in the latest brutile (which is not released yet).

https://github.com/BruTile/BruTile/suites/14223481110/artifacts/798298591

**Comment by inforithmics** [comment] 2023-08-01 09:42
I'll try your sample code

**Comment by inforithmics** [comment] 2023-08-01 10:09
I found some Code where the Async Handling could be improved.
https://github.com/Mapsui/Mapsui/pull/2109/commits/a88f50108b08769298a8400e4f8f55bb8e79bfe3

What I discovered is that you shouldn't start your Application with an attached debugger. Because of the many exceptions the IDE slows down the code. If you start it without attached debugger it is quite responsive.

So start your project without debugging Ctrl + F5 (In Visual Studio) instead of F5 (with Debugging in Visual Studio)

**Comment by LeoCarriere** [comment] 2023-08-01 10:10
Keep me updated, I didn't manage to try with both **MapsUI** and **BruTiles** due to versioning.
`Error	NU1605	Warning As Error: Detected package downgrade: BruTile from 5.0.4 to 5.0.4-10-gd7a84bb. Reference the package directly from the project to select a different version. `
` MapsuiOfflineTests -> Mapsui.Extensions 4.0.0-91-gb93fafc6c -> BruTile (>= 5.0.4 && < 6.0.0) `
` MapsuiOfflineTests -> BruTile (>= 5.0.4-10-gd7a84bb)	MapsuiOfflineTests	C:\Users\lc\source\repos\MapsuiOfflineTests\MapsuiOfflineTests\MapsuiOfflineTests.csproj	1	`

MapsuiOfflineTests.csproj :
```xaml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="Mapsui.Wpf" Version="4.0.0-91-gb93fafc6c" />
	<PackageReference Include="Mapsui.Extensions" Version="4.0.0-91-gb93fafc6c" />
        <PackageReference Include="BruTile" Version="5.0.4-10-gd7a84bb" />
  </ItemGroup>
</Project>
```

**Comment by inforithmics** [comment] 2023-08-01 10:12
But you could still disable the layer with a detection that there is no network access.

Sample code for example here for wpf
https://github.com/xamarin/Essentials/pull/1079/files#diff-754db1455d407533fbc6e2addf4cb394761af8e0bc37c3e4f617858e7d2d5d54

**Comment by LeoCarriere** [comment] 2023-08-01 10:19
Good job @inforithmics starting without debugging worked like a charm 😁
I'll try your sample, if something come out I'll keep you updated, thank you again !

**Comment by pauldendulk** [comment] 2023-10-02 19:58
I assume this is improved in 4.1.0-preview.1.

**Closed by pauldendulk** 2023-10-02 19:58 UTC
Labels: enhancement
