### ISSUE TITLE
Intermittent crash on UWP 

### ISSUE THREAD

**Issue by tizumiZoo** [Mapsui/Mapsui#313] opened 2018-02-12 02:31 UTC
Having an intermittent crash issue on UWP. I have encountered the issue with HP Elite 2 and Surface (not sure the model), though not with some others.

Do not seem to be happening with Debug build but does Release build.

We use Xamarin.Form and the map is one of pages in our application. Using Xamarin form's custom viewrenderer as in one of posts in Issues. When the page is popped, renderers Dispose is called.
We use a couple of TileLayers for map layers in our application.

Updated UniversalWindowsPlatform, XamarinForm, and BruTile to up to date versions, but the crash still happens.

**Comment by tizumiZoo** [comment] 2018-02-12 02:42
Checking and debugging with Mapsui source, found out that there is no 'Dispose' method for UWP's MapControl, probably because base is not disposable (and 'Dispose' is not called anyway from the viewrenderer's Dispose), however, it would be (maybe, or maybe doesn't matter...) better to have a way to unsubscribe some event handlers like

CompositionTarget.Rendering
SimpleOrientationSensor.GetDefault().OrientationChanged (?)
_renderTarget.PaintSurface

Making some changes in mapsui source and debugging, the crash seems to be not happening by;

- Added 'Dispose' method with unsubscribing above plus others like ManipulationDelta etc, basically undoing some of the stuff done in constructor (not sure if necessary)
- Added AbortFetch then 3s delay in viewrenderer before disposing
- try-catch in MapDataChanged() and _renderTarget_PaintSurface but NOT re-throwing it.
- bunch of logging

I assume it is timing issue but not being able to exactly spot the part causing it...

**Comment by pauldendulk** [comment] 2018-02-12 17:20
You say " When the page is popped, renderers Dispose is called." Is this the Xamarin.Forms renderer?

The UWP MapControl does indeed not have a Dispose method because that is how WPF/UWP components are designed. In WPF 'weak references' were added to fix a memory leak. Perhaps this is also needed for UWP. I do not expect a crash perse. I have to look into it.

**Comment by radderz** [comment] 2018-02-12 20:33
I don't have any of these dispose issues anymore, but I had to use locks and a override the Dispose method in the renderer. I used this to destroy anything that would cause object is disposed issues. I then use locks when accessing properties of the map which need to be set to null once the dispose occurs. It really comes down to being sure that you aren't trying to call map changes after the renderer is disposed.

**Comment by tizumiZoo** [comment] 2018-02-13 01:49
Yes, this is Xamarin.Forms viewrenderer (i.e. inherite Xamarin.Forms.Platform.UWP.ViewRenderer<> for mapsui control and a xamarin form custom view).
Probably not really 'Dispose' method in MapControl, as it is not disposed anyway, but maybe something in Unloaded event to unsubscribe static event(s)?

@radderz 
I suspected race condition with background tasks started by TileLayer and added lock and even a delay in renderer Dispose before disposing renderer, or even wait some seconds before opening the map again, but still intermittently happening...

What I have done  in the end is to have made MapControl object in custom renderer static (as it is not disposed anyway), and assign/de-assign Map object as OnElementChanged accordingly. Seems to be working better.

Good things about retaining MapControl object is when opening it again, it's much quicker (probably not rendering again??) and memory usage increase I could observer last time when opening/closing repeatedly does not seem to be happening.

Hence I now suspect an issue can be in SkiaXmlView. Can it be anyway not cleaning up resources properly?

Just a note, this issue does not occur in every device, a certain devices I tested, and even more likely occurring with Release build but less likely with Debug build...

**Comment by tizumiZoo** [comment] 2018-02-21 08:33
Issue seems, to me,  to be related with Map and Viewpoint objects being used in rendering/drawing in ui thread while they can be manipulated in other threads. Can this be an issue? It's really intermittent and seems to occur after certain steps but not all the time. One of them is panning gesture while seemingly initially loading/rendering/drawing...

**Comment by tizumiZoo** [comment] 2018-02-21 08:36
By the way, not seems to bedispose issue any more after making mapcontrol state, but tends to happen after closing entire application and opening again.

**Comment by pauldendulk** [comment] 2018-03-04 07:35
Yes, it seems there is still some cross thread feature access at some point. This needs to be fixed. For now I've put a try catch in UWP MapControl.DataChanged. If exceptions occur this should only affect the graphics at that point. There exception is logged. You can receive the log entry with like [this](https://github.com/pauldendulk/Mapsui/wiki/How-to-work-with-Mapsui#logging).

**Comment by tizumiZoo** [comment] 2018-03-06 06:09
Thanks for your reply. 

I have been using the Mapsui logging, and that's how I have been trying to debug the issue as the crash somehow is not caught by unhandled exception handler. It seems to be unmanaged code exception and crash straight away.

Probably try-catch should be in _renderTarget_PaintSurface() instead, as what MapDataChanged() does is to call RefreshGraphics(), and it just invalidates renderTarget. The SkiaXamlCanvas, on invalidate, calls CoreDispatcher.RunAsync() which calls PaintSurface event handler (_renderTarget_PaintSurface()). (However, I added try-catch in _renderTarget_PaintSurface still not catch the exception).

I also slightly changed _renderTarget_PaintSurface() by unsubscribing touch event before rendering and copying viewport like below;

private void _renderTarget_PaintSurface(object sender, SKPaintSurfaceEventArgs e)
        {
            Logging.Logger.Log(Logging.LogLevel.Information, "MapControl._renderTarget_PaintSurface called");

            if(_renderer == null) return;
            if (_map == null) return;
            if (!_invalid) return;

            Logging.Logger.Log(Logging.LogLevel.Information, "MapControl.TryInitializeViewport calling");
            TryInitializeViewport();
            if (!_map.Viewport.Initialized) return; 
            
            if (_skiaScale == null) _skiaScale = GetSkiaScale();
            Logging.Logger.Log(Logging.LogLevel.Information, "Scaling SKCanvas");
            e.Surface.Canvas.Scale((float)_skiaScale.X, (float)_skiaScale.Y);
            Logging.Logger.Log(Logging.LogLevel.Information, "Render calling");

            // Turn off gesture
            ManipulationMode = ManipulationModes.None;
            
            var viewportCopy = new Viewport(Map.Viewport);
            viewportCopy.TryInitializeViewport(_map, ActualWidth, ActualHeight);
            _renderer.Render(e.Surface.Canvas, viewportCopy, _map.Layers, _map.Widgets, _map.BackColor);

            // Turn back on
            ManipulationMode = ManipulationModes.Scale | ManipulationModes.TranslateX | ManipulationModes.TranslateY | ManipulationModes.Rotate;

            _renderTarget.Arrange(new Rect(0, 0, Map.Viewport.Width, Map.Viewport.Height));
            _invalid = false;
            Logging.Logger.Log(Logging.LogLevel.Information, "End MapControl._renderTarget_PaintSurfacecalling");
        }

which "seems" to have helped a bit when touching screen while loading (not totally sure if really did) but still crashing, now somehow after changing network condition, like disconnecting from network or disablign wifi. Suspected an issue like https://github.com/dotnet/corefx/issues/25224 , though I am not using App Store, and trying to pass a custom TileFetcher to HttpTileSource of TileLayer but still not successful.

**Comment by pauldendulk** [comment] 2018-03-06 08:31
Thanks for the information. This needs to be investigated thoroughly. Inside the skia renderer there is already a try-catch that is why I did not add in _renderTarget_PaintSurface, but apparently there is some crash at a higher level.

**Comment by pauldendulk** [comment] 2018-05-27 15:37
I did not manage to reproduce this myself and had no other reports on this. Also there have been some changes in here is well, so I will close this. Please post a new issue when anyone encounters this problem again.

**Closed by pauldendulk** 2018-05-27 15:37 UTC
Labels: bug
